### ISSUE TITLE
Is there way to get page language using pnpjs

### ISSUE THREAD

**Issue by asith-w** [pnp/pnpjs#2769] opened 2023-08-29 20:52 UTC
### What version of PnPjs library you are using

3.x

### Minor Version Number

1.0

### Target environment

All

### Additional environment details

sharepoint site with Site languages
![image](https://github.com/pnp/pnpjs/assets/5784846/0ae5af8d-64fd-474f-894d-fb68e4ec7e8c)

### Question/Request

I'm struggling to get a current page selected language as below image for my spfx extension project . if there are 2 or more languages are added item. I tried siteLangPref cookie but it doesnt looks correct .  

![image](https://github.com/pnp/pnpjs/assets/5784846/93c5a7cd-9600-4491-865b-0ace6b72b846)

**Comment by bcameron1231** [comment] 2023-08-30 20:59
The translated language is stored as property on the SharePoint Site Page item called **_SPTranslationLanguage**

This is outlined nicely in a blog by Elio
https://www.eliostruyf.com/multilingual-apis-modern-sharepoint/

You can use renderListDataAsStream
```
  const list = await sp.web.lists.getByTitle("Site Pages");
  return list.renderListDataAsStream({  ViewXml: `
      <View Scope=\"RecursiveAll\"><ViewFields><FieldRef Name=\"_SPIsTranslation\" /><FieldRef Name=\"_SPTranslatedLanguages\" /><FieldRef Name=\"_SPTranslationLanguage\" /><FieldRef Name=\"_SPTranslationSourceItemId\" /></ViewFields><Query><Where><Eq><FieldRef Name=\"ID\" /><Value Type=\"Number\">1</Value></Eq></Where></Query><RowLimit /></View>
      `,});
```
You can select directly from the properties
`   await sp.web.lists.getByTitle("Site Pages").items.getById(9)()`
![image](https://github.com/pnp/pnpjs/assets/7944457/12761c1f-75aa-4117-942a-3179a69b0813)

**Comment by juliemturner** [comment] 2023-08-30 21:31
Duplicate of #2300 for another way.

**Closed** 2023-09-01 17:28 UTC
Labels: type: question, status: answered
