### ISSUE TITLE
LastItemModifiedDate for list item not working as expected

### ISSUE THREAD

**Issue by milindsaraswala** [pnp/pnpjs#1982] opened 2021-12-19 10:33 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.3.8 ]

Please specify what version(s) of SharePoint you are targeting: [ 2019]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am using below SharePoint REST API to get any changes to the List Items and I am getting expected value

http://revamp.corp.xxx.com/_api/web/lists/GetByTitle('FormSettings')/LastItemModifiedDate

But same thing I am trying to do with PNPJS it gives me date/time of setting changes of the list itself not item changes

await $pnp.sp.web.lists.getByTitle("FormSettings").get()

what I am doing wrong

**Comment by juliemturner** [comment] 2021-12-22 15:40
Sorry, I don't know that I can help you as we no longer support version 1.x and I don't have a 2019 server to even spin it up on.  Maybe someone else has some guidance.  I did test this in V2 and I'm seeing that the call works correctly.  I would check the network console to see the call being made by PnPjs and inspect the return payload that could help you work out where the problem is.

**Comment by patrick-rodgers** [comment] 2022-01-03 19:41
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2022-01-03 19:41 UTC
Labels: area: code, type: someting isn't working
