### ISSUE TITLE
Error: "export 'combinePaths' was not found in '@pnp/common'

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#253] opened 2018-09-22 19:42 UTC
### Category
- [ x] Question

### Version 

Please specify what version of the library you are using: [    Latest     ]
```

WARNING in ./node_modules/@pnp/sp/dist/sp.es5.js 323:31-43
"export 'combinePaths' was not found in '@pnp/common'
 @ ./node_modules/@pnp/sp-addinhelpers/dist/sp-addinhelpers.es5.js
 @ ./node_modules/@pnp/pnpjs/dist/pnpjs.es5.js
 @ ./src/app/loader.js
```

Loader.js: 

`require("@pnp/pnpjs");`

I'm getting a lot of these, not sure what the issue is. I'm trying to bundle only the pnpjs module. 

Can I ignore this warning? Thanks.

**Comment by koltyakov** [comment] 2018-09-23 08:06
Duplicate of #254. Closing this one.

**Closed by koltyakov** 2018-09-23 08:06 UTC
