### ISSUE TITLE
SharePoint Online & SharePoint Web Services Access without License using Pnp JS

### ISSUE THREAD

**Issue by pandyla** [pnp/pnpjs#2132] opened 2022-02-28 05:45 UTC
I am facing an issue on my QA tenant. I have a SPFX created which is doing CRUD operation in SharePoint Online Lists and Libraries. I have used PnP Js for the rest calls. For a E3 standard license person that is working smoothly without 401 error but for users who don't have the license assign it is working sometimes and sometimes it is failing with 401 error.

For unlicensed user that scenario of getting failed is also not consistent. In between the process after inserting one item in the list it is getting failed with 401.

Can anyone help me to know the reason about this inconsistent behavior. If E3 license is required for users to use and interact with SharePoint Online and SharePoint web service then it has to fail from the beginning. Why it is allowing to perform some tasks and getting failed in between.

ETag value is getting missing for the rest calls with Pnp JS in between the process. For Licensed users not facing this issue but for unlicensed users sometimes it is coming and sometimes not coming. 

![Issue](https://user-images.githubusercontent.com/87748553/155930505-16570c20-3fc9-4e7d-84df-f4453c03ca89.png)

Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [         ]

Please specify what version(s) of SharePoint you are targeting: [         ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by pandyla** [comment] 2022-03-01 11:06
E3 or any license is mandatory for Pnp JS to work smoothly with SharePoint Online?

**Comment by koltyakov** [comment] 2022-03-01 11:20
A question is not about a licence requirement to use PnPjs but for REST API(s) usage with specific licence conditions. I have little experience with the use cases with unlicensed users (external users I guess) but definitely there are some differences, and for external users not everything will work smoothly. But intermittent nature, if you're sure that the same exactly API call and object sometimes OK sometimes 401, is a subject to tenant support.

**Comment by patrick-rodgers** [comment] 2022-03-01 15:52
The SharePoint API itself does not enforce license restrictions, but that doesn't mean all features won't. As @koltyakov said this is outside the control of this library - the library itself doesn't do anything with licensing.

What is your scenario that unlicensed users are needing to make API calls?

**Comment by iamguptarishi** [comment] 2022-03-01 22:38
@patrick-rodgers / @koltyakov - This is a dev tenant and not all users have license assigned to them. This issue might not happen in prod. But we are trying to understand the root cause. The question is, are these 401 error because of license, as users who have appropriate licenses are able to make edits and updates for all the requests. The issue is when we are looping through the items and moving them from one list to another. The code is able to move first 1-2 items and then it throws 401 error for rest of the items. The 401 error continue for all the subsequent requests to SharePoint.

**Comment by patrick-rodgers** [comment] 2022-03-02 01:49
I'd suggest asking this in [sp-dev-docs](https://github.com/SharePoint/sp-dev-docs/issues) as it is not something this library can control. Thanks!

**Closed by patrick-rodgers** 2022-03-02 01:49 UTC
Labels: area: non-library
