### ISSUE TITLE
Does not work in IE11

### ISSUE THREAD

**Issue by jusper-dk** [pnp/pnpjs#237] opened 2018-09-11 18:46 UTC
### Category
- [ ] Enhancement
- [X ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

1.2.1

### Expected / Desired Behavior / Question
var q = sp.web.lists.getById('123').items.select(['Title'])
q.toUrlAndQuery()

returns:
"_api/web/lists('123')/items?$select=Title"

### Observed Behavior
Causes an error. With additional polyfills returns

"_api/web/lists('123')/items?"

### Steps to Reproduce

Just make any request to a list

**Comment by jusper-dk** [comment] 2018-09-11 20:03
Already checked - does not help. At least 'Array.from' implementation is required now but even with a corresponding polyfill, the following code does not work since IE does not support iterators for Map and Set:
url += "" + char + Array.from(aliasedParams).map(function (v) { return v[0] + "=" + v[1]; }).join("&");

**Comment by gregwilton** [comment] 2018-09-12 00:32
I've been running into this issue as well. It's not exactly an issue with the PnP JS library but I'm coming to the conclusion that if support for IE 11 is required then `Array.from` can't be used with `Map` objects (which is what the [toUrlAndQuery](https://github.com/pnp/pnpjs/blob/a085a66f6528bcd9a7806c2e87d2182dcbeaadcb/packages/sp/src/sharepointqueryable.ts#L99) method is doing).

The simplest way to test is by adding the following to a blank HTML page:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
<script>
  console.log(Array.from(new Map([['$select', 'Url']])));
</script>
```

Chrome will output an array of length 2 but IE 11 will output an empty array.

Which I think might be caused by this issue mentioned on the [Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill) MDN page.

> In addition, since true iterables can not be polyfilled, this implementation does not support generic iterables as defined in the 6th edition of ECMA-262.

Also related: [Polyfill fails in IE11 when using Array.from of a Map](https://github.com/Financial-Times/polyfill-service/issues/1209).

**Comment by jusper-dk** [comment] 2018-09-13 08:32
So, am I right that you're not going to support IE11 anymore? The bug originally appeared in 1.1.5. 1.1.4 works fine in IE11.

**Comment by koltyakov** [comment] 2018-09-13 08:50
We're are not going to do not support IE11.
Figuring out, with my usual set of polyfills a face no issues in IE11, but there are issues in IE10 (which is also bad as some OnPrem installation are configured by default to use IE10 compatibility downgrade.

@gregwilton this is a result in IE11 on a random project with standard polyfills set I use in many project setups:
![image](https://user-images.githubusercontent.com/7816483/45477769-f32bd880-b74a-11e8-8168-69a14a566557.png)

**Comment by koltyakov** [comment] 2018-09-13 09:10
I have these polyfills along with Fetch and ES6 Promise:

```typescript
import 'core-js/es6/array';
import 'es6-map/implement';
```

Could you guys please check is these polyfills help in your project setup?

**Comment by jusper-dk** [comment] 2018-09-13 16:00
I can confirm now that 'es6-map' works fine for me too. Here are the polyfills that make pnp/sp working in ie11:

```
import 'core-js/modules/es6.promise'
import 'whatwg-fetch'

import 'core-js/modules/es6.array.iterator.js'
import 'core-js/modules/es6.array.from.js'

import 'es6-map/implement'
```

**Comment by patrick-rodgers** [comment] 2018-09-13 23:59
Hi all, getting back from a cancelled vacation and just catching up. For folks needing IE11 I am curious what your organizations plan is to transition off of what is now a legacy browser? Are real folks impacted or are these left over tests that fail because you are still testing against IE11? This is now a 5 year old browser so it is hard to limit what we can do based on that. I do understand companies standardize and are slow to move for many reasons (almost always out of developers controls) so I do sympathize - but moving to Map has performance advantages as well as removes the extra code we had to support the custom dictionary.

**Comment by PooLP** [comment] 2018-09-14 06:51
Hi,

I have the same issue

@patrick-rodgers 
For SPFx use, the response is simple : https://support.office.com/en-us/article/which-browsers-work-with-office-online-ad1303e0-a318-47aa-b409-d3a5eb44e452

Microsoft keep compatibility with IE11, pnp.js must compatibility with this (even if it's a mistake for me that Microsoft still keeps this compatibility ^^).

**Comment by jusper-dk** [comment] 2018-09-14 10:16
> Are real folks impacted or are these left over tests that fail because you are still testing against IE11?

A lot of our customers continue using IE11 and we've got complaints from them :(

**Comment by patrick-rodgers** [comment] 2018-09-15 15:05
You both skipped the second question, what is their plan to migrate off IE11? The alternative is that you are saying "you can never use any features not supported by IE11, ever" is simply no good. We can document the polyfills as outlined above, happy to do that. But we aren't part of the PG and as such can make different decisions on supported browsers. We don't want to break folks and will document the polyfills - but again what are you doing to advocate with your customers that they need to upgrade?

**Comment by jpalo** [comment] 2018-09-17 10:47
My SPFx web part (fairly complex) wasn't displaying anything on IE11 (workbench or deployed) - and IE wasn't even showing any errors in console. Fortunately the following fixed it. 

As a side-comment, customers are using IE11, so there's nothing we can do, except make everything work on IE11 as well. It will take years for the larger companies to move on from IE11, mainly due to legacy corporate applications only working on IE...

```
import 'core-js/es6/array';
import 'es6-map/implement';
import "core-js/modules/es6.array.find";
```

**Comment by patrick-rodgers** [comment] 2018-09-19 13:51
Please have a look at #246 and let us know if that makes things more clear. Thanks!

I totally understand not having control of what browsers folks use, but we all need to be advocates of moving to newer technologies. When you say it will take years for folks to move, IE 11 is 5 years old at this point - that is ancient in terms of web development. I can say from experience there will be a day (no I don't have any special knowledge and this isn't an announcement) when IE 11 is no longer listed as supported for O365 and everything will drop support almost overnight. There is already pressure to do that coming from many sides. At that point companies will be forced to migrate, which is a painful process. The more we all can do to prepare folks and get things transitioned early actually benefits our customers and developers equally.

**Comment by PooLP** [comment] 2018-09-20 07:04
it's ok for me.

**Comment by gregwilton** [comment] 2018-09-20 12:47
That's very helpful. Being clear about what parts won't work should save people a lot of time.

I'd be quite happy if IE 11 support was officially dropped from O365. All of our O365 code will work in modern browsers and we encourage people to use Chrome but we're stuck in a position where we have to assume some people will be using IE 11 (particularly on sites used for collaborating with other companies).

**Closed** 2018-09-20 20:40 UTC
Labels: area: documentation, status: answered, type: question

**Comment by s-KaiNet** [comment] 2018-09-22 22:33
There is one case though, when you simply can't upgrade your browser. I encountered an issue with lack of polyfills when developing office add-in. When add-in is loaded in desktop client, desktop client uses IE 11 internally... yeah desktop application in 2018 uses ancient legacy 5-years old browser :)

Extremely difficult to debug, no errors were thrown. That was a joy :)

**Comment by mag210** [comment] 2018-09-25 14:10
> My SPFx web part (fairly complex) wasn't displaying anything on IE11 (workbench or deployed) - and IE wasn't even showing any errors in console. Fortunately the following fixed it.
> 
> As a side-comment, customers are using IE11, so there's nothing we can do, except make everything work on IE11 as well. It will take years for the larger companies to move on from IE11, mainly due to legacy corporate applications only working on IE...
> 
> ```
> import "core-js/es6/array";
> import "es6-map/implement";
> import "core-js/modules/es6.array.find";
> ```

Thanks, - this also resolved an issue I had with a new 1.6 SPFx webpart and using @pnp/sp. Agreed that IE11 needs to be catered for. As much as the browser is old hat, large organisations (particularly in the public sector) are going to use IE11 for years to come.

**Comment by wobba** [comment] 2018-10-12 07:47
@patrick-rodgers IE11 will be dropped by customers when Windows don't include it - that's the plan for many companies.

**Comment by paigeflourin** [comment] 2018-11-09 03:45
Hi!

how do i implement this with TS?  i get a warning

[ts]
Could not find a declaration file for module 'core-js/es6/array'. 'c:/Users/xxxx/node_modules/core-js/es6/array.js' implicitly has an 'any' type.
  Try `npm install @types/core-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'core-js/es6/array';`

i am also having issues with my webpart not showing up in IE 11 without errors in console. Also i have error with Edge when i trying to fetch a data then update the retrieved data. It only works in Chrome

HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax.
(Fetch)POST - https://xxxx/_api/web/lists/getByTitle('listname')/items(8)

**Comment by wobba** [comment] 2018-11-09 20:02
See https://pnp.github.io/pnpjs/documentation/polyfill/ as per the first comment.

**Comment by paigeflourin** [comment] 2018-11-29 06:08
hi @wobba ,

already added import "@pnp/polyfill-ie11"; but stll having out of Stack space error in IE11.
