### ISSUE TITLE
ClientSidePage.fromFile() throws Exception

### ISSUE THREAD

**Issue by umaknow-annie** [pnp/pnpjs#578] opened 2019-03-25 14:52 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.3.1 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Expected / Desired Behavior / Question

I am trying to get a modern page.

### Observed Behavior

I got this error in the console 

![image](https://user-images.githubusercontent.com/39703457/54929019-472e2b80-4eeb-11e9-9b32-f65267df68ad.png)

### Steps to Reproduce

```
const list = await sp.web.getList('/sites/my-site/SitePages');

const pageFile = list.items.getById(myPageId).file;

const page = ClientSidePage.fromFile(pageFile);
```

Thank you for your feedback!

**Comment by patrick-rodgers** [comment] 2019-03-25 17:50
This is maybe a duplicate of #568

**Comment by patrick-rodgers** [comment] 2019-03-25 17:59
I rewrote your code slightly, but I cannot reproduce the issue, note where I used await for the fromFile call. Does this solve the issue?

```TypeScript
const list = sp.web.getList(`/sites/dev/SitePages`);

const pageFile = list.items.getById(141).file;

const page = await ClientSidePage.fromFile(pageFile);
```

**Comment by umaknow-annie** [comment] 2019-03-25 19:08
I put the await and still got the exception in the console. I am trying to figure it out by putting console.log everywhere

**Comment by umaknow-annie** [comment] 2019-03-25 19:48
This is the file I pass to the function.

![image](https://user-images.githubusercontent.com/39703457/54949462-7fe2fa80-4f15-11e9-9712-a3d849febd11.png)

**Comment by koltyakov** [comment] 2019-03-25 19:55
Can you try providing web absolute URL strictly within Web constructor? `const web = new Web('WEB_ABS_URL')`? Will it make any difference?

How the code is delivered to SharePoint? SPFx? If so, is the [context provided](https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpsp-setup)?

**Comment by umaknow-annie** [comment] 2019-03-25 20:05
It's return the same issue. This is how I provided my context 

```
constructor(context: BaseComponentContext) {
    this.context = context;
    sp.setup({
      spfxContext: this.context
    });
  }
```

**Comment by koltyakov** [comment] 2019-03-25 20:14
Not sure this is correct so it's likely that spfxContext ends up with incorrect context with no web object and its URL properties, that's why the error.

**Comment by umaknow-annie** [comment] 2019-03-25 20:24
The first two lines works fine. When I console.log my pageFile I reseave this file and I saw that the `_url` proprety is there but when I passed this file to the fromFile function it return the error.
![image](https://user-images.githubusercontent.com/39703457/54951507-3648de80-4f1a-11e9-95e3-1684f5c2945f.png)

**Comment by patrick-rodgers** [comment] 2019-03-25 21:11
The first two lines don't actually do anything, it is the third line that actually makes calls to SharePoint so that is why the error appears there. I can't currently reproduce this issue. Does the file exist you are trying to open? Is your code doing anything else you haven't included here? Do you have permissions to the file? What other factors can you share? Are you able to make other calls successfully within this webpart as @koltyakov asked?

**Comment by umaknow-annie** [comment] 2019-03-26 17:11
I verify the file exist and I got all permissions. I try to get the item of the file by using ```await pageFile.getItem()``` and I got no error on that. When I console.log the result of the item I got my file. I also try to change for my other tenant and I got the same issue. My code do nothing else then getting the ClientSidePage. And both of the Standard Release and Targeted Release return this error.

**Comment by umaknow-annie** [comment] 2019-03-26 17:52
I also try to get the file like this : 
```const pageFile = sp.web.getFileByServerRelativeUrl('/sites/Go-devPagePush-src/SitePages/PagePushTest.aspx');```
But I got the same error.

**Comment by umaknow-annie** [comment] 2019-03-26 19:33
If it can help to resolve, this is the entire code I use 
```
export interface IMyClassProps {
    context: BaseComponentContext;
    pageId?: number;
}

export class MyClass extends React.Component<IMyClassProps> {
    private readonly _spService: SharePointService;

    constructor(props: IMyClassProps) {
        super(props);
        this._spService = new SharePointService(props.context);
    }

    public async componentWillMount(): Promise<void> {
        await this._init();
    }

    public async componentWillReceiveProps(nextProps: IMyClassProps): Promise<void> {
        if (this.props.pageId !== nextProps.pageId) {
            await this._init(nextProps);
        }
    }

    private async _init(props: IMyClassProps = this.props): Promise<void> {
        const { context } = props;

        try {
            const pageId = this.props.pageId || context.pageContext.listItem.id;
            console.log('this message should appear in console');
            const page = this._spService.getClientSidePageById(pageId);
            console.log('this message does not appear because an exception is throw before');
        } catch (e) { console.error(e); }
    }
}

export class SharePointService {
    public context: BaseComponentContext;

    constructor(context: BaseComponentContext) {
        this.context = context;
        sp.setup({
            spfxContext: this.context
        });
    }

    public async getClientSidePageById(id: number, web: Web = sp.web): Promise<ClientSidePage> {
        const list = await web.getList('/sites/my-site/SitePages');
        const pageFile = list.items.getById(id).file;
        return ClientSidePage.fromFile(pageFile);
    }
}
```

**Comment by patrick-rodgers** [comment] 2019-03-26 20:24
Have you tried setting the context in the oninit? Because you have dropped code into various life-cycle methods I am not sure things are firing in the order you think or have the properties ready. Here is the full content from the webpart I am using for testing this. Note I am setting the context in onInit and making the calls in render (which always runs after onInit). I still cannot reproduce this using the code below:

```TypeScript
import { Version } from '@microsoft/sp-core-library';
import { BaseClientSideWebPart } from '@microsoft/sp-webpart-base';
import {
  IPropertyPaneConfiguration,
  PropertyPaneTextField
} from '@microsoft/sp-property-pane';
import { escape } from '@microsoft/sp-lodash-subset';

import styles from './HelloWorldWebPart.module.scss';
import * as strings from 'HelloWorldWebPartStrings';

export interface IHelloWorldWebPartProps {
  description: string;
}

import { sp, ClientSidePage } from "@pnp/sp";

export default class HelloWorldWebPart extends BaseClientSideWebPart<IHelloWorldWebPartProps> {

  protected onInit(): Promise<void> {
    return super.onInit().then(_ => {
      sp.setup({ spfxContext: this.context });
    });
  }

  public async render(): Promise<void> {


    try {

      const list = sp.web.getList(`/sites/dev/SitePages`);

      const pageFile = list.items.getById(179).file;

      const page = await ClientSidePage.fromFile(pageFile);


    } catch (error) { console.error(error); }


    this.domElement.innerHTML = `Testing...`;
  }

  protected get dataVersion(): Version {
    return Version.parse('1.0');
  }

  protected getPropertyPaneConfiguration(): IPropertyPaneConfiguration {
    return {
      pages: [
        {
          header: {
            description: strings.PropertyPaneDescription
          },
          groups: [
            {
              groupName: strings.BasicGroupName,
              groupFields: [
                PropertyPaneTextField('description', {
                  label: strings.DescriptionFieldLabel
                })
              ]
            }
          ]
        }
      ]
    };
  }
}
```

**Comment by umaknow-annie** [comment] 2019-03-26 20:46
I just tried to set the context in the onInit and make the call in the render like you said but I still have the same error.

**Comment by patrick-rodgers** [comment] 2019-03-26 21:10
Can you create a repo we can clone that demonstrates this error? I am running your code in an SPFx webpart in the online workbench and I am able to load the page without errors so at this point I am not sure what is wrong so can't fix it. What version of SPFx are you using? (I am testing on 1.8 FWIW). The same code is working for me in node as well. I also ensured I was testing using 1.3.1 and was.

**Comment by umaknow-annie** [comment] 2019-03-29 20:23
I am still working on a new repo to give you the access as soon as possible (probably on monday).

**Comment by patrick-rodgers** [comment] 2019-04-10 14:14
Is this still an active issue or can we close it?

**Comment by umaknow-annie** [comment] 2019-04-10 14:17
I can't reproduice the error in another repo. I try to copy the exact same code that I used and deploy in the same tenant and try it with the same page but no error.

**Comment by patrick-rodgers** [comment] 2019-04-10 14:19
Ok, sounds like some weirdness or a typo somewhere. Maybe you were still using an older version of the library somehow. Will close this then as fixed. Thanks!

**Closed by patrick-rodgers** 2019-04-10 14:19 UTC
Labels: area: code, status: details needed, type: someting isn't working
