### ISSUE TITLE
Warnings using PnPJS V2 (^2.11.0) targeting SPFx 1.4.1 (SharePoint 2019)

### ISSUE THREAD

**Issue by SaadKnowIT** [pnp/pnpjs#1965] opened 2021-12-08 08:57 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version
Please specify what version of the library you are using: [PnPJS V2 (^2.11.0)]

Please specify what version(s) of SharePoint you are targeting: [SharePoint 2019 (On-Premises)]

Global installed npm packages:
![image](https://user-images.githubusercontent.com/60182595/145177067-a2f46a09-9f74-4b86-a576-cb06b0525e02.png)

Project specific installed npm packages:
![image](https://user-images.githubusercontent.com/60182595/145177262-9caa0831-a881-48ed-b27a-f4058f128d9f.png)

### Expected / Desired Behavior / Question
Be able to run PnPJs V2 with SPFx 1.4.1 on SharePoint 2019 (On-Premises) without warnings or errors.

### Observed Behavior
Need to use PnPJS V2 for my project to be able to use API:s for creating news ClientSide Pages. Started with PnPJs V1 but the API:s i need doesn't exist for V1.

Need to use this one:
"const page3 = await sp.web.addClientsidePage("mypage", "My Page Title", "Article", PromotedState.PromoteOnPublish);"
Documentation reference: [create-using-iwebaddclientsidepage](https://pnp.github.io/pnpjs/sp/clientside-pages/#create-using-iwebaddclientsidepage)

So i created a new project with "yo @microsoft/sharepoint" for "SharePoint 2019 (On-Premises)".
Then followed this guide to add PnPJs V2 to the project: [workaround-for-on-premises-spfx-typescript-version-sharepoint-2016-or-2019](https://pnp.github.io/pnpjs/SPFx-on-premises/#workaround-for-on-premises-spfx-typescript-version-sharepoint-2016-or-2019).

After the guide i tried to run "gulp serve --nobrowser" and gets a wall of these warnings:
![image](https://user-images.githubusercontent.com/60182595/145176622-fded8be4-7c7f-4d62-9fe1-7f205f39303b.png)

The API:s from the PnPJS V2 version is working fine but i should not get these warnings right or is this expected behaviour?

### Steps to Reproduce
1. Have same global installed packages as on my machine:
![image](https://user-images.githubusercontent.com/60182595/145177067-a2f46a09-9f74-4b86-a576-cb06b0525e02.png)
2. Created a new project with "yo @microsoft/sharepoint" for "SharePoint 2019 (On-Premises)"
3. Install PnPJS V2 by following this guide: [workaround-for-on-premises-spfx-typescript-version-sharepoint-2016-or-2019](https://pnp.github.io/pnpjs/SPFx-on-premises/#workaround-for-on-premises-spfx-typescript-version-sharepoint-2016-or-2019)
4. Use any PnPJS V2 API in the project. For example:
![image](https://user-images.githubusercontent.com/60182595/145178445-e3cbbd91-8e86-4156-820c-fd0f1fd987cf.png)
5. Save all files and Run "gulp serve --nobrowser".
6. Get a wall of warnings in the terminal.

**Comment by SaadKnowIT** [comment] 2021-12-13 08:26
Even tried the alternative in the same guide:
[alternative-using-npm-force-resolutions](https://pnp.github.io/pnpjs/SPFx-on-premises/#alternative-using-npm-force-resolutions)

Still getting the yellow warnings in the image above.

Project specific installed npm packages:
![image](https://user-images.githubusercontent.com/60182595/145776730-4cb1d039-0f1f-476e-98e8-a470e59cb3eb.png)

Anyone had similar problem and a solution for this?

@koltyakov and @juliemturner have you guys experienced this before?

**Comment by SaadKnowIT** [comment] 2021-12-13 11:17
Found the root cause of these warnings.

I tried an older version of PnPjs V2 (2.0.4) as the api i wanted to use was introduced in that version.
That worked as expected without any warnings. So there after i tried to upgrade to the latest patch version of 2.0.4 (used "~2.0.9" in package.json), that installed the 2.0.13 version of PnPJs V2. Tried to build with that version and the warnings came back.

So i figured that there must have happened a change in between the 2.0.4 and 2.0.13 that causes these warnings. So i tried every version in between and looked at the changelogs of each version and found this version: [2.0.10](https://github.com/pnp/pnpjs/blob/main/CHANGELOG.md#2010---2020-sept-10).
![image](https://user-images.githubusercontent.com/60182595/145802561-2585df12-939f-43bd-aaeb-259e500df468.png)

I am guessing that this change is causing the warnings i am having when i use a version above 2.0.9.

I even left a comment on the [pull request](https://github.com/pnp/pnpjs/pull/1371).

@patrick-rodgers what do you think? Is it possible to use an later version of PnPJs V2 then 2.0.9 with SPFx 1.4.1 and not get these warnings? If "Yes", how?

**Comment by juliemturner** [comment] 2021-12-13 12:35
@SaadKnowIT - I don't think including .map files in are the root cause of your issue, more probably it's the version of typescript that was used or some other package dependency that was changed for that version as we update packages and dependencies to keep up with the updates on a monthly basis. Version 1.4.1 of SPFx is effectively stalled in the past and I think you're going to have to stick with an older version of pnpjs to make it work.  That you got it to work with version 2.0.4 seems like the right answer.

**Comment by SaadKnowIT** [comment] 2021-12-13 13:31
@juliemturner - Ok, so there is no other way for the warnings to not show up when using a version above 2.0.9.

As i said before also. It works with latest version of PnPJs V2 but the only problem are these warnings.

What would you recommend?
- Use 2.0.9 and not have these warnings.
- Use the latest version of V2 and have these warnings but ignore them.

PS. Is it possible for you guys to update the documentation to include this information. That for SPFx 1.4.1 for SharePoint 2019 any version of the PnPJs V2 above 2.0.9 will cause these warnings to show up but the endpoints still work. If you don't want these warnings stick to PnPJs version 2.0.9.

**Comment by patrick-rodgers** [comment] 2022-02-03 19:52
This appears related to an [issue with source-map-loader](https://github.com/webpack-contrib/source-map-loader/issues/18) that was fixed in a later version not included with 1.4.1 of the spfx generator. You were correct it was triggered by the addition of our source map files, which were picked up by source-map-loader.

We accept PRs if you want to update the docs, but going to close this as non-library. Thanks!

**Closed by patrick-rodgers** 2022-02-03 19:52 UTC
Labels: status: answered, area: code, type: someting isn't working
