### ISSUE TITLE
loadClientsidePage doesn't work with single part app pages 

### ISSUE THREAD

**Issue by RafalUrbanski** [pnp/pnpjs#2525] opened 2023-01-06 10:02 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.10.0 ]

Please specify what version(s) of SharePoint you are targeting: [ Online ]

### Expected / Desired Behavior / Question
When executing sp.web.loadClientsidePage to get instance of single part app page, ClientsidePage object should be returned

### Observed Behavior
Exception is thrown when executing loadClientsidePage - Uncaught TypeError: Cannot set properties of undefined (setting 'sectionFactor'). 
Error source - types.js, method onColumnChange, first line of method

### Steps to Reproduce
1. Create a single part app page within the site
2. Import all necessary pacakges and initialize pnpjs
3. Execute:
await sp.web.loadClientsidePage("{single part app page url}")

**Comment by patrick-rodgers** [comment] 2023-01-06 15:06
Hi @RafalUrbanski - I am unable to reproduce this with the information provided. Can you share more details on the page you are trying to load, how it was created, or really anything that might help us debug this on your behalf? Thanks!

**Comment by RafalUrbanski** [comment] 2023-01-06 19:06
Hi, 
sure, please find detailed instruction below:
1. Download sample spfx full page app part:
https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnpjs-spsite-er-diagram
2. Open project in VS Code
3. Run 'npm install'
4. Run 'gulp bundle --ship'
5. Run 'gulp package-solution --ship'
6. Upload created package to the SharePoint app catalog
7. Install new app on the selected site collection (Site Contents -> New -> App)
8. Follow steps in https://github.com/pnp/sp-dev-fx-webparts/tree/main/samples/react-pnpjs-spsite-er-diagram#summary to add new app as a single app part page
9. When page is created, named and saved, please try to execute the following command:
await sp.web.loadClientsidePage("<newly created page url>") - pnpjs and related import are required

Hope this will help

**Comment by juliemturner** [comment] 2023-01-13 15:10
Ok, it's possible that the page structure has changed again.  As we discuss in the documentation about the [pages API](https://pnp.github.io/pnpjs/concepts/adv-clientside-pages/) the page structure can change at any point and that can break the ability for the api to work. A new official supported API is in the works and we will be looking into that.  In the meantime, we can look into this issue and see if it's easily fixed.

**Comment by RafalUrbanski** [comment] 2023-01-17 07:04
Thank you for the update, if you manage to find out if it can be easily fixed, please let me know:)

**Comment by bcameron1231** [comment] 2023-05-08 22:51
Hi, any chance you could confirm if this is still an issue with the latest version of Pnpjs? I am unable to reproduce this problem.

**Comment by RafalUrbanski** [comment] 2023-05-10 10:45
Hi, I just checked this with version 3.14 and exactly the same error is thrown.

**Comment by bcameron1231** [comment] 2023-05-12 00:40
> Hi, I just checked this with version 3.14 and exactly the same error is thrown.

Hmm ok. I can try and keep testing.

**Comment by patrick-rodgers** [comment] 2023-06-16 19:24
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2023-06-16 19:24 UTC
Labels: status: details needed, area: code, type: someting isn't working
