### ISSUE TITLE
errors loading client side web-parts in specific content scenarios

### ISSUE THREAD

**Issue by jonathanhotono** [pnp/pnpjs#422] opened 2018-12-14 08:38 UTC
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

Since `getLimitedWebPartManager.webparts.get()` returns empty on modern page, is there anyway to get webpart configuration json from a certain modern page? I can't seem to find the api for this.

**Comment by koltyakov** [comment] 2018-12-14 08:44
Hi @jonathanhotono,

Please check [docs section](https://pnp.github.io/pnpjs/sp/docs/client-side-pages/) regards this topic.

**Comment by jonathanhotono** [comment] 2018-12-14 10:18
@koltyakov Thanks
I'm getting this error when reading the page:
![image](https://user-images.githubusercontent.com/6864547/49997381-880dce80-ffe5-11e8-991e-c1ea339e23c4.png)
Inside clientside.ts
![image](https://user-images.githubusercontent.com/6864547/49997439-b2f82280-ffe5-11e8-908c-bd834a4a8e62.png)
Request seems fine?
![image](https://user-images.githubusercontent.com/6864547/49997508-dae78600-ffe5-11e8-8816-9c13ded04860.png)

**Comment by patrick-rodgers** [comment] 2018-12-17 16:49
This is a duplicate of another issue we just got. This will be resolved in the next release. How things were stored internally changed slightly and our parsing got broken. This should currently be resolved in the latest beta, v1.2.8-0, so you can give that a try and let us know. Thanks!

**Comment by jonathanhotono** [comment] 2018-12-19 06:51
@patrick-rodgers thanks I've tested it and getting another issue.
![image](https://user-images.githubusercontent.com/6864547/50203606-2f0fb300-03b6-11e9-8514-cfc476d8372b.png)
Technically I updated the code slightly to something like:
```
import { 
    Web,
    ClientSidePage,
} from "@pnp/sp";

const web = new Web(SOME_URL);
const page = await ClientSidePage.fromFile(web.getFileByServerRelativeUrl("/sites/dev/SitePages/ExistingFile.aspx"));
```
Find the canvas content here:
https://gist.github.com/jonathanhotono/a122073bd99998a8c1a1cb1a8c9715a4

**Comment by patrick-rodgers** [comment] 2018-12-19 16:33
Ok, will have a look. This is the danger of doing all the brute force regex manipulation is that we can't anticipate all of the edge cases. Thanks for providing the content that is breaking things, that makes it much easier to diagnose.

**Comment by patrick-rodgers** [comment] 2018-12-20 18:22
@jonathanhotono - on the sample you posted above. I have made updates to handle the "*" and "$" chars encoding. There is however another issue with what you provided. If you look you can see that ""Policy Document""(&quot;&quot;Policy Document&quot;&quot;) and a two other values are double quoted, so I get the error:

`Message: Unexpected token P in JSON at position 1528 Data: {}`

There isn't a way to handle this because double quotes could be valid, meaning I can't just drop one of them. So my fix does take care of the issue you reported. Once I get it merged I'll close this issue. If you find other problems please open a new issue. Thanks!

**Closed** 2018-12-20 19:08 UTC
Labels: area: code, status: investigate, type: bug
