### ISSUE TITLE
Create page from another page with empty title

### ISSUE THREAD

**Issue by thenail** [pnp/pnpjs#1166] opened 2020-04-20 07:27 UTC
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.11 ]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Observed Behavior
I trying to create page from another page (template) using empty title on the new page, to replicate the default behavior of forcing the user to set the title before saving the page.
In the savepage api request I can see that the empty title is used but its not updating the title on the list item only the title in the layoutpart (title inside the page).
The workaround is to update the list item afterwards with empty title, but that requires additional api requests.
Are there any additional definitions of empty than empty string or undefined that could be used here?, I have also tried with a space but that causes a space in the page title that the users needs to remove.

**Comment by patrick-rodgers** [comment] 2020-04-20 17:21
The API works on filenames for the pages, and the forced blank title isn't something that is supported after a page is published. Meaning there isn't a way by design to leave a page with a blank title. It looks like you have found a workaround that meets your needs - so I would recommend continuing with that. Thanks!

**Comment by thenail** [comment] 2020-04-20 17:49
Maybe I was a little unclear, I havn't done any publishing of the page. 
I'm trying to reproduce the standard behavior of creating a page from template and then forcing the user to assign a title to the page. The createPage function (in pnpjs) assigning pagename to title (and that it updating title in list item and layoutpart) doing a save without publishing and then assigning title to title, but if you have empty title only the title in the layoutpart is being assigned empty, the title in the list item is still pagename, but it changes for all other values. This ends up with a page without a title that can be published.

**Comment by patrick-rodgers** [comment] 2020-05-04 16:23
I don't think this can work in the way you want via the available API. The page title is required as it becomes the page url. When you first create a page in the UI the page url is a random string. What you describe isn't possible through the UI, meaning the API wasn't designed to support it. The page is never meant to exist without a title - and the API creates a page using the title you give it - and it can't be blank, hence the juggling we do to let folks set the page name and title as distinct values. We don't in our code set the list item directly so when or how that is set is outside our control.

If you are trying to model the Copy of this page functionality under new it drops you to newpage.aspx - so the page doesn't really exist at all until you add a title and save.

This feels like a special requirement you have, my suggestion would be to use whatever workaround you have and perhaps [add it as an extension](https://pnp.github.io/pnpjs/odata/extensions/) method so it flows inline with your code.

**Comment by thenail** [comment] 2020-05-05 10:38
Ok, I still however does not 100% agree that its a special case and replicating the UI is exactly what I'm trying to do here. If you create a page in pnp js the user needs to remove the title (in the UI) from the page and enter the title that they want to use. If you create a page from within SharePoint the page title is blank (and the url is a random string) so the user does not need to remove the title first they could just enter the title that they want, when they save the url of the page is changed from the random string to what they entered in the title field.

This is how SavePage looks like when SharePoint doing new page:
```
{
    "__metadata":{
       "type":"SP.Publishing.SitePage"
    },
    "LayoutWebpartsContent":"[{\"id\":\"cbe7b0a9-3504-44dd-a3a3-0e5cacd07788\",\"instanceId\":\"cbe7b0a9-3504-44dd-a3a3-0e5cacd07788\",\"title\":\"\\r\\n      Title area\\r\\n    \",\"description\":\"\\r\\n      Title area description\\r\\n    \",\"serverProcessedContent\":{\"htmlStrings\":{},\"searchablePlainTexts\":{},\"imageSources\":{\"imageSource\":\"/_LAYOUTS/IMAGES/SLEEKTEMPLATEIMAGETILE.JPG\"},\"links\":{},\"customMetadata\":{\"imageSource\":{}}},\"dataVersion\":\"1.4\",\"properties\":{\"imageSourceType\":2,\"title\":\"\",\"textAlignment\":\"Left\",\"showPublishDate\":false,\"authors\":[{\"id\":\"i:0#.f|membership|user@contoso.onmicrosoft.com\",\"upn\":\"User@contoso.onmicrosoft.com\",\"email\":\"User@contoso.onmicrosoft.com\",\"name\":\"User Username\",\"role\":\"\"}],\"showTopicHeader\":false,\"authorByline\":[\"i:0#.f|membership|user@contoso.onmicrosoft.com\"],\"layoutType\":\"CutInShape\",\"titlePlaceholder\":\"Name your news post\",\"topicHeader\":\"\"}}]",
    "AuthorByline":[
       "i:0#.f|membership|user@contoso.onmicrosoft.com"
    ],
    "TopicHeader":"",
    "BannerImageUrl":"/_layouts/15/images/sitepagethumbnail.png",
    "CanvasContent1":"[{\"controlType\":4,\"id\":\"1212fc8d-dd6b-408a-8d5d-9f1cc787efbb\",\"position\":{\"controlIndex\":2,\"sectionIndex\":1,\"sectionFactor\":12,\"zoneIndex\":1,\"layoutIndex\":1},\"addedFromPersistedData\":true,\"innerHTML\":\"\"},{\"controlType\":0,\"pageSettingsSlice\":{\"isDefaultDescription\":true,\"isDefaultThumbnail\":true}}]"
 }
```

This is how SavePage looks like when pnp js doing create page (doing random string title for now):
```
{
    "__metadata":{
       "type":"SP.Publishing.SitePage"
    },
    "AuthorByline":[
 
    ],
    "BannerImageUrl":null,
    "CanvasContent1":"[{\"controlType\":0,\"pageSettingsSlice\":{\"isDefaultDescription\":true,\"isDefaultThumbnail\":true}}]",
    "LayoutWebpartsContent":"[{\"dataVersion\":\"1.4\",\"description\":\"Title Region Description\",\"id\":\"cbe7b0a9-3504-44dd-a3a3-0e5cacd07788\",\"instanceId\":\"cbe7b0a9-3504-44dd-a3a3-0e5cacd07788\",\"properties\":{\"authors\":[],\"layoutType\":\"FullWidthImage\",\"showPublishDate\":false,\"showTopicHeader\":false,\"textAlignment\":\"Left\",\"title\":\"e8bdb30a\",\"topicHeader\":\"\"},\"serverProcessedContent\":{\"htmlStrings\":{},\"searchablePlainTexts\":{},\"imageSources\":{},\"links\":{}},\"title\":\"Title area\"}]",
    "Title":"e8bdb30a",
    "TopicHeader":""
 }
```

Doesn't seems like title is a required property either in CanvasContent1 or in the object itself.

**Comment by juliemturner** [comment] 2020-06-11 22:09
I have spent a few hours seeing if there is any way we can make this work and have been unable to do so.  What, although I agree, seems simple is unfortunately not.  If you leave the title blank when you create the page then the page will get created but not with the name you specified, instead, it gets assigned a random text string. 

What is maybe not so obvious is that there is no formally supported page API for modern pages so we too are reverse engineering this functionality by seeing what the first party UI is doing.  It seems based on the thread you have a workaround, although not ideal does at least solve the problem. At this point, we're going to close this issue. If you can find a way to solve it and would like to submit a PR we'd be more than happy to review it and possibly merge it into the library.

We really appreciate your submitting the idea, and we're sorry we're not able to accommodate you at this time.

**Closed by juliemturner** 2020-06-11 22:09 UTC
Labels: area: code, status: answered, type: question
