### ISSUE TITLE
Issue when saving IClientsidePage with new banner section / page head functionality

### ISSUE THREAD

**Issue by Bobinho4711** [pnp/pnpjs#3116] opened 2024-08-13 21:43 UTC
### Major Version

3.x

### Minor Version Number

3.17.0

### Target environment

All

### Additional environment details

Using it in an Azure function, but I assume all environments are affected.

### Expected or Desired Behavior

Simplified case:
I want to create a new Page via the SharePoint frontend and publish it.
Afterwards I want to fetch it via my app as an IClientSidepage object and save it.
I would expect that the page looks like it looked before the save.

### Observed Behavior

Microsoft recently introducted this Banner Section, which is also used by Microsoft to replace the Page Header as we knew it.
Once you save the page via PNP, PNP add the "old" header in top, so that it is displayed twice:

Original, created via frontend:
![image](https://github.com/user-attachments/assets/202e3521-ee28-4e60-8600-87697cc1b4ec)

Afterwards, just after save:
![image](https://github.com/user-attachments/assets/d9b954d7-f2f2-4084-85e4-aee36e960e47)

This happens independently of the banner type.
![image](https://github.com/user-attachments/assets/bee7f2ae-4528-4417-af67-84697e51cb64)

### Steps to Reproduce

Simplified case:
Im trying to get an IClientSidepage Object via

`sp.web.loadClientsidePage("some ur");`

and save it afterwards, without any changes:

`page.save(true);`

Afterwards page is broken as shown above.

**Comment by bcameron1231** [comment] 2024-08-13 22:00
Duplicate of #3095 and #3096

**Closed by bcameron1231** 2024-08-13 22:00 UTC
Labels: status: investigate, type: someting isn't working
