### ISSUE TITLE
Unit testing typescript SPFx web part (react) that uses pnpjs

### ISSUE THREAD

**Issue by nbelyh** [pnp/pnpjs#1425] opened 2020-10-31 19:18 UTC
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.11]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Question

How do you unit test SPFx web part, written in typescript (react), that uses pnpjs to communicate with SharePoint? 
Is there a stock configuration or framework?

I have already tried these tutorials they all don't seem to work with current version SPFx if you use both typescript and pnpjs:
https://www.eliostruyf.com/sharepoint-framework-unit-tests-with-jest/
https://blog.velingeorgiev.com/unit-test-your-sharepoint-framework-solution-with-jest/
https://www.c-sharpcorner.com/article/spfx-unit-test-with-jest-and-enzyme/
https://github.com/sebastianrogers/pnpjs-jest
https://github.com/estruyf/spfx-testing-jest

Related issue where you can find a typical example of the problems I'm currently facing:
https://github.com/pnp/pnpjs/issues/1058

```
    XXXX/node_modules/@pnp/sp/fields/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import "./web";

    > 2 | import { FieldTypes } from "@pnp/sp/fields";
        | ^
    SyntaxError: Unexpected string
```

The issue seems to be that: jest does not support modules natively (it supports them in the very last release, but that's for node 13, for which other things fail). So now transforms are used, and you should be able to overcome that with babel plugin, that can load the modules and remove all those "import" and "export" stuff. Now, babel does not play well with typescript so in jest there is another plugin ts-jest that does typescript, as of my current understanding. But installing that creates version incompatibilities and erros like `cwd is not a function`...

So, well, the whole thing looks like a swarm of snakes 😄 

Could someone share a configuration that supports unit testing, for a SPFx web part 1.11 written in typescript, that uses pnpjs to communicate with SharePoint?  I mean, I'm flexible and if JEST just does not want to work, screw it, I could use whatever 😄 
Maybe I'm missing something simple? Or is nobody unit testing SPFx web parts?

Please note that if you don't use pnp (do not import it), the tutorials above work. So I believe this issue **is** related to PNP, and hopefully won't be closed like the referenced one... I'm really interested in an example where you **do** import pnp, and use typescript (react) to build your web part.

So far my best shot was this setup:
- jest
- ts-jest (because the project is in typescript)
- babel-jest (because pnp uses modules inside compiled .js files in node_modules)
- identity-obj-proxy (to overcome the issue with scss modules)

Still no luck though. Any recommendation is appreciated 😄

**Comment by nbelyh** [comment] 2020-11-01 20:49
Found a somewhat related user voice topic... probably this should go to the same bucket:
https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/34073197-web-parts-allow-them-to-be-unit-testable

**Comment by patrick-rodgers** [comment] 2020-11-03 13:07
@andrewconnell just released a [new blog post about setting up jest](https://www.andrewconnell.com/blog/enable-jest-testing-of-sharepoint-framework-projects-in-one-simple-step/) that might help you out.

As discussed in the other thread, the issue is with node and jest's ability to use es modules, which is what we use to enable the selective imports. We do publish [commonjs modules](https://pnp.github.io/pnpjs/nodejs-support/#commonjs-libraries) for use specifically in node environments. But that's not what you want in the browser. We tried to package it all together, but that caused a lot of issues for folks.

Beyond that we can't offer much support, perhaps someone from the community has additional ideas as well. I get you don't want this issue closed - but the issue isn't with PnPjs as much as it is with the module support.

**Comment by nbelyh** [comment] 2020-11-03 13:19
Thank you @patrick-rodgers 

With the blog post unfortunately it's the same problem, here is the reated issue:  
https://github.com/pnp/pnpjs/issues/1425

Seems that I have moderate progress with babel though, just to share here maybe for others who may run into the same thing..
Had to add:

- babel-plugin-transform-es2015-modules-commonjs (to fix pnpjs using ES modules in compiled code). Also had to add pnp to "transformIgnorePatterns" so that babel does process it.
- babel-plugin-transform-amd-to-commonjs (to fix en-us.js that is using AMD for babel - what a mess)

project json:
```
    "babel-core": "^6.26.3",
    "babel-jest": "^25.0.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
    "babel-plugin-transform-amd-to-commonjs": "^1.4.0",
    "jest": "^25.0.0",
    "ts-jest": "^25.0.0",
```
jest config:
```
  "jest": {
    "transform": {
      "^.+\\.(ts|tsx)$": "ts-jest",
      "^.+\\.js$": "babel-jest"
    },
    "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(ts?|tsx?)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ],
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(@pnp)/)"
    ],
```
babel config:
```
{
  "presets": [[ "@babel/preset-env", { "modules": false, "targets": { "node": "current" }}]],
  "plugins": ["transform-es2015-modules-commonjs", "transform-amd-to-commonjs"]
}
```
tsconfig:
```
   "module": "commonjs",
   "types": [
      .......
      "jest"
   ],
```

**Comment by patrick-rodgers** [comment] 2020-11-03 13:30
There are [some more ideas in this thread](https://github.com/Voitanos/jest-preset-spfx-react16/issues/7#issuecomment-552863944). One of the big issue in play is that SPFx is never intended to run in node.

I will say as you work on this if there is something we can do within the library to assist (that makes sense) we are open to it.

**Comment by nbelyh** [comment] 2020-11-03 13:31
`babel`  + `transform-amd-to-commonjs` plugin seems to solve the issue with the strings quite nicely.

**Comment by andrewconnell** [comment] 2020-11-03 14:22
@patrick-rodgers said:
> One of the big issue in play is that SPFx is never intended to run in node.

Yup... that's the crux of the problem. Microsoft made it incredibly hard to test SPFx projects because all the SPFx libraries expect to run within a SharePoint context & with the SPFx runtime present. It's why I recommend you never include the SPFx components in your tests, rather use them as the glue between your app & SharePoint, then you only focus on testing your app.

I do have it on my backlog to update my Jest presets for the current version dependency matrix... no ETA ATM, but it's planned work in the near future.

**Comment by nbelyh** [comment] 2020-11-03 14:43
@andrewconnell I don't actulaly include SPFx components in tests, but the thing is - as soon as you have in the **main** module (such as a service) `import { something} from @sp/@pnp/@microsoft` it can easily becomes an issue in unit tests (jest) - invalid keyword 'import', 'export', 'define', take your pick 😄

**Comment by andrewconnell** [comment] 2020-11-03 15:00
Gotcha... yeah, lots of people have hit this as as the thread @patrick-rodgers & you mentioned above, there are a few different approaches to resolving it. Sadly, one size doesn't fit all... just not a fun thing to deal with :-/

**Comment by wizneeraj** [comment] 2020-11-10 23:18
@nbelyh - Please let me know if you were able to make jest work with PnPJs, i am having a similar issue and need some guidance on this regard.

**Comment by nbelyh** [comment] 2020-11-11 00:56
@wizneeraj @andrewconnell 
Like described below, created a simple hello-world repository (that uses babel with the mentioned plugins for unit testing):
https://github.com/nbelyh/spfx-unit-testing-pnpjs

config: 
- SPFx 1.11.0 (latest), 
- react 16, 
- typescript 3.9
- can test both services and components (jest 26 + enzyme)
- does not break on `import { sp } from @pnp/sp`
- does not break on "define" in string resources (on `import * as strings from 'HelloWorldWebPartStrings'`)

To run unit test:
```
npm install
npm test
```

The modifications to the original projects are mostly in the latest commit:
https://github.com/nbelyh/spfx-unit-testing-pnpjs/commit/f1698ba6fe6492284588a8e1218ebe220c60c2b8

**Comment by patrick-rodgers** [comment] 2020-11-16 16:20
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

Would also invite someone from this thread to add an explanation to the docs to make the information easier to find.

**Closed by patrick-rodgers** 2020-11-16 16:20 UTC
Labels: area: non-library, status: by design, type: someting isn't working
