### ISSUE TITLE
Batching with 

### ISSUE THREAD

**Issue by Krugerro** [pnp/pnpjs#2579] opened 2023-02-20 12:59 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using:  3.12.1

Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question
Fields with properties in batch are added to list without throwing error `Could not properly parse responses to match requests in batch.`

### Observed Behavior
Error is thrown on `catch` of batching which stops `then` actions. Beside error all fields are added but not with all properties. 

### Steps to Reproduce
Use batching for adding new field to a list with additional properties. Example code below.
 
```TS
createBatchToCreateFields(listResult, fields)
      .then((_) => {
                 // do sth here
          })
      .catch((e) => console.log("batch error", e));

const createBatchToCreateFields = async (
  list: IList,
  fields: newListFields[]
): Promise<void> => {
  const [batchedListBehavior, execute] = createBatch(list);
  const res: IFieldAddResult[] = [];

  list.using(batchedListBehavior);

  fields.forEach(({ title, fieldTypeKind, properties }) => {
    let newAdd;
    const propLoc = properties as IFieldCreationProperties & AddChoiceProps;
    switch (true) {
      case fieldTypeKind === FieldTypes.DateTime:
        newAdd = list.fields.addDateTime(title, properties);
        break;
      case fieldTypeKind === FieldTypes.File:
        newAdd = list.fields.addImageField(title, properties);
        break;
      case fieldTypeKind === FieldTypes.Choice:
        newAdd = list.fields.addChoice(title, propLoc);
        break;
      default:
        newAdd = list.fields.add(title, fieldTypeKind, properties);
    }
    newAdd
      .then((r) => {
        res.push(r);
      })
      .catch((e) => res.push(e));
  });

  return execute();
};

const fields: newListFields[] = [
  {
    title: "DateFrom",
    fieldTypeKind: FieldTypes.DateTime,
    properties: {
      DisplayFormat: DateTimeFieldFormatType.DateOnly,
      Required: true,
    },
  ]
```

### Submission Guidelines
In batching.js I can see that adding field is one request and changing parameters (required and date format) is another request this compared to one response.

Thank you for your feedback!

**Comment by juliemturner** [comment] 2023-02-20 14:54
Can you try rewriting this with more detail:
>In batching.js I can see that adding field is one request and changing parameters (required and date format) is another request this compared to one response.

I am trying to understand what your issue is but it's not really clear.

**Comment by Krugerro** [comment] 2023-02-21 07:23
Sure. In console I made pause on a condition which if true throws above error. Below is snippet pointing at exact line. Running above code gives error as there are two requests and only one response. 
![image](https://user-images.githubusercontent.com/51735003/220275545-96a98a7a-f7d4-4617-9946-93aa5492b945.png)

**Comment by patrick-rodgers** [comment] 2023-02-21 14:45
I haven't had a chance to test this, but `.forEach` doesn't work with async you might try rewriting this using a for loop.

**Comment by Krugerro** [comment] 2023-02-22 08:20
I played more with code and spotted new aspects of issue. I think main problem is not in batching itself but in two batching methods done one after another about which I did not mentioned above. After adding fields to list I fired method to add just created fields to default view (maybe it can be done during fields creation?). And this second method causes an error (when fired separately code went without errors). To sum up consider simpler situation which for me gives error:
```TS
const list = await sp.web.lists.getByTitle(listName);

await createBatchToCreateFields(list, fields);

await createBatchToCreateFields(listResult, fields2);` 
```
where as example:
```TS
export const fields2: newListFields[] = [
  {
    title: "DateNew",
    fieldTypeKind: FieldTypes.DateTime,
    properties: {
      DisplayFormat: DateTimeFieldFormatType.DateOnly,
      Required: true,
    },
  },
];

export const fields: newListFields[] = [
  {
    title: "DateFrom",
    fieldTypeKind: FieldTypes.DateTime,
    properties: {
      DisplayFormat: DateTimeFieldFormatType.DateOnly,
      Required: true,
    },
  },
```
I switch to for loop as I suggested earlier.

**Comment by patrick-rodgers** [comment] 2023-02-22 12:40
If you take the batching code out of your methods and simply run it, does it work as expected? If so the issue is likely how you are wrapping things.

In the code you share above you don't indicate what `listResult` is, so its not really helpful in undestanding.

**Comment by Krugerro** [comment] 2023-02-22 12:58
Sorry for errors in code I changed previous comment. 
_If you take the batching code out of your methods and simply run it, does it work as expected?_
Yes, when run separately, so only one  only one await createBatchToCreateFields(list, fields)  all goes smoothly.

**Comment by patrick-rodgers** [comment] 2023-02-22 16:18
If you recreate the list object does it work? Reusing the list in the manner you are would add a second batch behavior to the list if you are reusing that object which might lead to what you are seeing. It wouldn't work exactly right with two batch behaviors present.

**Comment by Krugerro** [comment] 2023-02-23 10:25
OK, that was a trick. If I requested once again for a list after fields creation and provide it to second batch method error did not appear and everything went smoothly.  Thanks for your guidance. So working code would be: 
```TS
const list = await sp.web.lists.getByTitle(listName);

await createBatchToCreateFields(list, fields);

const list2 = await sp.web.lists.getByTitle(listName);

await createBatchToCreateFields(list2, fields2);
```

**Comment by patrick-rodgers** [comment] 2023-02-23 13:11
Awesome, glad it worked. You may also be able to do something like the below if you want to keep your pattern.

```
import { List } from "@pnp/sp/lists";

const createBatchToCreateFields = async (list: IList, ....) {

    const clonedList = List(list);


    clonedList.using(#add batching to this list#)

    //...
}
```

Glad things are working for you now, will go ahead and close this issue. Thanks!

**Closed by patrick-rodgers** 2023-02-23 13:11 UTC
Labels: status: details needed, area: code, type: someting isn't working
