### ISSUE TITLE
Error fetching page details

### ISSUE THREAD

**Issue by raymondlittle100** [pnp/pnpjs#125] opened 2018-06-11 14:59 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.1.0        ]

### Expected / Desired Behavior / Question
Able to load page details by page Url

### Observed Behavior
Getting JSON token errors, see below

"SyntaxError: Unexpected token . in JSON at position 343"
"stack:"SyntaxError: Unexpected token . in JSON at position 343\n    at JSON.parse (<anonymous>)\n    at Function.ClientSidePage.escapedStringToJson (https://localhost:4321/dist/pn-p-web-part.js:5897:21)\n    at ClientSideWebpart.fromHtml (https://localhost:4321/dist/pn-p-web-part.js:6385:42)\n    at https://localhost:4321/dist/pn-p-web-part.js:5951:29\n    at getBoundedDivMarkup (https://localhost:4321/dist/pn-p-web-part.js:5780:29)\n    at ClientSidePage.fromHtml (https://localhost:4321/dist/pn-p-web-part.js:5935:9)\n    at https://localhost:4321/dist/pn-p-web-part.js:5972:19""

### Steps to Reproduce
Created a basic web part for testing which setups PnP context and passes this to react component

public onInit(): Promise<void> {

    return super.onInit().then(_ => {
  
      // other init code may be present
  
      sp.setup({
        spfxContext: this.context
      });
    });
  }

In react component try and fetch a page. If there is any content on the page like text web part of links web part or a custom web part it errors. If the blank page it works ok.

 const page = await ClientSidePage.fromFile(
        this.props.spRest.web.getFileByServerRelativeUrl(this.props.pageUrl));

**Comment by patrick-rodgers** [comment] 2018-06-11 15:12
Does this work correctly outside of the react application? I am not able to duplicate making the plain call.

**Comment by raymondlittle100** [comment] 2018-06-11 15:37
I never got this in 1.04 or 1.0.5 it only seems to be 1.1.1

Tried adding this directly in the web part ts file and got same issue

![image](https://user-images.githubusercontent.com/23637375/41241703-8d78b82c-6d95-11e8-9646-8a47f2b3c8fe.png)

SyntaxError: Unexpected token [ in JSON at position 107
    at JSON.parse (<anonymous>)
    at Function.ClientSidePage.escapedStringToJson (https://localhost:4321/dist/pn-p-web-part.js:6101:21)
    at ClientSideWebpart.fromHtml (https://localhost:4321/dist/pn-p-web-part.js:6589:42)
    at https://localhost:4321/dist/pn-p-web-part.js:6155:29
    at getBoundedDivMarkup (https://localhost:4321/dist/pn-p-web-part.js:5984:29)
    at ClientSidePage.fromHtml (https://localhost:4321/dist/pn-p-web-part.js:6139:9)
    at https://localhost:4321/dist/pn-p-web-part.js:6176:19

**Comment by patrick-rodgers** [comment] 2018-06-11 17:15
So far as I know none of our code has changed between those releases that would affect this scenario. Will try and duplicate.

**Comment by raymondlittle100** [comment] 2018-06-11 19:12
Happy to share any more details you need

**Comment by patrick-rodgers** [comment] 2018-06-12 14:49
I can't duplicate this exactly - what all is on the page? I did find an issue related to text web parts sticking in an extra </div>due to how we were parsing this, I think related but not solving your other issue #126.

**Comment by patrick-rodgers** [comment] 2018-06-12 15:09
Can you capture the actual content the JSON parser is failing on?

**Comment by raymondlittle100** [comment] 2018-06-12 19:52
I'll get a sample of the page, it mainly seemed to be when any content, as in any web part, was on the page. Blank pages were fine. What would be the best way to get the JSON? Look at maintenance mode?

**Comment by raymondlittle100** [comment] 2018-06-12 20:59
Tried the following but it gives me the error below when trying to getJSON

**_Sample code_**
      console.log('test 1');
      const file = await this.props.spRest.web.getFileByServerRelativeUrl(this.props.pageUrl);
      console.log('test 2');
      const fileJson = await file.getJSON();
      console.log('test 3');
      const page = await ClientSidePage.fromFile(file);  

**_Result_**
SyntaxError: Unexpected token < in JSON at position 0

**_Screenshot of web parts__**
![image](https://user-images.githubusercontent.com/23637375/41316904-8a482998-6e8b-11e8-950e-03b78840d4cf.png)

**_Screenshot of maintenancemode_**
![image](https://user-images.githubusercontent.com/23637375/41316951-aab5b18c-6e8b-11e8-85e0-cdff569ef36a.png)


In this example I have 

- Custom web part

- Link web part

- Image web part

- Text web part

**Comment by patrick-rodgers** [comment] 2018-06-12 21:17
Oh - I think you don't need the getJSON step...the file won't be in JSON, so that might be the source of your error. Can you try passing the file object directly to the fromFile method, [as shown here](https://pnp.github.io/pnpjs/sp/client-side-pages.html#load-client-side-page).

```TypeScript
import { 
    sp,
    ClientSidePage,
} from "@pnp/sp";

// the fromFile just needs the file instance, ClientSidePage will handle all the loading from there.
const page = await ClientSidePage.fromFile(sp.web.getFileByServerRelativeUrl("/sites/dev/SitePages/ExistingFile.aspx"));
```

**Comment by harshdamaniahd** [comment] 2018-06-13 09:52
i downgraded @pnp/sp to   "@pnp/sp": "^1.0.4"
Now it works

**Comment by patrick-rodgers** [comment] 2018-06-13 14:14
Are you both only upgrading a single package? All packages need to be upgraded to latest version for things to work. You would have gotten errors in the command line about missing peer dependencies.

**Comment by raymondlittle100** [comment] 2018-06-13 14:22
No I have updated all 

![image](https://user-images.githubusercontent.com/23637375/41357232-978e3dbc-6f1d-11e8-9623-75188ce680b0.png)

**Comment by harshdamaniahd** [comment] 2018-06-13 14:24
@raymondlittle100  after upgrading all packages to 1.1.1 and still it doesn't work right ?

**Comment by patrick-rodgers** [comment] 2018-06-13 14:29
@raymondlittle100  or @harshdamaniahd can either of you share the content of the JSON that is failing to parse? Or share the code around the call? Without seeing the actual data I can only guess what might be happening.

**Comment by raymondlittle100** [comment] 2018-06-13 14:31
@patrick-rodgers  happy to help if you let me know the best way to get the JSON

**Comment by patrick-rodgers** [comment] 2018-06-13 18:12
You can set a breakpoint in that method where it throws the error and get the value then. My problem currently is that knowing there is a JSON parsing error isn't a thing I can fix since I can't recreate whatever is happening. The other option is to provide steps that will recreate the issue. Something like add this web part with these settings, add this web part with these settings, add a text web part with exactly this content, etc.

Or you can wait until Friday when we publish the beta that will have the fix for the text content parsing from #126. Perhaps that will help here and these pages have gotten corrupted.

**Comment by harshdamaniahd** [comment] 2018-06-14 08:12
@patrick-rodgers the JSON string is always empty
and the other point is when we use any other webpart except text  editor there are no sections returned.

This is all i can provide
![image](https://user-images.githubusercontent.com/11780473/41399535-32fb348e-6fd8-11e8-8c9a-3a5a4f450449.png)


To Reproduce the problem:

1. Create a Modern Page in Site Pages.
2.Add a text editor webpart with some text.
3.Add an image webpart to the page.
4.Now create a SPFX webpart and add the below line of code 

`const page= await ClientSidePage.fromFile(this.props.spRest.web.getFileByServerRelativeUrl(`/Sites/common/SitePages/Test.aspx`));
`
The above code breaks and gives JSON error.

**Comment by raymondlittle100** [comment] 2018-06-14 08:15
Page with hero web part gets error  "SyntaxError: Unexpected token [ in JSON at position 276" with JSON, i think,



&#123;&quot;controlType&quot;&#58;3,&quot;displayMode&quot;&#58;2,&quot;id&quot;&#58;&quot;66d4cd07-0391-4650-81db-cf04cde17fc0&quot;,&quot;position&quot;&#58;&#123;&quot;zoneIndex&quot;&#58;1,&quot;sectionIndex&quot;&#58;1,&quot;controlIndex&quot;&#58;1&#125;,&quot;webPartId&quot;&#58;&quot;c4bd7b2f-7b6e-4599-8485-16504575f590&quot;&#125;
clientsidepages.ts:267
&#123;&quot;id&quot;&#58;&quot;c4bd7b2f-7b6e-4599-8485-16504575f590&quot;,&quot;instanceId&quot;&#58;&quot;66d4cd07-0391-4650-81db-cf04cde17fc0&quot;,&quot;title&quot;&#58;&quot;Hero&quot;,&quot;description&quot;&#58;&quot;Prominently display up to 5 pieces of content in a highly visual layout&quot;,&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&quot;content\[0\]\.title&quot;&#58;&quot;&quot;,&quot;content\[1\]\.title&quot;&#58;&quot;&quot;,&quot;content\[2\]\.title&quot;&#58;&quot;&quot;,&quot;content\[3\]\.title&quot;&#58;&quot;&quot;,&quot;content\[4\]\.title&quot;&#58;&quot;&quot;,&quot;content\[0\]\.alternateText&quot;&#58;&quot;&quot;,&quot;content\[1\]\.alternateText&quot;&#58;&quot;&quot;,&quot;content\[2\]\.alternateText&quot;&#58;&quot;&quot;,&quot;content\[3\]\.alternateText&quot;&#58;&quot;&quot;,&quot;content\[4\]\.alternateText&quot;&#58;&quot;&quot;&#125;,&quot;imageSources&quot;&#58;&#123;&#125;,&quot;links&quot;&#58;&#123;&#125;,&quot;componentDependencies&quot;&#58;&#123;&quot;heroLayoutComponentId&quot;&#58;&quot;9586b262-54de-4b27-9eb9-34c671400c33&quot;,&quot;carouselLayoutComponentId&quot;&#58;&quot;8ac0c53c-e8d0-4e3e-87d0-7449eb0d4027&quot;&#125;,&quot;customMetadata&quot;&#58;&#123;&quot;heroLayoutComponentId&quot;&#58;&#123;&quot;minCanvasWidth&quot;&#58;640&#125;,&quot;carouselLayoutComponentId&quot;&#58;&#123;&quot;maxCanvasWidth&quot;&#58;639&#125;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;1\.3&quot;,&quot;properties&quot;&#58;&#123;&quot;heroLayoutThreshold&quot;&#58;640,&quot;carouselLayoutMaxWidth&quot;&#58;639,&quot;layoutCategory&quot;&#58;1,&quot;layout&quot;&#58;5,&quot;content&quot;&#58;\[&#123;&quot;id&quot;&#58;&quot;36f4977f-688d-4fa2-827f-ec4c3a7c6290&quot;,&quot;type&quot;&#58;&quot;Image&quot;,&quot;color&quot;&#58;4,&quot;description&quot;&#58;&quot;&quot;,&quot;showDescription&quot;&#58;false,&quot;showTitle&quot;&#58;true,&quot;imageDisplayOption&quot;&#58;0,&quot;isDefaultImage&quot;&#58;false,&quot;showCallToAction&quot;&#58;false,&quot;isDefaultImageLoaded&quot;&#58;false,&quot;isCustomImageLoaded&quot;&#58;false,&quot;showFeatureText&quot;&#58;false&#125;,&#123;&quot;id&quot;&#58;&quot;2b66c8a5-106e-4066-a27c-7569ee71c981&quot;,&quot;type&quot;&#58;&quot;Image&quot;,&quot;color&quot;&#58;4,&quot;description&quot;&#58;&quot;&quot;,&quot;showDescription&quot;&#58;false,&quot;showTitle&quot;&#58;true,&quot;imageDisplayOption&quot;&#58;0,&quot;isDefaultImage&quot;&#58;false,&quot;showCallToAction&quot;&#58;false,&quot;isDefaultImageLoaded&quot;&#58;false,&quot;isCustomImageLoaded&quot;&#58;false,&quot;showFeatureText&quot;&#58;false&#125;,&#123;&quot;id&quot;&#58;&quot;56372181-93ad-48b9-b9c9-e21a12c09f91&quot;,&quot;type&quot;&#58;&quot;Image&quot;,&quot;color&quot;&#58;4,&quot;description&quot;&#58;&quot;&quot;,&quot;showDescription&quot;&#58;false,&quot;showTitle&quot;&#58;true,&quot;imageDisplayOption&quot;&#58;0,&quot;isDefaultImage&quot;&#58;false,&quot;showCallToAction&quot;&#58;false,&quot;isDefaultImageLoaded&quot;&#58;false,&quot;isCustomImageLoaded&quot;&#58;false,&quot;showFeatureText&quot;&#58;false&#125;,&#123;&quot;id&quot;&#58;&quot;25c91620-fd9d-4e4c-b48c-95ac29f4251c&quot;,&quot;type&quot;&#58;&quot;Image&quot;,&quot;color&quot;&#58;4,&quot;description&quot;&#58;&quot;&quot;,&quot;showDescription&quot;&#58;false,&quot;showTitle&quot;&#58;true,&quot;imageDisplayOption&quot;&#58;0,&quot;isDefaultImage&quot;&#58;false,&quot;showCallToAction&quot;&#58;false,&quot;isDefaultImageLoaded&quot;&#58;false,&quot;isCustomImageLoaded&quot;&#58;false,&quot;showFeatureText&quot;&#58;false&#125;,&#123;&quot;id&quot;&#58;&quot;ad63c722-b208-4e23-940e-f3489373cd66&quot;,&quot;type&quot;&#58;&quot;Image&quot;,&quot;color&quot;&#58;4,&quot;description&quot;&#58;&quot;&quot;,&quot;showDescription&quot;&#58;false,&quot;showTitle&quot;&#58;true,&quot;imageDisplayOption&quot;&#58;0,&quot;isDefaultImage&quot;&#58;false,&quot;showCallToAction&quot;&#58;false,&quot;isDefaultImageLoaded&quot;&#58;false,&quot;isCustomImageLoaded&quot;&#58;false,&quot;showFeatureText&quot;&#58;false&#

Same page with no web parts, which works.

&#123;&quot;displayMode&quot;&#58;2,&quot;position&quot;&#58;&#123;&quot;sectionIndex&quot;&#58;1,&quot;zoneIndex&quot;&#58;1&#125;&#125;
clientsidepages.ts:267
&#123;&quot;displayMode&quot;&#58;2,&quot;position&quot;&#58;&#123;&quot;sectionIndex&quot;&#58;1,&quot;zoneIndex&quot;&#58;1&#125;&#125;
 
Same page with custom web part with same error
&#123;&quot;controlType&quot;&#58;3,&quot;displayMode&quot;&#58;2,&quot;id&quot;&#58;&quot;c192fb7e-3398-4e21-a519-511636743f1e&quot;,&quot;position&quot;&#58;&#123;&quot;zoneIndex&quot;&#58;1,&quot;sectionIndex&quot;&#58;1,&quot;controlIndex&quot;&#58;1&#125;,&quot;webPartId&quot;&#58;&quot;e4cbbb07-342e-481f-9521-8025d426e73a&quot;&#125;
clientsidepages.ts:267
&#123;&quot;id&quot;&#58;&quot;e4cbbb07-342e-481f-9521-8025d426e73a&quot;,&quot;instanceId&quot;&#58;&quot;c192fb7e-3398-4e21-a519-511636743f1e&quot;,&quot;title&quot;&#58;&quot;\[development\]PageInformation&quot;,&quot;description&quot;&#58;&quot;Web part to show current page metadata&quot;,&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&#125;,&quot;imageSources&quot;&#58;&#123;&#125;,&quot;links&quot;&#58;&#123;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;1\.0&quot;,&quot;properties&quot;&#58;&#123;&quot;description&quot;&#58;&quot;PageInformation&quot;&#125;&#125;

**Comment by patrick-rodgers** [comment] 2018-06-14 14:02
It looks like there was a chance on the server to escape the '[', ']', and '.' chars in the string, so it couldn't decode correctly. Added code to handle this and as well return the server processed content to the server. PR will be merged pending CI checks. Thanks for helping out with the details, this will be part of Friday's beta release.

**Closed** 2018-06-14 14:13 UTC
Labels: area: code, status: fixed, type: bug

**Comment by raymondlittle100** [comment] 2018-06-14 14:39
Glad we got there in the end :)

Do you know when the actual release will be?

**Comment by harshdamaniahd** [comment] 2018-06-14 14:45
@patrick-rodgers thanks

**Comment by patrick-rodgers** [comment] 2018-06-14 17:43
Release is targeted for July 6th. The betas are full releases and are built from the same code so should work for you as an interim.

**Comment by pavan2920** [comment] 2018-07-09 11:45
Any news on updates ?? (Which was supposed to be released on 6th July)

**Comment by patrick-rodgers** [comment] 2018-07-09 12:31
@pavan2920 - yes the release was published July 6. You can always check the milestones, changelog, or the npmjs publish dates if you aren't sure.
