### ISSUE TITLE
wierdness with getFileByServerRelativePath with getText() in batch?   

### ISSUE THREAD

**Issue by PowellT** [pnp/pnpjs#2472] opened 2022-11-09 20:06 UTC
### Category
- [ ] Enhancement
- [ ] Bug
- [ X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  2.12.0   ]

Please specify what version(s) of SharePoint you are targeting: [ O365, SP 2019 ]

### Question
is getFileByServerRelativePath with .getText() usable with batching?

Without batching this works fine
const html:string =await sp.web.getFileByServerRelativePath ("myfilepath").getText();

trying to do something like this:

let filesarray:string[]=new Array()
let batch=sp.web.createBatch()
 sp.web.getFileByServerRelativePath ("myfilepath1").inBatch(batch).getText().then( res=>{
 console.log(res)
 filearray.push(res);
 }
sp.web.getFileByServerRelativePath ("myfilepath2").inBatch(batch).getText().then( res=>{
 console.log(res)
 filearray.push(res);
 }

batch.execute().then(()=>{
console.log(filearray)  <--- always blank
})

batch.Execute does not execute.  I am missing something fundamental.  Any clarification greatly appreciated.

**Comment by patrick-rodgers** [comment] 2022-11-09 20:11
getting files in batches is not supported. Pretty much anything that deals with uploading/downloading files won't work in a batch, by design.

**Comment by patrick-rodgers** [comment] 2022-11-11 16:56
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2022-11-11 16:56 UTC
