### ISSUE TITLE
Chaining getByLoginName(login).groups parameter issue

### ISSUE THREAD

**Issue by jrwiller13** [pnp/pnpjs#247] opened 2018-09-19 17:42 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

1.2.1 

### Expected / Desired Behavior / Question
Chaining `groups `after a `getByLoginName `should return groups for a user when a valid LoginName is passed to the getByLoginName. 

let userGroups = sp.web.siteUsers.getByLoginName(user).groups.get();

### Observed Behavior
Request fails with the following error message logged: 

`Error making HttpClient request in queryable: [400] Bad Request ::> 
{
      "responseBody":   {
          "odata.error":  {
              "code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException",
              "message":  {
                  "lang":"en-US",
                  "value":"Missing required query string: @v." 
               }
           }
      },
      "responseHeaders": {}
}`

### Steps to Reproduce
Try to make a call to groups following a getByLoginName(userLogin). 

### Additional Note
This appears to be the same behavior as [issue 571 ](https://github.com/SharePoint/PnP-JS-Core/issues/571) from pnp-js-core, as I see the same code that was [modified](https://github.com/SharePoint/PnP-JS-Core/pull/573/commits/7f1400453a2989a732fa8063923aa52cf4e13925) in the fix for this issue, still exists inside the sitesusers.ts of this library.

**Comment by patrick-rodgers** [comment] 2018-09-19 23:13
Thanks for reporting this and the great research tracking down the root cause. I just pushed a fix into [this PR](https://github.com/pnp/pnpjs/pull/246) so will be in this week's beta coming out Friday. Thanks!

**Closed** 2018-09-20 20:40 UTC
Labels: area: code, status: fixed, type: bug
