### ISSUE TITLE
Util method to test folder / file name before adding it to library

### ISSUE THREAD

**Issue by michaelmaillot** [pnp/pnpjs#1097] opened 2020-03-04 14:48 UTC
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.0.3

Please specify what version(s) of SharePoint you are targeting: Online

### Expected / Desired Behavior / Question

The idea here is to enhance the `common` package (or `Files` / `Folders` packages ?), to add a method that tells you if a file / folder name is ok for a SharePoint library.

Based on [this article](https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa), I've managed to create the appropriate RegEx :

`^((((L|l)(P|p)(T|t))|(C|c)(O|o)(M|m))[0-9])$|(^(P|p)(R|r)(N|n))$|^(A|a)(U|u)(X|x)$|^(N|n)(U|u)(L|l)$|^(C|c)(O|o)(N|n)$|_vti_|^[\~$]|[«\*:<>\?\/\\\\\|]`

I'm not a RegEx expert and I haven't found an example online that covers every case, so if anyone has a better approach, feel free to complete this post 😉.

P.S.: I haven't include # and % characters, as it's a Tenant parameter that can be switched on to be allowed. I also didn't include the "&" character, as it only concerns Office 2010.

**Comment by patrick-rodgers** [comment] 2020-04-02 14:34
I think the issue is you have lots of logic like ""forms" isn't supported when the folder is at the root level for a library." from the article. Not sure how we would handle stuff like that. And your P.S. is another "special case". This feels to me like something I don't want to maintain as we would get issues about all the edge cases and would be creating an expectation that the method would always be accurate.

I am open to being convinced or reviewing a PR with tests included to cover all the various scenarios - but this isn't something I would plan to add to the library.

**Comment by patrick-rodgers** [comment] 2020-07-14 14:10
Going to close this - remain open to getting PR to review for this functionality. Thanks!

**Closed by patrick-rodgers** 2020-07-14 14:10 UTC
Labels: area: code, contribution opportunity🐇, type: enhancement
