### ISSUE TITLE
Creating Folder in SharePoint List

### ISSUE THREAD

**Issue by AntyfrizZz** [pnp/pnpjs#107] opened 2018-05-17 11:20 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.0.5]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
*If you are reporting an issue please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit. If you are asking a question, ask away!*

### Observed Behavior
*If you are reporting an issue please describe the behavior you expected to occur when performing the action. If you are making a
suggestion or asking a question delete this section.*

### Steps to Reproduce
*If you are reporting an issue please describe the steps to reproduce the bug in sufficient detail to allow testing. If you are making
a suggestion or asking a question delete this section.*

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* If you have a general question [gitter](https://gitter.im/OfficeDev/PnP-JS-Core) may be a better forum.
* Remember to include sufficient details and context.
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thank you for your feedback!

Hello,
I have an issue when i am adding folder in SP list.
I used a few approaches with no result.

**sp.web.lists.getByTitle("asd").rootFolder.folders.add("FolderName");** - this adds the folder, I can see it within the result from query sp.web.lists.getByTitle("asd").rootFolder.folders.get(), but i cant see the folder in the view (the view is not flat, i have other folders in it)
**sp.web.lists.getByTitle("asd").items.add({Title: "Foldername", "ContentTypeId": "0x0120"})** - this add the folder, i can see it in the view, but when i open it it is with name like {ID}_.000. Also i couldnt manage to change the 000 name and to move the folder. Tried with item.folder.moveTo() and item.file.moveTo() or something like that and i didnt manage to move it or change the name.

Best Regards,
Yavor

**Comment by koltyakov** [comment] 2018-05-17 11:26
Hey @AntyfrizZz,

This is a duplicate of [this issue](https://github.com/pnp/pnpjs/issues/100).
Please check the answer provided in there.

The key factor is that after a folder is created it's item's `FileLeafRef` property should be updated to correspond to a valid folder name/path.

**Comment by patrick-rodgers** [comment] 2018-05-21 12:11
Going to close this as answered. Please do _reopen_ should you require more assistance. Thanks!

**Closed by patrick-rodgers** 2018-05-21 12:11 UTC
Labels: area: code, status: answered, type: question
