### ISSUE TITLE
Using ClientSidePage: Cannot read property '_url' of undefined

### ISSUE THREAD

**Issue by CarlosMunozDiaz** [pnp/pnpjs#910] opened 2019-11-06 06:33 UTC
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [   1.3.6    ]

Please specify what version(s) of SharePoint you are targeting: [   Online    ]

### Expected / Desired Behavior / Question

I want to access to a Client-side page webpart with pnp/sp in a React-SPFx project and I do it with the next code (I will not share the entire because in terms of clearance):

```typescript
import { sp, ClientSidePage, SPRest } from "@pnp/sp";
.....
private service: SPRest;
    constructor(props: IFeaturedBoxSimpleNewsCarouselProps) {
        super(props);
        this.state = {
            carouselData: null,
            slides: new Array<JSX.Element>(),
            isDataLoaded: false
        };
        this.service = this.props.service; **<this.props.service -in the WebPart.ts- give me a service related to the 'context' of the webpart>**
    }
.....
let elementoNoticia: ClientSidePage = null;
const estructuraNoticia = sp.web.getFileByServerRelativePath(item.FileRef); **<FileRef returns the right File>**                 
elementoNoticia = await ClientSidePage.fromFile(estructuraNoticia); **<Here is when the error happens**>
````
And instead of an appropiate response, the 'queryable.ts' file returns the next response (in Chrome's console):

```typescript
Uncaught (in promise) TypeError: Cannot read property '_url' of undefined
    at qn.J.extend (queryable.ts:214)
    at qn.R [as constructor] (sharepointqueryable.ts:65)
    at qn.k [as constructor] (site.ts:131)
    at qn.ze [as constructor] (webs.ts:126)
    at new qn (sharepointqueryableshareable.ts:601)
    at sharepointqueryableshareable.ts:601
```

I also want to share parts of my package.json and config.json (its externals properties) files if it helps you:

package.json
```typescript
"dependencies": {
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-lodash-subset": "1.9.1",
    "@microsoft/sp-office-ui-fabric-core": "1.9.1",
    "@microsoft/sp-property-pane": "1.9.1",
    "@microsoft/sp-webpart-base": "1.9.1",
    "@pnp/common": "^1.3.6",
    "@pnp/graph": "^1.3.6",
    "@pnp/logging": "^1.3.6",
    "@pnp/odata": "^1.3.6",
.....
"devDependencies": {
    "@babel/polyfill": "^7.6.0",
    "@microsoft/rush-stack-compiler-2.9": "0.7.16",
    "@microsoft/sp-build-web": "1.9.1",
    "@microsoft/sp-module-interfaces": "1.9.1",
    "@microsoft/sp-tslint-rules": "1.9.1",
    "@microsoft/sp-webpart-workbench": "1.9.1",
    **"@pnp/sp": "^1.3.6",**
.....
```

config.json
```typescript
"externals": {
....
    "@pnp/sp": {
      "path": "node_modules/@pnp/sp/dist/sp.es5.umd.min.js",
      "globalName": "pnp.sp",
      "globalDependencies": [
        "@pnp/logging",
        "@pnp/common",
        "@pnp/odata",
        "tslib"
      ]
    },
    "@pnp/odata": {
      "path": "node_modules/@pnp/odata/dist/odata.es5.umd.min.js",
      "globalName": "pnp.odata",
      "globalDependencies": [
        "@pnp/common",
        "@pnp/logging",
        "tslib"
      ]
    },
    "@pnp/common": {
      "path": "node_modules/@pnp/common/dist/common.es5.umd.bundle.min.js",
      "globalName": "pnp.common"
    },
    "@pnp/logging": {
      "path": "node_modules/@pnp/logging/dist/logging.es5.umd.min.js",
      "globalName": "pnp.logging",
      "globalDependencies": [
        "tslib"
      ]
    },
    "tslib": {
      "path": "node_modules/tslib/tslib.js",
      "globalName": "tslib"
    }
  }
```

I hope everything here can help you to find any issue related to my problem. And forgive my possible mistakes: it is the first time I report an Issue Question.

Thank you for your feedback!

**Comment by patrick-rodgers** [comment] 2019-11-06 14:12
Hi @CarlosMunozDiaz - understand you can't share all your code but its tough to really understand what is happening. Does your file name or path happen to have any special characters in it? The code you do show should work just by looking at it and does if I test it locally. Also, are you [establishing context](https://pnp.github.io/pnpjs/documentation/getting-started/#getting-started-with-sharepoint-framework) using the setup function?

**Comment by patrick-rodgers** [comment] 2019-12-02 18:50
Have tried but am unable to reproduce this error. Can you remove PnPjs from externals and package it up with the solution and see if that solves the issue? Externals don't currently work great in v1 with SPFx - something we have addressed with v2 set to be released later this month.

**Comment by patrick-rodgers** [comment] 2019-12-30 20:37
Going to close this as unable to reproduce. If you continue to have an issue please open a new issue and ref this one. Thanks!

**Closed by patrick-rodgers** 2019-12-30 20:37 UTC
Labels: area: code, status: details needed, type: someting isn't working
