### ISSUE TITLE
sp web search query

### ISSUE THREAD

**Issue by robiharid** [pnp/pnpjs#924] opened 2019-11-14 10:51 UTC
Would it be possible to use the built in sp web to query the tenant site?

I am trying to grab Delve blogs

tenantSite.com/_api/search/query?QueryText=%27SecondaryFileExtension:PointPub%27

**Comment by patrick-rodgers** [comment] 2019-11-14 13:11
Can you share the code you have tried that isn't working?

**Comment by robiharid** [comment] 2019-11-18 14:26
> Can you share the code you have tried that isn't working?

The problem is that the behaviour of the search API is not very consistent.

I published three blogs. 1/3 HitHighlightedSummary properties were null. When I updated another blog post, it went completely missing from the search API query. 

The blog posts were all published consistently with the same Lorem Ipsum body and different titles./subtitles.

This is my code:

`return fetch(
    "https://carrsgroup.sharepoint.com/_api/search/query?QueryText=%27SecondaryFileExtension:PointPub%27"
  )
    .then(resp => resp.text())
    .then(resp => {
      const data = convert.xml2js(resp, { compact: true });

      const results: any[] =
        data["d:query"]["d:PrimaryQueryResult"]["d:RelevantResults"]["d:Table"][
          "d:Rows"
        ]["d:element"];

      const postData = Object.keys(results).map(el => {
        return results[el]["d:Cells"]["d:element"];
      });

      const allPosts = postData.map(el => {
        const timeCreated = el.find(item => item["d:Key"]["_text"] === "Write");
        const title = el.find(item => item["d:Key"]["_text"] === "Title");
        const author = el.find(item => item["d:Key"]["_text"] === "Author");
        const summary = el.find(
          item => item["d:Key"]["_text"] === "HitHighlightedSummary"
        );
        const path = el.find(item => item["d:Key"]["_text"] === "Path");`

**Comment by patrick-rodgers** [comment] 2019-12-02 19:06
If the library code is working as expected and the service isn't that isn't something we can address. Articles are not indexed instantly and there can be some delay before any item appears in the search index. Going to close this issue as external to the library - should you find that the issue is indeed with the library please open a new issue, reference this issue, and provide any additional details you can. Thanks!

**Closed by patrick-rodgers** 2019-12-02 19:06 UTC
Labels: area: non-library, status: details needed, type: question
