### ISSUE TITLE
Make getListItemChangesSinceToken return an object

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#51] opened 2018-03-18 01:24 UTC
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.0.3]

### Expected / Desired Behavior / Question

When using the `sp.web.SomeList.getListItemChangesSinceToken()` call, the return value is an XML string. This is very inconvenient.

After running it through `xml2js`, the result is not very friendly (empty result shown for terseness):

```js
{
  "GetListItemChangesSinceTokenResult": {
    "listitems": [
      {
        "$": {
          "MinTimeBetweenSyncs": "0",
          "RecommendedTimeBetweenSyncs": "180",
          "MaxBulkDocumentSyncSize": "500",
          "MaxRecommendedEmbeddedFileSize": "500",
          "xmlns:rs": "urn:schemas-microsoft-com:rowset"
        },
        "Changes": [
          {
            "$": {
              "LastChangeToken": "1;3;d6b498bd-346a-4fe0-800a-f2cb44510949;636569147769100000;114019856"
            }
          }
        ],
        "rs:data": [
          {
            "$": {
              "ItemCount": "0"
            }
          }
        ]
      }
    ]
  }
}
```

it would be much nicer if the result was simply e.g. `{ChangeToken, Items, MinTimeBetweenSyncs, ...}`, converting the values where appropriate (folders, files, MinTimeBetweenSyncs is an integer, …)

The library is supposed to encapsulate the communication with sharepoint, using native objects, and this xml is a leaky abstraction.

At the very least it would be nice to see some documentation on best practices on how to handle this result in JS.

**Comment by patrick-rodgers** [comment] 2018-03-19 16:40
The underlying method returns an xml stream by design - so we are just returning that currently. Is this something you would be interested in helping out with in a PR to add the support/docs you would like to see?

**Comment by wmertens** [comment] 2018-03-30 11:00
Yes, I'll share with what I come up with.

Question, I notice that many of the field values seem to be prefixed with e.g. `3;`. I have the impression that in this case, the prefix is the index. Is that correct? Why is it there?

**Comment by patrick-rodgers** [comment] 2018-06-18 14:36
Going to close this due to age. This isn't something we see as a priority but will absolutely look at a PR if you do have the time to put one together. Thanks!

**Closed by patrick-rodgers** 2018-06-18 14:36 UTC
Labels: area: code, status: help wanted, type: enhancement
