### ISSUE TITLE
 Problems adding "MODERNCALENDAR" view to a list

### ISSUE THREAD

**Issue by jamesm2024** [pnp/pnpjs#3162] opened 2024-11-05 19:08 UTC
### What version of PnPjs library you are using

3.x (No longer supported)

### Minor Version Number

3.25.0

### Target environment

SharePoint Framework

### Additional environment details

SharePoint Online, React

### Question/Request

I'm struggling to add a "MODERNCALENDAR" view to a list. 
I have created a simple list named "Cal" with three columns: Title, StartDate, EndDate.
I pass the name of the list Cal to the following function to add a ModernCalendar view named Test.
The view is created, however it always displays "Invalid Calendar View" (refer attached image) when first opened.
How do I stop this from happenning?
```
export const getViews = async (listName: string): Promise<void> => {

try {
    const sp = getSP();
    const list = sp.web.lists.getByTitle(listName);

    const viewData = `<FieldRef Name="Title" Type="CalendarMonthTitle" /><FieldRef Name="Title" Type="CalendarWeekTitle" /><FieldRef Name="Title" Type="CalendarWeekLocation" /><FieldRef Name="Title" Type="CalendarDayTitle" /><FieldRef Name="Title" Type="CalendarDayLocation" />`;
    const viewQuery = `<ViewFields><FieldRef Name="StartDate" /><FieldRef Name="EndDate" /><FieldRef Name="Title" /></ViewFields>`;
    const viewStyles = `<CalendarViewStyle Title="Day" Type="day" Template="CalendarViewdayChrome" Sequence="1" Default="FALSE" /><CalendarViewStyle Title="Week" Type="week" Template="CalendarViewweekChrome" Sequence="2" Default="TRUE" /><CalendarViewStyle Title="Month" Type="month" Template="CalendarViewmonthChrome" Sequence="3" Default="FALSE" /><CalendarViewStyle Title="Work week" Type="workweek" Template="CalendarViewweekChrome" Sequence="4" Default="FALSE" />`;
    
    const res = await list.views.add("Test", false, { CalendarViewStyles: viewStyles, ViewData: viewData, ViewQuery: viewQuery, Paged: true, RowLimit: 0, PersonalView: false, ViewType2: "MODERNCALENDAR"});
 
    console.log(res.data);
    console.log(res.view);
    
} 
catch (error) {
    console.error('Error getting views', error);
    throw error; // Rethrow the error for handling in the calling code
}

};
```
![Screenshot 2024-11-06 0552451](https://github.com/user-attachments/assets/83d53884-f07f-45e4-80de-63630a64967e)

**Comment by patrick-rodgers** [comment] 2024-11-06 00:38
The only suggestion I have would be to export a view setup how you like and duplicate that in the markup you use to create a new view. I don't have any special knowledge of what makes those individual views work, might just take some digging around.

**Comment by jamesm2024** [comment] 2024-11-06 04:28
I've gone over each view object (working and not working) many times now and cannot determine the exact cause. Can you point me to any documentation describing the configuration of the Calendar (specifically the flag that causes the alert). The only info I can find is:
```
https://stackoverflow.com/questions/67271425/create-modern-calendar-view-for-sharepoint-online-list-using-the-rest-api
```
I think it is more than the following: 
```
ViewData has 5 FieldRef entries - 1 for month view and 2 each for week and day view. The fields are used as 'Title' for respective visualizations. If this is missing, you will see the popup to 'fix' calendar view.
```

**Comment by bcameron1231** [comment] 2024-11-15 21:34
I tested this out a bit. I also am seeing the issues you are having. I couldn't tell exactly what the problem is aside from it having trouble binding the StartDate.

**Comment by jamesm2024** [comment] 2024-11-15 22:36
Thanks for your interest. Is there any way to find out more about the implementation from microsoft? I got to a dead end trying to make it work.

**Comment by bcameron1231** [comment] 2024-11-18 12:02
Here is what Microsoft uses to create their Calendar View. /views/add

```
fetch("https://tenant.sharepoint.com/sites/CalendarTest/_api/web/GetList(@a1)/Views/Add?@a1=%27%2Fsites%2FCollabDays%2FLists%2FCalendar%27", {
  "headers": {
    "accept": "application/json;odata=verbose"
  },
  "body": "{"parameters":{"__metadata":{"type":"SP.ViewCreationInformation"},"Title":"TestView","ViewFields":{"__metadata":{"type":"Collection(Edm.String)"},"results":["StartDate","EndDate","Title","Title"]},"Query":"<Where><DateRangesOverlap><FieldRef Name='StartDate' /><FieldRef Name='EndDate' /><Value Type='DateTime'><Month /></Value></DateRangesOverlap></Where>","Paged":true,"PersonalView":false,"RowLimit":0,"ViewTypeKind":1,"ViewType2":"MODERNCALENDAR","ViewData":"<FieldRef Name="Title" Type="CalendarMonthTitle" /><FieldRef Name="Title" Type="CalendarWeekTitle" /><FieldRef Name="Title" Type="CalendarWeekLocation" /><FieldRef Name="Title" Type="CalendarDayTitle" /><FieldRef Name="" Type="CalendarDayLocation" />","CalendarViewStyles":"<CalendarViewStyle Title="Day" Type="day" Template="CalendarViewdayChrome" Sequence="1" Default="FALSE" /><CalendarViewStyle Title="Week" Type="week" Template="CalendarViewweekChrome" Sequence="2" Default="TRUE" /><CalendarViewStyle Title="Month" Type="month" Template="CalendarViewmonthChrome" Sequence="3" Default="FALSE" /><CalendarViewStyle Title="Work week" Type="workweek" Template="CalendarViewweekChrome" Sequence="4" Default="FALSE" />"}}",
  "method": "POST",
});
```

**Comment by juliemturner** [comment] 2024-12-10 02:02
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Closed by juliemturner** 2024-12-10 02:02 UTC
Labels: help wanted 🐇, type: question, status: answered, type: version 3
