### ISSUE TITLE
Unable to import PnPjs modules correctly in NodeJS 16

### ISSUE THREAD

**Issue by Yvand** [pnp/pnpjs#2141] opened 2022-03-03 16:49 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.0.3]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question

I am trying hard to use the v3 version of PnPjs, but the ESModules support is causing me a lot of trouble.
My scenario is a simple TypeScript project using [Azure Functions runtime 4 project](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=in-process%2Cv4&pivots=programming-language-typescript), node 16.13.2 and TypeScript 4.7.0-dev.20220303.
Based on [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/esm-node.html), I have this `tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "target": "ES2017",
    "outDir": "dist",
    "rootDir": ".",
    "sourceMap": true,
    "strict": false
  }
}
```

I also set `"type": "module"` in my `package.json` file.

I have this simple `pnptest.mts` file:

```js
import { SPDefault } from "@pnp/nodejs";
import { spfi } from "@pnp/sp";
import "@pnp/sp/webs/index.js";
import { Configuration } from "@azure/msal-node";
// import "@pnp/core/util.js"

const config: Configuration = {
  auth: {
      authority: "https://login.microsoftonline.com/{tenant id or common}/",
      clientId: "{application (client) id}",
      clientSecret: "",
  },
};

const sp = spfi("https://318studios.sharepoint.com/sites/dev").using(SPDefault({
            msal: {
                config,
                scopes: [ 'https://{my tenant}.sharepoint.com/.default' ]
            },
        }));

const webData = await sp.web();
```

### Observed Behavior

`tsc` compilation works fine and produces the .mjs file as expected. But when I run the function I get this error:

```
[2022-03-03T16:38:50.927Z] Worker was unable to load function HelloHttp: 'Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/app/azure/azure-functions/testnodepnpv4/node_modules/@pnp/core/util' imported from /usr/app/azure/azure-functions/testnodepnpv4/node_modules/@pnp/nodejs/sp-extensions/stream.js
[2022-03-03T16:38:50.927Z] Did you mean to import @pnp/core/util.js?'
```

If I uncomment the `import "@pnp/core/util.js"` I get the exact same error.

I guess I must be doing a dumb mistake (ESM is very new to me).  
And I noticed that in [your samples](https://pnp.github.io/pnpjs/concepts/authentication/#msal-nodejs) you don't speecify `index.js` in `import "@pnp/sp/webs/index.js"`, while I have to do it otherwise I have another error:

```
[2022-03-03T16:42:56.115Z] Worker was unable to load function HelloHttp: 'Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/usr/app/azure/azure-functions/testnodepnpv4/node_modules/@pnp/sp/webs' is not supported resolving ES modules imported from /usr/app/azure/azure-functions/testnodepnpv4/dist/HelloHttp/pnptest.mjs
[2022-03-03T16:42:56.115Z] Did you mean to import @pnp/sp/webs/index.js?'
```

Thank you for your help

**Comment by juliemturner** [comment] 2022-03-11 16:09
@Yvand  -- So that you don't think we're ignoring this we're in discussions on how to address this issue better.  We'll respond more when we have a more detailed answer.

**Comment by patrick-rodgers** [comment] 2022-03-11 20:34
@Yvand - we are evaluating things around modules. Anticipated that the transition to esm would be easier, but this is the largest friction point so far with v3 release. Might go back to releasing commonjs, or revisit bundling it together. Previously this didn't work, but haven't investigated since node firmed up esm support. Anyway, sorry for the troubles here, we're working on it.

**Comment by Yvand** [comment] 2022-03-14 12:27
Thank you for the explanations, and your work on this project, that is very helpful.
But I'm still missing something: Can you please explain what do I need to change in my setup to use PnPjs v3 with NodeJS [as documented here](https://pnp.github.io/pnpjs/getting-started/#using-pnpsp-spfi-factory-interface-in-nodejs)?

**Comment by Yvand** [comment] 2022-03-14 14:42
@juliemturner let me try to be more specific: I understand that PnPjs 3 is ESM only, and [this example works with NodeJS](https://pnp.github.io/pnpjs/getting-started/#using-pnpsp-spfi-factory-interface-in-nodejs).
So I don't understand why my sample project does not work while this sample does, as both scenarios seem identical to me.

**Comment by sebastianrogers** [comment] 2022-03-17 14:47
I have an identical issue with Azure Functions V4.  I have followed the advice given in [ECMAScript modules (preview)](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=v2-v3-v4-export%2Cv2-v3-v4-done%2Cv2%2Cv2-log-custom-telemetry%2Cv2-accessing-request-and-response%2Cwindows-setting-the-node-version#ecmascript-modules) but get the following when I run the azure function:

```
[2022-03-17T14:24:54.765Z] Worker process started and initialized.
[2022-03-17T14:24:54.887Z] Worker was unable to load function GetWeb: 'Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/workspaces/azure-function-pnp-template/PnP/node_modules/@pnp/sp/files' is not supported resolving ES modules imported from /workspaces/azure-function-pnp-template/PnP/node_modules/@pnp/nodejs/sp-extensions/stream.js
[2022-03-17T14:24:54.888Z] Did you mean to import @pnp/sp/files/index.js?'
```

I have renamed my script file from "scriptFile": "../dist/GetWeb/index.js" to "scriptFile": "../dist/GetWeb/index.mjs".

This appears to be caused by the use of directory imports which is not supported by Azure Functions.

By changing these in node_modules, for debugging purposes only, I was able to get it to work locally.

So

@pnp/nodejs/sp-extensions/stream.js imports become:

```js
import { headers } from "@pnp/queryable/index.js";
import { File, Files } from "@pnp/sp/files/index.js";
import { spPost } from "@pnp/sp/operations.js";
import { extendFactory, getGUID, isFunc } from "@pnp/core/index.js";
import { odataUrlFrom, escapeQueryStrValue } from "@pnp/sp/index.js";
import { StreamParse } from "../behaviors/stream-parse.js";
```

My test file getPnPWeb.mts becomes:

```js
import { SPFI } from "@pnp/sp";
import "@pnp/sp/webs/index.js";

export async function getPnPWeb(spfi: SPFI) {
    return await spfi.web.select("Title", "Description")();
}
```

This then works.

**Comment by juliemturner** [comment] 2022-03-23 17:19
Correct me if I'm wrong but doesn't option 3 leave the door open for option 1?

**Comment by patrick-rodgers** [comment] 2022-03-23 17:39
Option 3 *I think* means you wouldn't need to do Option 1. Would need to fully test it. If you include the flag from Option 1 then no other action is needed, but not everyone would be able to control the launch of the node process to apply that flag.

**Comment by juliemturner** [comment] 2022-03-23 17:46
Ok I see... it's the addition of the internal references that would most likely (TBD) eliminate the need for the flag, but then users would still have to reference the imports with the extra index.js

**Comment by sebastianrogers** [comment] 2022-03-24 15:27
Option 1:

As you say @patrick-rodgers for option 1 we can't always control the node process launch, for example Azure Functions. Also I notice on the node site https://nodejs.org/api/esm.html#customizing-esm-specifier-resolution-algorithm

> Do not rely on this flag. We plan to remove it once the [Loaders API](https://nodejs.org/api/esm.html#loaders) has advanced to the point that equivalent functionality can be achieved via custom loaders.

> The current specifier resolution does not support all default behavior of the CommonJS loader. One of the behavior differences is automatic resolution of file extensions and the ability to import directories that have an index file.

Option 2:
Writing your own custom loader is foreseen by Node but according to the link above it hasn't reached that point yet.  Also would this not be a generic component rather than one in PnP as if done correctly it would work for any project using automatic file resolution.

Option 3:
This is the only currently supported mechanism by node and its future proof.  You could still use option 1 if you have access to the node launch as @juliemturner says but you don't need to.

Based on this I'd say its option 3 as for Azure Functions the other two options don't work (and we make extensive use of Azure Functions so I may be biased).

**Comment by Yvand** [comment] 2022-03-24 16:24
My target is also Azure Functions v4, so Node flag `--experimental-specifier-resolution=node` is not a possible option.

**Comment by patrick-rodgers** [comment] 2022-03-24 17:09
Good News Everyone!

It turns out there are very few changes to make to fix this. From what you wrote @sebastianrogers I thought we would have to update all the imports - but just the few that aren't root. Meaning "@pnp/sp" is ok, but "@pnp/sp/webs" must be updated to "@pnp/sp/webs/index.js".

I am working on making these updates now, but all node solutions would have to include the "index.js" for selective imports. We aren't going to update every documentation page to show both possibilities, but will add a message to the getting started page.

Thanks to everyone for helping us work through this!

**Comment by patrick-rodgers** [comment] 2022-03-24 17:37
@sebastianrogers, @Yvand, @barkdoll - going to merge what I think is the fix for this. Will be in tomorrow's nightly build. If you get a chance and can verify sometime before 3.2 is schedule to release I'd appreciate it. Would love to get this resolved with that monthly release. Thanks!

**Closed** 2022-03-24 17:37 UTC
Labels: type: bug, status: in progress, area: package

**Comment by sebastianrogers** [comment] 2022-03-26 07:10
@patrick-rodgers sorry to be a pain but how can we access the nightly build?

**Comment by juliemturner** [comment] 2022-03-26 13:11
You can see the latest nightly build by looking at the NPMJS page for the repository...

![image](https://user-images.githubusercontent.com/7570936/160241020-70f771c0-36b0-4913-abed-5c969d3a069d.png)


then you just do:
`npm i @pnp/sp@3.1.0-v3nightly.20220225 --save`

**Comment by sebastianrogers** [comment] 2022-03-28 08:32
I was looking at @pnp/pnpjs - my bad.

Written a simple test rig for Azure Functions [[simple-azure-function-pnp-template](https://github.com/Simple-Innovation/simple-azure-function-pnp-template)](https://github.com/Simple-Innovation/simple-azure-function-pnp-template) and the two functions tested so farhave worked:

- web.select
- web.lists.getByTitle

```ts
import { SPFI } from "@pnp/sp/index.js";
import "@pnp/sp/webs/index.js";
```

Its looking good so I'll try it in an actual working Azure Function.

**Comment by barkdoll** [comment] 2022-04-06 17:29
I will be testing the nightly soon. Hoping to give some feedback on the changes later this week, although I am glad to hear @sebastianrogers case is turning out successful!
