### ISSUE TITLE
file.getBuffer().then raises an exception "TypeError: r.buffer is not a function"

### ISSUE THREAD

**Issue by pabmardo** [pnp/pnpjs#111] opened 2018-05-25 07:21 UTC
### Category
- [ ] Enhancement
- [*] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.0.5 and 1.0.4]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
Trying to access a file buffer from a CommandSet (a button that when selecting an item generates a word with some content)

### Observed Behavior
Its failing with an uncaught (in promise) exception at BufferParser.ParseImpl
Uncaught (in promise) TypeError: r.buffer is not a function
    at BufferParser.parseImpl (pipeline.ts:27)
    at parsers.ts:36
    at new Promise (<anonymous>)
    at BufferParser.ODataParserBase.parse (parsers.ts:35)
    at pipeline.ts:226

### Steps to Reproduce
import {sp}  from "@pnp/sp";
In a CommandSet 
In the onInit
return super.onInit().then(_ => {
      sp.setup({
        spfxContext: this.context
      });

in the onExecute
Was failing in a batch, but tested is failing while outside the batch

sp.web.getFolderByServerRelativeUrl("/sites/DevSite/Shared Documents/")
                .files.getByName("template.docx").get().then(file => {
                        Dialog.alert("got file with information, name etc");
                        
                        if (file !== undefined && file !== null) {
                            file.getBuffer().then((buffer : ArrayBuffer) => { //Explosion!!!
                              Dialog.alert("Bravo!!");
                              //this.content = buffer;
                          });
                        }
                });

//This version is also fails
sp.web.getFileByServerRelativeUrl("/sites/DevSite/Shared Documents/template.docx").getBuffer().
                then((buffer: ArrayBuffer) => {
                  }

Coding with VS Core

Thank you for your feedback!

**Comment by tavikukko** [comment] 2018-05-25 11:20
Tested this same with SP Editor (not published version) and also experienced the same.
![screen shot 2018-05-25 at 14 18 05](https://user-images.githubusercontent.com/2223355/40541950-ab235ff2-6026-11e8-996f-65b389f76744.png)

**Comment by patrick-rodgers** [comment] 2018-05-25 14:26
Thanks - Yes, this was a regression and is fixed pending release. Sorry about that, will have a release Tuesday 29 May that will include fix. Going to close this one as the issue is tracked in #103.

**Closed by patrick-rodgers** 2018-05-25 14:26 UTC
Labels: area: code, status: fixed, type: bug
