### ISSUE TITLE
ClientsidePage setting Banner Issue

### ISSUE THREAD

**Issue by Joy-jeevan** [pnp/pnpjs#591] opened 2019-04-05 12:36 UTC
### Category
- Bug
### Version

Please specify what version of the library you are using: [    ^1.3.2-0     ]

Please specify what version(s) of SharePoint you are targeting: [   online      ]

### Expected / Desired Behavior / Question
I am trying create new page using clientsidepage with option of setting Banner Image for the same but  clientSidepage is not getting saved when page.setBannerImage() method is used.

Image Url is working fine
![tempsnip](https://user-images.githubusercontent.com/14804189/55627255-548cc500-57cb-11e9-9455-e49169e7d13b.png)
 
on click of error get request, generates the following URL

https://xxxxx.sharepoint.com/sites/TestPlayground/_api/web/getFileByServerRelativePath(decodedUrl='https://xxxx.sharepoint.com/sites/TestPlayground/SiteAssets/ClientFormImages/bloom-blossom-close-up-60057.jpg')/listItemAllFields?$select=UniqueId,ParentList/Id&$expand=ParentList

### Observed Behavior
await page.save() throws error when 
page.setBannerImage(bannerUrl); is present and works fine when removed.

**Comment by patrick-rodgers** [comment] 2019-04-05 13:02
This is a duplicate of #576 - which I see you also opened. The fix will be released today (April 5). Closing this as duplicate.

**Comment by Joy-jeevan** [comment] 2019-04-08 05:08
This issue was logged for beta version. I updated my pnpjs package to 1.3.2 and still the above issue remains.

**Comment by patrick-rodgers** [comment] 2019-04-08 13:35
Can you share your code?

**Comment by Joy-jeevan** [comment] 2019-04-09 09:07
Here's the simplest code which is not working.
if I remove the bannerImageUrl or setBannerImage function page gets saved

` const page=await sp.web.addClientSidePage("Testing","testing");`
`// page.setBannerImage(this.state.bannerUrl);` `page.bannerImageUrl="http://image.desk7.net/Landscape%20Wallpapers/11811_1024x768.jpg";`
`// page.addSection().addControl(ImageGalleryPart);`
`page.save();`
`//await page.save();`

**Comment by Joy-jeevan** [comment] 2019-04-09 09:15
Mistakenly clicked on close and comment button.

Here's the simplest code which is not working
If I remove bannerImageUrl or  setBannerImage function page gets saved

`const page=await sp.web.addClientSidePage('Testing','Testing');`
`// page.setBannerImage(this.state.bannerUrl);`
`page.bannerImageUrl="http://image.desk7.net/Landscape%20Wallpapers/11811_1024x768.jpg";`
`// page.addSection().addControl(ImageGalleryPart);`
`page.save();`
`//await page.save();`

**Comment by Joy-jeevan** [comment] 2019-04-09 12:46
I have used that link for that example purpose only. I am actually saving the image in SiteAssets and then setting the banner. I am able to change the banner through UI.

**Comment by patrick-rodgers** [comment] 2019-04-09 13:07
Can you share the code you are actually using? It is very hard to try and reproduce an issue while guessing what you are doing when you see the problem. Also, I noticied you had the await line commented out for the save, I assume you have tried it with that as you would want to wait for the save operation to complete.

**Comment by Joy-jeevan** [comment] 2019-04-10 07:04
I was using absolute URL to fetch the BannerImage which was giving me the issue,changing the path to relative URL solved the issue.
It would be nice to use absolute URL's rather than relative URL though.

Thanks a lot @patrick-rodgers .

**Comment by patrick-rodgers** [comment] 2019-04-10 12:36
Ah, so absolute url might be the issue. That I can check.

**Comment by patrick-rodgers** [comment] 2019-04-10 15:25
Added code to parse the absolute url in #597. Will be part of the next release. Until then you can use server relative urls or this code:

```TypeScript
if (isUrlAbsolute(origImgUrl)) {
    // do our best to make this a server relative url by removing the x.sharepoint.com part
    origImgUrl = origImgUrl.replace(/^https?:\/\/[a-z0-9\.]*?\.[a-z]{2,3}\//i, "/");
}
```

Thanks!

**Closed by patrick-rodgers** 2019-04-10 15:25 UTC
Labels: area: code, status: complete, type: enhancement
