### ISSUE TITLE
Adding new empty Excel Spreadsheet

### ISSUE THREAD

**Issue by jaxnz** [pnp/pnpjs#2163] opened 2022-03-18 06:19 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.13.0

Please specify what version(s) of SharePoint you are targeting: Online

### Expected / Desired Behavior / Question
Create an empty new excel document.

### Observed Behavior
Creating new word document - Works fine
```
web.getFolderByServerRelativeUrl(relativePath).files.add('test.docx', '', true).then(async doc => {
  window.open(doc.data.LinkingUri + '?web=1', '_blank');
});

```

Creating an excel document - creates a .xlsx file, but does not open correctly in new window, or if I go into the Document Library and open directly.
```
web.getFolderByServerRelativeUrl(relativePath).files.add('test.xlsx', '', true).then(async doc => {
  window.open(doc.data.LinkingUri + '?web=1', '_blank');
});

```

Not sure if this is actually possible, or do I need to use a xlsx template?

**Comment by koltyakov** [comment] 2022-03-18 07:37
Hi there,

This is definitely not a bug.

There are 2 problems with that approach:
- SharePoint requires files containing some content, a zero-length file can't be uploaded
- Office apps not necessarily ok with empty body and expect Open XML bare minimal content

So, document library templates are better be used. Or a default empty Excel content fetched and passed somehow.

**Comment by jaxnz** [comment] 2022-03-19 01:49
Can pnpjs add a way to create documents easier?

For .NET there is [CreateDocumentAndGetEditLink](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/mt796220(v=office.15)) which is the official way used in Document Libraries, but there is nothing equivalent in Javascript/Typescript

**Comment by juliemturner** [comment] 2022-03-19 19:32
There are libraries for javascript/typescript that do this already and it would not be something we would roll into the library since there is and it's really something we consider in scope

**Comment by jaxnz** [comment] 2022-03-21 01:40
Hi Julie,
 
Sorry – could you please reference the libraries that do this?

**Comment by juliemturner** [comment] 2022-03-21 12:13
Not without spending time searching in google, it's been too long and I can't remember names off the top of my head.

**Comment by patrick-rodgers** [comment] 2022-03-23 20:04
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2022-03-23 20:04 UTC
Labels: type: question, status: answered, area: code
