### ISSUE TITLE
Internal SP roundtrips for batchings

### ISSUE THREAD

**Issue by nikolaiessel** [pnp/pnpjs#2686] opened 2023-05-19 08:09 UTC
### Category
- [x] Enhancement

### Version
Please specify what version of the library you are using: 3.15.0
Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question
Maybe internal SP roundtrips required for callees operations can be bundled into a batch before the batch.

### Observed Behavior
Batching does work after fixing #2668. A sideeffect of the solution is, that the internal roundtrips are executed in single requests.
E.g. the moveByPath example of the previous ticket:

![image](https://github.com/pnp/pnpjs/assets/12515305/7e78ad50-3729-4968-8ccd-d47a8697aea5)

**Comment by patrick-rodgers** [comment] 2023-05-19 11:05
The problem is those call's return values are used in subsequent calls. Such as getting the file paths or other details. I am not sure how it could work to auto-batch everything. As well, each request is its own thing - they aren't aware of each other.

**Comment by bcameron1231** [comment] 2023-05-19 16:41
I suppose if you already  had the server relative URLs, we could come up with a way to handle it without having to make the internal calls (like how we do ListItemEntityTypes)?

**Personally, if I need to batch move a lot of files... I would use a different endpoint for this.** I would use the /_api/site/CreateCopyJobs endpoint, which is the one that Microsoft Uses out of the box in their own libraries. There are methods that you can use our internal methods to make your own calls against SharePoint. 
```
import { spfi, SPQueryable, spPost } from "@pnp/sp";
import "@pnp/sp/presets/all";

 const sp = SPQueryable("https://tenant.sharepoint.com/sites/sitename/_api/siteName/CreateCopyJobs").using(spfx?, spbrowser?).
 
 //This call passes in the sources (exportObjectUris) and destinations, and will return a set of results back. 
 var moveResults = await spPost(sp,body({
            exportObjectUris: ["https://tenant.sharepoint.com/sites/sitename/Files2/Document1.docx","https://tenant.sharepoint.com/sites/siteName/Files2/Document2.docx"],
            destinationUri:"https://cameroncode.sharepoint.com/sites/siteName/Files",
            options:{
                IgnoreVersionHistory:true,
                IsMoveMode:true,
                IncludeItemPermissions:false,
                AllowSchemaMismatch:true,
                BypassSharedLock:true,
                SameWebCopyMoveOptimization:true
            }
        }));
```
The above call will return an array of result objects for each file being moved. You can then call another endpoint called _api/site/GetCopyJobProgress and pass in each result object to get the progress back.

```
 const sp2 = SPQueryable("https://tenant.sharepoint.com/sites/sitename/_api/siteName/GetCopyJobProgress").using(spfx?, spbrowser?);
 
 //do some processing logic? While condition? Whatever.
   results.forEach(async (result)=>{
          var progress = await spPost(sp3, body({
              copyJobInfo:{
                 ...result
              }
          }));
      })               

```

**Comment by patrick-rodgers** [comment] 2023-05-19 19:26
@bcameron1231 - Good candidate to add to the library? Nice work!

**Comment by bcameron1231** [comment] 2023-05-19 19:43
I'm not sure. Technically, it's deprecated (even though Microsoft still uses it) as Graph Move/Copy is the preferred API for moving documents. I only recommended it in this instance because OP is working with SharePoint contexts already, and it would handle the batch.

We do have support for the Graph methods though.
https://pnp.github.io/pnpjs/graph/onedrive/#move-drive-item
https://pnp.github.io/pnpjs/graph/onedrive/#copy-drive-item

**Comment by nikolaiessel** [comment] 2023-05-22 06:45
`The problem is those call's return values are used in subsequent calls.`
My initial idea was something like: each query has a 2 references to batches, for external and internal. If a query needs a roundtrip, it could check if it is part of a batch and adds itself to the internal one (which must be awaited if already running).
But when the internal batch will be started?
A second idea does maybe not work with the current structure: the internal batches could work like some games had done. All requests are collected in 100ms timeframes and then send all together while the collection for the next send starts. Maybe the internal batch can start itself a timer when it is created and send itself when it is elapsed

`I suppose if you already had the server relative URLs`
Yes, the file-/folder metadata were fully requested from SP before

`I would use a different endpoint for this`
Nice, thank you - didn´t know it. Since a while I first looking in pnpjs / pnp core sdk for endpoints, instead of MS documentation itself :D

`Technically, it's deprecated`
Yes, but all this stuff works as long as SPO heavily bases on legacy SP. Like the SPFx Asset-XML provisioning and the reason why SPO deflivers old versions of a SPFx extension after update: the legacy documentation notes for a required restart of SP after an update :D

**Comment by bcameron1231** [comment] 2023-05-22 15:29
We'll talk internally on if we want to make updates to this. We're unsure at this point how often file batching is used in the library (like you're using it) and we want to make sure we're investing in the right areas. We do have some thoughts where we may be able to improve this experience. Thanks for the feedback.

**Comment by patrick-rodgers** [comment] 2023-06-16 19:55
Going to close this as the initial question is answered. We'll consider the ideas presented for the future. Thanks!

**Closed by patrick-rodgers** 2023-06-16 19:55 UTC
Labels: status: details needed, area: code
