### ISSUE TITLE
keyFactory in Caching() function is ignored

### ISSUE THREAD

**Issue by erkanch** [pnp/pnpjs#2413] opened 2022-09-29 21:43 UTC
### Category
- [ ] Bug

### Version

Please specify what version of the library you are using: 3.7.0

Please specify what version(s) of SharePoint you are targeting: 1.15.0

### Expected / Desired Behavior / Question
keyFactory should let you control the cache key

### Observed Behavior
keyFactory is ignored.

### Steps to Reproduce
Add using(Caching()) to your SPFI object. The data is cached using a hash like 1147296254 instead of using your custom cache key.
sp.using(Caching({
      store: "local",
      expireFunc: (url) => Config.CacheTimers.DEFAULT,
      keyFactory: (url) => "myCacheKey" + getHashCode(query + url)
    }))
.search({
        QueryTemplate: `${query} AND (NOT IsAudienceTargeted:true OR ModernAudienceAadObjectIds:{User.Audiences})`,
});

init?.headers["X-PnP-CacheKey"] is overriding the keyFactory provided:
https://github.com/pnp/pnpjs/blob/4c88e93613d65e9b2e3c114c2f5136433fa206f6/packages/queryable/behaviors/caching.ts#L48

**Comment by patrick-rodgers** [comment] 2022-09-30 16:12
This is by design - let me explain a bit more. Our default caching hashes the url 

```TS
```

**Comment by erkanch** [comment] 2022-09-30 16:55
Hi @patrick-rodgers. Perhaps we could add an optional flag to ICachingProps (e.g. overrideDefaultKeyFactory?:boolean) so it wouldn't be a breaking change for others. This flag can then override init.headers["X-PnP-CacheKey"].

**Comment by patrick-rodgers** [comment] 2022-09-30 17:33
~You can do that today by using [CacheKey](https://pnp.github.io/pnpjs/queryable/behaviors/#cachekey) behavior.~ Well I thought you could, but now that I tried it that doesn't work because we always honor any init passed into the operation over init from the handlers. Let me see what we can improve here.

**Comment by patrick-rodgers** [comment] 2022-09-30 18:57
Ok, going to check in a change Monday that will be in the next version that will ensure using the CacheKey behavior sets the key. Then you can use your logic, and that behavior to set it per request. I get this is a workaround but allows you to set your own cache key for search and should be the only place currently in the library that it is needed. You code would end up something like:

```TS
import { spfi } from "@pnp/sp";
import "@pnp/sp/search";
import { CacheKey, Caching } from "@pnp/queryable";

await spfi(sp).using(Caching({
    store: "local",
    expireFunc: (url) => Config.CacheTimers.DEFAULT,
  }),
    CacheKey(`myCacheKey ${getHashCode(query)}`)).search({
      QueryTemplate: ${ query } AND(NOT IsAudienceTargeted: true OR ModernAudienceAadObjectIds: { User.Audiences }),
  });
```

**Comment by erkanch** [comment] 2022-09-30 21:22
Thanks!

**Closed** 2022-10-03 13:01 UTC
Labels: status: in progress, type: discussion, area: code
