### ISSUE TITLE
renderListDataAsStream returns no items (probably due to threshold problems)

### ISSUE THREAD

**Issue by mdissel** [pnp/pnpjs#2778] opened 2023-09-11 09:02 UTC
### What version of PnPjs library you are using

3.x

### Minor Version Number

14

### Target environment

SharePoint Framework

### Additional environment details

SPFX Webpart showing a list folders

### Question/Request

Fetch folders from a specific folder in the a doclib. The folders contains 10 folders and 15.000 files.

```
renderListDataAsStream(
{
	ViewXml: `
		<View>
			<RowLimit Paged='TRUE'>2500</RowLimit>
			<Query>
				<OrderBy Override='TRUE'><FieldRef Name='ID'/></OrderBy>
				<Where><Eq><FieldRef Name='FSObjType' /><Value Type='Integer'>1</Value></Eq></Where>
			</Query>
			<ViewFields>
				<FieldRef Name='FileLeafRef' />
				<FieldRef Name='FolderChildCount' />
				<FieldRef Name='ContentTypeId' />
				<FieldRef Name='ProgId' />
				<FieldRef Name='UniqueId' />
			</ViewFields>
		</View>`,
		FolderServerRelativeUrl: doclib.folderPath,
		DatesInUtc: true,
		Paging: "Paged=TRUE&ix_Paged=TRUE&ix_ID=0&PageFirstRow=0"
}
)
```

Returns an empty Row object, instead of returning 10 items. I tried all kind of different Paging string values (and empty), but no difference

![image](https://github.com/pnp/pnpjs/assets/126084/65f21b98-bebc-4b32-8f2f-da85fd484b90)

**Comment by bcameron1231** [comment] 2023-09-13 12:34
I've been trying to reproduce your issue but I am unable to. If it was a threshold issue, I would expect the ListViewThreshold error to appear, not an empty array.

I created a list with 5300 Folders in it. I copied your CAML query and used the same call (except for folder serverrelativeurl, just used root.) When I put a 2500 row-limit, the query works for me.

![image](https://github.com/pnp/pnpjs/assets/7944457/8e19857c-6717-4ff4-93ba-2a8659bc0b10)

```
const renderListDataParams: any = {
    ViewXml: `<View>
			<RowLimit Paged='TRUE'>2500</RowLimit>
			<Query>
				<OrderBy Override='TRUE'><FieldRef Name='ID'/></OrderBy>
				<Where><Eq><FieldRef Name='FSObjType' /><Value Type='Integer'>1</Value></Eq></Where>
			</Query>
			<ViewFields>
				<FieldRef Name='FileLeafRef' />
				<FieldRef Name='FolderChildCount' />
				<FieldRef Name='ContentTypeId' />
				<FieldRef Name='ProgId' />
				<FieldRef Name='UniqueId' />
			</ViewFields>
		</View>`,
		DatesInUtc: true,
		Paging: "Paged=TRUE&ix_Paged=TRUE&ix_ID=0&PageFirstRow=0",
};
// render list data as stream
const r = await sp.web.lists.getByTitle("Test Documents").renderListDataAsStream(renderListDataParams);
```
![image](https://github.com/pnp/pnpjs/assets/7944457/5b0aeb1b-452a-4ad6-a488-7792227f34c4)

As we're just a proxy for the REST API, there may be something else at play here. Your query is searching inside this folder /sites/5644/5644100/Email. Do all your folders exist here?

**Comment by mdissel** [comment] 2023-09-17 09:50
See https://github.com/SharePoint/sp-dev-docs/issues/4621, seems a similar problem 

>  Your query is searching inside this folder /sites/5644/5644100/Email. Do all your folders exist here?

No, more folders exists in the root.

**Comment by juliemturner** [comment] 2023-09-17 14:03
Given the problems noted in sp-dev-docs that implies there is probably some sort of issue with the endpoint itself, ergo we're probably not going to be more help than contributing too/following the issue in sp-dev-docs, although to participate in that conversation you'd have to be making the calls without the library. It's telling that @bcameron1231 doesn't have the problem if he points to the root. Not saying that solves your issue, just saying it's interesting factoid.

**Comment by mdissel** [comment] 2023-09-18 13:30
Ok, thanks! It is just strange that we don't get the threshold exception back, but just 0 records

**Comment by patrick-rodgers** [comment] 2023-09-18 14:33
Have you tried " RenderOptions: 2,"? Views usually aren't defined at the folder level so I am not certain this method supports the query in the way you believe it should.

**Comment by mdissel** [comment] 2023-09-21 08:39
No difference when I use RenderOptions: 2, no rows are returned..

**Comment by juliemturner** [comment] 2023-09-25 14:17
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Closed by juliemturner** 2023-09-25 14:17 UTC
Labels: type: question, status: answered, area: non-library, area: coding request
