### ISSUE TITLE
@pnp/graph Post method missing

### ISSUE THREAD

**Issue by lworkman** [pnp/pnpjs#527] opened 2019-03-02 00:11 UTC
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version
1.2.8

### Expected / Desired Behavior / Question

Some endpoints on `graph.microsoft.com` require you to send a `POST` request to pass in parameters and return data, such as [`/getMemberObjects`](https://docs.microsoft.com/en-us/graph/api/user-getmemberobjects?view=graph-rest-1.0).

When manually constructing a query using `.concat`, the only exposed method is `.get()`, which takes a `FetchOptions` object but ignores the passed in `method` prop.

Ideally, there would be a `.post()` equivalent to `.get()` or, at the very least, `.get()` would respect the passed in `FetchOptions` object.

### Observed Behavior
Manually constructed graph requests cannot be sent as `POST` requests.

**Comment by patrick-rodgers** [comment] 2019-03-04 14:10
This is by design and we will not be changing it in this version of the library. However, we are making changes in 2.0 that will support this scenario. Within the 1.x versions you can add a method to access the protected post - OR since this is JavaScript at the end of the day you can cast it to any and call .post().

I'll add the roadmap tag to this item in case others run into the same thing. This is also similar/duplicate of #285.

**Comment by lworkman** [comment] 2019-03-04 16:19
Okay, I'll stick to my current workaround and keep an eye out for 2.0. Thanks!

**Closed** 2019-11-01 13:48 UTC
Labels: Roadmap, [v2] Done
