### ISSUE TITLE
Having issues bundling this with webpack

### ISSUE THREAD

**Issue by simkessy** [pnp/pnpjs#254] opened 2018-09-22 21:25 UTC
Hi, I'm trying to bundle only the rollup library @pnp/sppn:

`require("@pnp/pnpjs");`

But I just get an error: 

![image](https://user-images.githubusercontent.com/5871660/45921820-ece7db80-be71-11e8-870f-8da6c5e29bca.png)

My webpack file looks like this: 

```
module.exports = {
    mode: "development",
    entry: {
        frb: "./src/app/loader.js"
    },
    output: {
        path: path.resolve(__dirname, "./src/lib"),
        filename: "bundle.js"
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /(node_modules)/,
                loader: "babel-loader",
                query: {
                    presets: [
                        [
                            "@babel/preset-env",
                            {
                                targets: {
                                    chrome: "58",
                                    ie: "9"
                                }
                            }
                        ]
                    ]
                }
            }
        ]
    },
    plugins: [
        // Ignore all locale files of moment.js
        new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
        new webpack.ProvidePlugin({
            moment: "moment"
        })
    ]
};
```
Looking at the [documentation](https://github.com/pnp/pnpjs/blob/ae7ee2db75b044c6751403ee835a849e563cb9b1/packages/documentation/deployment.md) on deployment: 

**If you have installed the library via NPM into your application solution bundlers such as webpack can bundle the PnPjs libraries along with your solution. This can make deployment easier, but will increase the size of your application by the size of the included libraries. The PnPjs libraries are setup to support tree shaking which can help with the bundle size.**

But doesn't really show how to do it. 

In the document on the [package](https://pnp.github.io/pnpjs/pnpjs/docs/) itself just says browse to the folder and grab the file? 

Am I missing something?

**Comment by koltyakov** [comment] 2018-09-23 08:05
Looks that you have PnP packages with different versions. Please check if in `./node_modules/@pnp` all the packages have exactly the same versions.
If no, try to remove `./node_modules` and `package-lock.json`, verify dependencies in `package.json` to have a single `@pnp/pnpjs` or separate peer dependencies with identical versions numbers and run `npm install`.

**Comment by simkessy** [comment] 2018-09-23 20:31
What do I need to install if I just want to use @pnp/pnpjs? 

Because I did `npm i @pnp/pnpjs` and my bundling returns these errors: 

```
ERROR in ./node_modules/@pnp/config-store/dist/config-store.es5.js
Module not found: Error: Can't resolve '@pnp/common' in '\node_modules\@pnp\config-store\dist'

ERROR in ./node_modules/@pnp/graph/dist/graph.es5.js
Module not found: Error: Can't resolve '@pnp/common' in '\node_modules\@pnp\graph\dist'

ERROR in ./node_modules/@pnp/sp-addinhelpers/dist/sp-addinhelpers.es5.js
Module not found: Error: Can't resolve '@pnp/common' in 'C:
```

My Package: 

```
  "dependencies": {
        "@pnp/pnpjs": "^1.2.1",
```

My Lock: 
```

        "@pnp/config-store": {
            "version": "1.2.1",
            "resolved": "https://registry.npmjs.org/@pnp/config-store/-/config-store-1.2.1.tgz",
            "integrity": "sha512-5qPLvKrT6jWpJvyrwMGkxx9SR9rKq1TGaZc8R7AGtqDxXwy8EYkCmPruKr6dwe/bwCnd/B8nHf/8UK0AxN7hgw==",
            "requires": {
                "tslib": "1.9.3"
            }
        },
        "@pnp/graph": {
            "version": "1.2.1",
            "resolved": "https://registry.npmjs.org/@pnp/graph/-/graph-1.2.1.tgz",
            "integrity": "sha512-XPm8KqbQBCo7VUfhtJMPIz/vorgpZVC9V87OTcToNlw6yUSMIqk3Wrph4Tz4gVo8YKNtQDe7t9wbJCCru2Z94g==",
            "requires": {
                "@microsoft/microsoft-graph-types": "1.3.0",
                "tslib": "1.9.3"
            }
        },
        "@pnp/pnpjs": {
            "version": "1.2.1",
            "resolved": "https://registry.npmjs.org/@pnp/pnpjs/-/pnpjs-1.2.1.tgz",
            "integrity": "sha512-+lS/LXQDkGxrilnD9L0CHKXYoPmpMporllA2MMjrbnLfG8FBZXFfligA/5UF5xXJrrxGZMPHXk3dBi5QAf3cRA==",
            "requires": {
                "@pnp/common": "1.2.1",
                "@pnp/config-store": "1.2.1",
                "@pnp/graph": "1.2.1",
                "@pnp/logging": "1.2.1",
                "@pnp/odata": "1.2.1",
                "@pnp/sp": "1.2.1",
                "@pnp/sp-addinhelpers": "1.2.1",
                "tslib": "1.9.3"
            },
            "dependencies": {
                "@pnp/common": {
                    "version": "1.2.1",
                    "resolved": "https://registry.npmjs.org/@pnp/common/-/common-1.2.1.tgz",
                    "integrity": "sha512-cWyz8W1mq1Q7GO+Q6/RghRheYUFgNqjEEn7SDXUsUqnIu9+ZjQ8b36USRmKTFUY9p0nRPe+Ig7/Vu3oc/dMbyQ==",
                    "requires": {
                        "adal-angular": "1.0.17",
                        "tslib": "1.9.3"
                    }
                },
                "@pnp/logging": {
                    "version": "1.2.1",
                    "resolved": "https://registry.npmjs.org/@pnp/logging/-/logging-1.2.1.tgz",
                    "integrity": "sha512-VCEcqaqH+g5PQ0OOJv8UpD797BZnmy1ENmApRaLFAD/+SHnu8Xc/I6G3/BA/zivbmwZnPstOmLR4r49an+pQDw==",
                    "requires": {
                        "tslib": "1.9.3"
                    }
                },
                "@pnp/odata": {
                    "version": "1.2.1",
                    "resolved": "https://registry.npmjs.org/@pnp/odata/-/odata-1.2.1.tgz",
                    "integrity": "sha512-iNJy4QZMcD8CjTWtBasEf+LgWNQ1Q4K1g4KpfjEPScWY4QaV2/pjkM/NbRzbUc1zrfgREu13d+ZIiB45/setsQ==",
                    "requires": {
                        "tslib": "1.9.3"
                    }
                },
                "@pnp/sp": {
                    "version": "1.2.1",
                    "resolved": "https://registry.npmjs.org/@pnp/sp/-/sp-1.2.1.tgz",
                    "integrity": "sha512-HfM6g0CIilENpRD2QG8oL0cEsyWK7ZKAKUJOxvrZ5A3EG/vJDxBhCWWUrjKK/7t7/Si/b44Mpnb622fPr5XKHw==",
                    "requires": {
                        "tslib": "1.9.3"
                    }
                }
            }
        },
        "@pnp/sp-addinhelpers": {
            "version": "1.2.1",
            "resolved": "https://registry.npmjs.org/@pnp/sp-addinhelpers/-/sp-addinhelpers-1.2.1.tgz",
            "integrity": "sha512-tE79M7RzRsEohiPNNdgxTERC6NNOSdF2ziaHXZGHDITyhdfLEbWwCwZ0TyCAWl+wxcYgtNOrKNFvwWUhYVF6Iw==",
            "requires": {
                "@types/sharepoint": "2013.1.9",
                "tslib": "1.9.3"
            }
        },

```

**Comment by simkessy** [comment] 2018-09-23 20:45
I reset my packages / dependencies. It bundles without warnings / errors now. 

My loader.js file looks like this: 

```
require("expose-loader?moment!moment");
require("lodash");
require("materialize-css");
require("script-loader!datatables.net");
require("script-loader!select2");
import $pnp from "@pnp/pnpjs";

```
But when I load my page I get: 

![image](https://user-images.githubusercontent.com/5871660/45932793-d48dc480-bf36-11e8-849e-6f70f82b2aa1.png)

**Comment by koltyakov** [comment] 2018-09-23 21:16
Can't reproduce. The bundled code just works fine for me. Yet, using ts-loader and config from a generator.
Can you create a repo with a bare minimum setup which fails for you to test on? I know that you specified webpack config and the way you import, but it would be really great just to clone, npm install and check. Would be a real timesaver. Thanks!

**Comment by patrick-rodgers** [comment] 2018-10-12 23:23
Going to close this as answered. Please do _reopen_ if that is not the case so we can ensure things are working for you. Thanks!

**Closed by patrick-rodgers** 2018-10-12 23:23 UTC
Labels: area: package, status: details needed

**Comment by simkessy** [comment] 2019-03-14 00:52
Hey, 

I'm trying this again and still can't seem to get bundling to work. 

```
// pnpjs
require("@pnp/pnpjs");

var webpack = require("webpack");
var path = require("path");

module.exports = {
    mode: "production",
    devtool: "",

    // entry: ["whatwg-fetch", "@babel/polyfill", "./src/app/loader.js"],
    entry: {
        main: ["whatwg-fetch", "@babel/polyfill", "./src/build/loader.js"]
    },
    output: {
        path: path.resolve(__dirname, "/build/"),
        filename: "bundle.js"
    },
    optimization: {
        minimize: true
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /(node_modules)/,
                loader: "babel-loader",
                query: {
                    presets: [
                        [
                            "@babel/preset-env",
                            {
                                useBuiltIns: "entry",
                                targets: {
                                    ie: "9"
                                }
                            }
                        ]
                    ]
                }
            }

            // {
            //     test: /\.(scss|sass)$/,
            //     use: [
            //         {
            //             loader: "css-loader",
            //             options: {
            //                 modules: true,
            //                 importLoaders: 1,
            //                 localIdentName: "[hash:base64:10]",
            //                 sourceMap: false
            //             }
            //         },
            //         {
            //             loader: "sass-loader"
            //         },
            //         {
            //             loader: "postcss-loader"
            //         }
            //     ]
            // }
        ]
    },
    externals: {
        $: "jquery",
        jQuery: "jquery"
    }
};

```

> Uncaught (in promise) ReferenceError: pnp is not defined
