### ISSUE TITLE
After installed npm install @pnp/sp @pnp/graph --save

### ISSUE THREAD

**Issue by pmeripe** [pnp/pnpjs#1045] opened 2020-02-01 00:00 UTC
Created a new project with React and installed PnPJs 2.0, and i get below errors.

[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(115,62): error TS1109: Expression expected.
[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(115,81): error TS1109: Expression expected.
[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(115,90): error TS1005: ';' expected.
[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(115,105): error TS1005: '(' expected.
[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(121,28): error TS1005: ',' expected.
[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(121,37): error TS1005: ';' expected.
[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(121,52): error TS1005: '(' expected.
[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(122,1): error TS1128: Declaration or statement expected.
[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(125,33): error TS1005: ',' expected.
[18:42:18] Error - [tsc] node_modules/@pnp/sp/webs/types.d.ts(125,85): error TS1005: '(' expected.

**Comment by patrick-rodgers** [comment] 2020-02-01 01:09
What version of SPFx are you using? Does [this article](https://pnp.github.io/pnpjs/SPFx-on-premises/) help?

**Comment by pmeripe** [comment] 2020-02-01 01:18
Patrick,
Even while checking SPFx version i get these errors.

npm -g ls --depth=0
C:\Users\pmeripe\AppData\Roaming\npm
+-- @microsoft/generator-sharepoint@1.8.0
+-- @pnp/office365-cli@1.12.0
+-- create-react-app@3.2.0
+--  error: ENOENT: no such file or directory, stat 'C:\Users\pmeripe\AppData\Roaming\npm\node_modules\get-sp-list-data
+-- gulp@4.0.2
+-- tslint@5.12.1
+-- UNMET PEER DEPENDENCY typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev
`-- yo@3.1.1

npm ERR! peer dep missing: typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev, required by tslint@5.12.1
npm ERR! error in C:\Users\pmeripe\AppData\Roaming\npm\node_modules\get-sp-list-data: ENOENT: no such file or directory, stat 'C:\Users\pmeripe\AppData\Roaming\npm\node_modules\get-sp-list-data'
npm ERR! peer dep missing: typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev, required by tsutils@2.29.0

Thanks.

**Comment by pmeripe** [comment] 2020-02-02 01:45
> What version of SPFx are you using? Does [this article](https://pnp.github.io/pnpjs/SPFx-on-premises/) help?

Package                              Current  Wanted  Latest  Location
@microsoft/rush-stack-compiler-2.7     0.4.0   0.4.0   0.9.3  submittal-form
@microsoft/sp-build-web                1.8.0   1.8.0  1.10.0  submittal-form
@microsoft/sp-core-library             1.8.0   1.8.0  1.10.0  submittal-form
@microsoft/sp-lodash-subset            1.8.0   1.8.0  1.10.0  submittal-form
@microsoft/sp-module-interfaces        1.8.0   1.8.0  1.10.0  submittal-form
@microsoft/sp-property-pane            1.8.0   1.8.0  1.10.0  submittal-form
@microsoft/sp-tslint-rules             1.8.0   1.8.0  1.10.0  submittal-form
@microsoft/sp-webpart-base             1.8.0   1.8.0  1.10.0  submittal-form
@microsoft/sp-webpart-workbench        1.8.0   1.8.0  1.10.0  submittal-form
@types/chai                           3.4.34  3.4.34   4.2.8  submittal-form
@types/es6-promise                    0.0.33  0.0.33   3.3.0  submittal-form
@types/mocha                          2.2.38  2.2.38   7.0.1  submittal-form
@types/webpack-env                    1.13.1  1.13.1  1.15.1  submittal-form
ajv                                    5.2.5   5.2.5  6.11.0  submittal-form
gulp                                   3.9.1   3.9.1   4.0.2  submittal-form

**Comment by patrick-rodgers** [comment] 2020-02-03 15:49
Can you provide detailed reproduction steps? I am not able to reproduce this with the information you have provided as you ignored the template.

**Comment by pmeripe** [comment] 2020-02-03 17:07
Patrick,
Created a new project with react framework, installed PnPJs v2 and @pnp/spfx-controls-react. I have created all projects in C: drive. Yesterday I tried to create a project in C:\\users\user\spfx\project and working without any issues after I installed latest PnPJs. I am not sure what exactly causes the problem. Let me know if you need any more information.
Thanks.

**Comment by patrick-rodgers** [comment] 2020-02-04 16:26
So it sounds like you have a working project and everything is OK now? Perhaps that other project was corrupted somehow?

I am unable to reproduce this and don't have any other reports at this time so it leans towards something local in your environment. If new projects work fine then you are probably OK and the problem project has some other issue.

**Comment by patrick-rodgers** [comment] 2020-02-11 13:56
Going to close this as it sounds like things are working. If you continue to have issues please open a new issue, ref this one, and provide any additional details you can. Thanks!

**Closed by patrick-rodgers** 2020-02-11 13:56 UTC
Labels: area: non-library, status: details needed, type: question
