### ISSUE TITLE
Argument of type 'ApplicationCustomizerContext' is not assignable to parameter of type 'ISPFXContext'.

### ISSUE THREAD

**Issue by martinlingstuyl** [pnp/pnpjs#2334] opened 2022-06-29 08:29 UTC
This may be related to #2329 
The workaround mentioned there is okay for me currently as I'm not using the graph.

### Category
- [ ] Enhancement
- [x] Bug  
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [3.4.1]

Please specify what version(s) of SharePoint you are targeting: [SPO SPFx 1.15.0]

### Expected / Desired Behavior / Question
I should be able to create a pnp.js Factory instance from an Application Customizer SPFx extension using:
```typescript
const spfi = spfi().using(SPFx(this.context); //type of context: ApplicationCustomizerContext
```

### Observed Behavior
I get a typing error:
Argument of type 'ApplicationCustomizerContext' is not assignable to parameter of type 'ISPFXContext'.

### Steps to Reproduce
-Create a new SPFx Application Customizer
-Install @pnp/sp
-Add the above code in the onInit method.

**Comment by patrick-rodgers** [comment] 2022-06-29 12:27
You can type it as "any" as a work around, we'll have an update in the next version. They changed the signature of a method on the context in a breaking way between versions. It turns out to be a method we don't use so we'll just take it off our interface. Thanks.

**Comment by juliemturner** [comment] 2022-06-29 13:52
I'm going to close this issue as a duplicate of #2329 .

**Closed by juliemturner** 2022-06-29 13:52 UTC
Labels: status: duplicate
