### ISSUE TITLE
spfxContext web incorrect when browser has no trailing slash

### ISSUE THREAD

**Issue by jacobhummel** [pnp/pnpjs#144] opened 2018-06-20 15:04 UTC
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

v1.1.1

### Expected / Desired Behavior / Question

404 on list call when using the inferred web url only if there is no trailing slash.

I established the context in the onInit function
```
export default class BillboardWebPart extends BaseClientSideWebPart<IBillboardWebPartProps> {
  public onInit(): Promise<void> {
    return super.onInit().then(_ => {
      pnpSetup({
        spfxContext: this.context,
      });
    });
  }
```
And then use the standard list call in a component.
```
const billboardItems: IBillboardItem[] = await sp.web.lists
      .getByTitle('billboard').items.get();
```

I expect to be able to retrieve my list items on the 'billboard' list on my current site.

### Observed Behavior

This works if I'm on my site with a trailing slash on the end:
`https://contoso.sharepoint.com/sites/MySite/`

Does not work when I have no trailing slash on the end:
`https://contoso.sharepoint.com/sites/MySite`

`GET https://contoso.sharepoint.com/sites/_api/web/lists/getByTitle('billboard')/items 404 ()`

I can work around this issue by manually setting the web before making calls:

```
const web: Web = new Web(this.props.context.pageContext.web.absoluteUrl);
const billboardItems: IBillboardItem[] = await web.lists
      .getByTitle('billboard').items.usingCaching().get();
```

### Steps to Reproduce

1. Create SPFx component
2. Add pnp setup to onInit function
3. Do a list item get on a site homepage with no trailing slash

**Comment by patrick-rodgers** [comment] 2018-06-20 17:24
Hi @jacobhummel - I am a little confused. Do you mean that in your browser address bar it matters if you have the "/" char or not? If you do nothing, and provide the context to the library (as you show doing above) we return this as the base url, which matches your workaround. Hence my confusion.

`return RuntimeConfig.spfxContext.pageContext.web.absoluteUrl;`

Is there other code around your request? Are you creating a new web instance that is causing the issue (meaning the problem is likely in how we parse urls)?

If possible can you share full sample of the code you are running. Want for sure to fix this, just unsure where to start. Thanks!

**Comment by Sartor87** [comment] 2018-06-21 13:16
I had the same issue.

Just add (you have to include import { sp } from "@pnp/sp";):

`sp.setup({
      spfxContext: this.context
    });`

in your render or init method (depends on the solution).

**Comment by oozoo-solutions** [comment] 2018-06-29 14:29
I get the same thing in an Application Customizer. 
I copied the instructions for Getting Started: SharePoint Framework (https://pnp.github.io/pnpjs/sp/index.html)

The call to get the title for the current web returns a 404, it's not removing the SitePages path from the URL, see below:
https://mytenant.sharepoint.com/sites/modern/SitePages/_api/web?$select=Title

As Jacob points out this can be fixed by using
`const web: Web = new Web(this.context.pageContext.web.absoluteUrl);
web.select("Title").get().then(w => { });`

**Comment by patrick-rodgers** [comment] 2018-06-29 14:40
Can you share your code? Are you invoking requests before the setup method is actually called? I.e. are you doing things in oninit THEN calling setup? This is the most likely cause of this issue.

**Comment by oozoo-solutions** [comment] 2018-07-02 07:33
Thanks @patrick-rodgers I'd put inadvertently put the setup call after the call to the function calling into SP.

**Comment by patrick-rodgers** [comment] 2018-07-09 12:36
I am going to close this due to no response. I can't duplicate this behavior and I think it is likely due to executing some code before the setup method completes. Please _reopen_ if we need to investigate further. Thanks!

**Closed by patrick-rodgers** 2018-07-09 12:36 UTC
Labels: area: code, status: details needed, type: discussion
