### ISSUE TITLE
Save modern page using ClientSidePage interface with some not encoded signs, cause issue with page content

### ISSUE THREAD

**Issue by ruslan-s** [pnp/pnpjs#1690] opened 2021-04-08 13:05 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.3.0, 1.3.11 ]

Please specify what version(s) of SharePoint you are targeting: [ SPO ]

### Expected / Desired Behavior / Question
Get modern page using using _ClientsidePageFromFile_ method, that contains an Text Webpart **below** an QuickLink Webpart. QuickLink Webpart should contains **"1 <2"** string in a link title. Then save the page. 
When open page in a browser, I expect to see a modern page with QuickLink Webpart following by Text Webpart.

`const page = await ClientsidePageFromFile(sp.web.getFileByServerRelativeUrl("/sites/xxx/SitePages/yyy.aspx"));`
`await page.save();`

![image](https://user-images.githubusercontent.com/32303191/114029322-afa19880-9879-11eb-8c7a-03e6e348fa6b.png)

### Observed Behavior
Get modern page using using _ClientsidePageFromFile_ method, that contains an Text Webpart **below** an QuickLink Webpart. QuickLink Webpart should contains **"1 <2"** string in a link title. Then save the page. 
When open page in a browser, I see a modern page with only QuickLink Webpart, that contains a link with the title **"1 "**. Text Webpart and another part of link title are missing.

![image](https://user-images.githubusercontent.com/32303191/114027833-17ef7a80-9878-11eb-97bb-629238c4f62f.png)

### Steps to Reproduce
1. Go to the SP site and create an modern page;
2. Add the QuickLink Webpart at first;
3. Add one link to the webpart with the Title "1 <2";
4. Add Text Webpart to the page and fill it with some text;
5. Publish the page;
6. Get the page with ClientsidePageFromFile() method:
`const page = await ClientsidePageFromFile(sp.web.getFileByServerRelativeUrl("/sites/xxx/SitePages/yyy.aspx"));`
7. Save the page from step 6 with _save_ method on the ClientSidePage interface:
`await page.save()`;
8. Reload browser tab with the page from step 1;

### Note
- We noticed that problem is caused by not encoded signs in the **webPartData.serverProcessedContent.searchablePlainTexts**;
- If we publish the page via SharePoint UI we noticed, that this values will be encoded 
![image](https://user-images.githubusercontent.com/32303191/114030080-79184d80-987a-11eb-9c63-5984e72b8bd2.png)
- If we publish via PnPJS values will be not encoded:
   https://github.com/pnp/pnpjs/blob/83f178d4af61c6b2fa926bef24ae4c65c1c5c2b0/packages/sp/clientside-pages/types.ts#L764
- We also noticed, if the user use "1 < 2" instead of "1 <2", no issue will be happen.

Thank you for your feedback!

**Comment by juliemturner** [comment] 2021-04-09 15:59
@ruslan-s -- first thank you very much for your very through submission.

Both @patrick-rodgers and I tried to repo this and we couldn't with 2.3.0 build. My only concern is that you mention you're using 2.3.0 *and* 1.3.11... which doesn't really make any sense and if true is a problem... you really need to use the same version of the library.

In our testing we do not see that value encoded when we load the page or when we save the page, so that also is a discrepancy in what you reported.  Both of our tenants though are on first-release so I suppose that could have some bearing.

**Comment by nmtoblum** [comment] 2021-04-09 19:30
Hi @juliemturner,

let me jump in. I traced this issue down yesterday together with @ruslan-s.

To make it a bit easier to reproduce, I created a [video](https://user-images.githubusercontent.com/57751598/114228702-22dd0480-9977-11eb-8041-85701d271484.mp4) that shows the relevant steps:
<video src="https://user-images.githubusercontent.com/57751598/114228702-22dd0480-9977-11eb-8041-85701d271484.mp4"></video>

The page is just loaded and directly saved with PnP.js and loaded again:
```javascript
import { sp } from "@pnp/sp/presets/all";

(async () => {

  const page = await sp.web.loadClientsidePage("/sites/teamsite_7/SitePages/Simple-page-with-just-a-quicklinks-and-a-text-web-part.aspx");
  console.log("Number web parts of the page:", page.sections[0].columns[0].controls.length);

  await page.save();

  const page_after = await sp.web.loadClientsidePage("/sites/teamsite_7/SitePages/Simple-page-with-just-a-quicklinks-and-a-text-web-part.aspx");
  console.log("Number web parts of the page:", page_after.sections[0].columns[0].controls.length);

})().catch(console.log);
```

You can see that PnP counts initially three webparts and after saving only two. The page is cut directly at the < symbol in the quicklink title. The SavePage call itself is successful, but everything after that symbol is lost. I'd expect the whole call to fail in such a case, but this is different.  
As Ruslan mentioned, this happens also if e.g. a image web part contains <2 in the caption. And I guess that there are more web parts affected.

We checked the HTTP calls made by PnP.js and SharePoint, when saving the page:
![SavePage_call_diff](https://user-images.githubusercontent.com/57751598/114229550-494f6f80-9978-11eb-86d3-93936a7e10d8.png)

You can see that SharePoint HTML-encodes the fields below "searchablePlainTexts" while PnP.js doesn't and just sends back what it received from SharePoint when loading the page (which also looks conclusive to me).

I look forward to your assessment of the behavior.

Greetings
Tobias

**Comment by ruslan-s** [comment] 2021-04-20 06:29
@juliemturner @patrick-rodgers  Do we have here any updates? Should i provide some new details or is @nmtoblum and my explanation is already enough?

**Comment by patrick-rodgers** [comment] 2021-04-20 19:10
I have been quite busy and not had a chance to circle back to this or any of the other issues. It remains open and we'll have a look once we get a chance. If we have additional questions then we'll be sure to ask. Thanks!

**Comment by ruslan-s** [comment] 2021-04-21 07:52
@patrick-rodgers Thank you for your response!

**Comment by toblum** [comment] 2021-04-30 10:22
Hi @patrick-rodgers,

thanks for coming back to this. It's really strange that you were not able to reproduce it. I tested on five different tenants (some with early release enabled, some not, my developer tenant, on customer tenants and even created a fresh demo tenant) and this happens on all of these. Also tried with communication and team sites.

To be 100 % sure: you used "test <2 test" as quicklinks title or a image caption in this page? 
In Maintenance mode the page looks like this:  
![maintenance](https://user-images.githubusercontent.com/18660238/116675912-a56d4880-a9a6-11eb-874a-17e8c167a9d6.png)

If you like, I could invite you to one of these tenants.

I saw that you don't process the contents in pnp.js. I would also expect this to work. But it looks that SharePoint itself encodes these values when it saves the page and I'm unsure if PnP.js should do this too. But when doing this we should be 100 % sure that it should be done this way.

For me it looks like there is some HTML sanitizing happening on server side. Because if I take my test and try the following data, it looks like this:

- test &lt;b&gt;test&lt;/b&gt; test --> test test test
- test &lt;hr/&gt; test --> test &nbsp; test
- test &lt;example&gt; test --> test &nbsp; test
- test &quot; test --> test " test
- test <2 test 2> test --> test &nbsp; test

So SharePoint obviously removes tags and processes HTML-entities. And something like <2 is like a "incomplete" tag so SharePoint removes it (and unfortunately the rest of the page too). This seems to be the reason why SharePoint itself HTMLencodes the contents before it send them back to the server so they stay untouched.

Based on these observations I would say that PnP.js should encode these payloads too but it would be good to get confirmation from Microsoft how this works. I'm unsure how to accomplish that.

Greetings
Tobias

**Comment by patrick-rodgers** [comment] 2021-05-03 19:59
@juliemturner and I worked through this today and were able to get a reproduction. After much discussion we added a special case handling for what is an edge case. We decided that addressing this was important as it caused breaks with no user action, loading and saving a page with no edits shouldn't break the page.

The complexity here is that the fix should only be applied to this one web part and in a very specific way. Which means we had to do something we have been avoiding carefully which is clogging up the client-pages code with special cases. Because there is no documented API for client-side pages we reverse engineered our offering and by design been as thin a wrapper as possible. Truly this is an issue on the server and should be fixed there. If we can't send back the text we get that indicates something else is wrong.

As a general disclaimer we are not looking to add special handling for all of the different web parts. They are all unique, store their data differently, and change without warning.

Thanks @toblum and @ruslan-s for working through this with us. The fix will go out in 2.5.0.

**Comment by toblum** [comment] 2021-05-04 15:21
Hello,

thank you for taking up this topic again. Yes, it is definitely an edge case, but it actually occurs in real life. In our case it was a quicklink with the text "Expenses <100.000 €". I think such cases will be encountered rarely but over and over again, so I think it's good that you are handling the case accordingly now.

What I'm not quite sure about is whether it really only affects a specific web part. I have been able to recreate it at least in image web part captions as well. So my guess would be that this behavior is not limited to specific web parts, but to this field in general. Maybe Microsoft will give us some more detailed information about the way it works in the future.

In any case, I would like to thank you again for your efforts.

Many greetings
Tobias

**Comment by patrick-rodgers** [comment] 2021-05-18 12:31
Closing as fixed, missed closing it with the last release. Thanks!

**Closed by patrick-rodgers** 2021-05-18 12:31 UTC
Labels: area: code, status: complete, type: enhancement
