### ISSUE TITLE
Expand doesn't work with thumbnail field type

### ISSUE THREAD

**Issue by Lelluch** [pnp/pnpjs#1822] opened 2021-07-05 13:24 UTC
### Category
- [x] Question

### Version

Please specify what version of the library you are using: [  ^2.0.2   ]

Please specify what version(s) of SharePoint you are targeting: [ sharepoint online  ]

### Expected / Desired Behavior / Question
Hello! We have two tables, one contains a lookup with ID to the second table.
Table №1
![image](https://user-images.githubusercontent.com/64580162/124471652-cdfa3000-dda5-11eb-8ecb-6396c46dcc68.png)

Which contains a field of type "thumbnail".
Table №2
![image](https://user-images.githubusercontent.com/64580162/124471887-1ade0680-dda6-11eb-8a07-58128f2b0600.png)

There was a need to create a query to table number 1 and get using
```
.select(...['TEST_IDs/test'])
.expand(...['TEST_IDs'])
```
However, expand to the given lookup returned an error
![image](https://user-images.githubusercontent.com/64580162/124472644-09e1c500-dda7-11eb-83f3-b7f32c67f07f.png)

Could you tell me if there is a solution how to get access to the desired lookup?

**Comment by ValerasNarbutas** [comment] 2021-07-08 20:12
Hi @Lelluch 
under the hood your query is like this:
/_api/web/lists/getByTitle('table1')/items?$select=TEST_IDs/test&$expand=TEST_IDs
which i bet is not valid, if you would select ID or title this would work.
My suggestion is have one more colum single line type and store some value from test column, like 'filename'.
thumb/image field store valu as json:
```json
{"type":"thumbnail","fileName":"some.jpg","nativeFile":{},"fieldName":"test","serverUrl":"https://tenant.sharepoint.com","serverRelativeUrl":"/sites/sitename/SiteAssets/Lists/8a8f074b-3408-4bce-9fea-281967e23b0a/some.jpg","id":"uniqueitemid"}
```

when you could use 

```typescript
.select(...['TEST_IDs/newcolumn'])
.expand(...['TEST_IDs'])
```

**Comment by patrick-rodgers** [comment] 2021-07-12 12:41
Hi @Lelluch,

Done some testing and confirmed with the engineering team, image fields don't work with expand/select through lookups. This is by design.

If you can share a bit more about your scenario we can perhaps share some ideas to work around this in your design.

Thanks!

**Comment by a1exymoroz** [comment] 2021-07-17 10:36
HI.
I have the same issue. And I need to get `serverRelativeUrl` via select and expand. Why do I need create another columns for storing some details from `thumbnails`, if we have select and expand. functionality?

Does `Sharepoint API` have a documentation of expand/select functionality?

Because I have the same error with a boolean column. I can't select a boolean column via expand lookup.

**Comment by koltyakov** [comment] 2021-07-17 10:52
These are painful limitations of SharePoint API which have been presenting from the day 1. Might sound strange, but are by design. Unfortunately, in a client library there's nothing to do to workaround but to augment the data structure of an app to support requests scenarios, e.g. replacing a boolean to a number or string, copying a trimmed string from multi to single line field.

**Comment by a1exymoroz** [comment] 2021-07-17 11:07
@koltyakov Thanks for answer. And It is sad😒

And will it never change?

**Comment by koltyakov** [comment] 2021-07-17 11:11
More likely it will never happen as it is deep in the platform's architecture.

**Comment by patrick-rodgers** [comment] 2021-08-03 16:44
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2021-08-03 16:44 UTC
Labels: area: coding request, status: answered, type: question
