### ISSUE TITLE
Exception for item.userHasPermissions, unless user is admin

### ISSUE THREAD

**Issue by IvanToronto** [pnp/pnpjs#2157] opened 2022-03-14 13:51 UTC
### Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     2.4.0    ]

Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
User with contribute access should consistently have userHasPermissions method executed without System.UnauthorizedAccessException.

### Observed Behavior
The console occasionally shows a System.UnauthorizedAccessException unless they are in the Admin Group.
Users in a group with contribute access get an authorized exception when then methods are called

### Steps to Reproduce
item = await sp.web.getFolderByServerRelativeUrl(serverRelativeFolderUrl).getItem();
https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee539339(v=office.15)

await item.userHasPermissions(currentUser.LoginName,PermissionKind.AddListItems);
https://pnp.github.io/pnpjs/sp/permissions/

**Comment by bcameron1231** [comment] 2022-03-16 15:43
Duplicate of #489  It is true, this userHasPermissions is an elevated method meaning you'd need higher permissions to call it.

Could you check the response from koltyakov in that post and see if the workaround helps you?

**Closed** 2022-03-23 17:45 UTC
Labels: type: question, area: code, status: duplicate
