### ISSUE TITLE
Question - using react sp.web opens root site and not current sub web

### ISSUE THREAD

**Issue by luisnjuarez** [pnp/pnpjs#931] opened 2019-11-19 12:25 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     ]
"@pnp/sp": "^1.3.7",
"react": "16.8.5",
"react-dom": "16.8.5"

Please specify what version(s) of SharePoint you are targeting: [    SharePoint Online     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I would like to dynamically find the list in the current context web where the web part has been added.

### Observed Behavior
A web part querying a list in the current web is failing to find the list, because sp.web is always looking at the rootweb

### Steps to Reproduce
Create a new SPFX project using react, package and deploy to a sub web of a site collection

Note: 
I have added the context, but I think I am missing something as it is still failing and I have no idea what else I could do 
I have added the following code in the TSX File
-----
import {IWebPartContext} from '@microsoft/sp-webpart-base';
-----
export default class ProjectDetailsReact extends React.Component<IProjectDetailsReactProps, any> {
  private _context: IWebPartContext;
  public constructor (props:IProjectDetailsReactProps, any)
  {
    super(props);
    this.state={
      items:[]

    };
    this._context = props.context;
    sp.setup({
      spfxContext: this._context
    });
  }
------------
sp.web.lists.getByTitle("Project Details").items.select("Id", "Title")
-------------

Could you please point me in the right direction?

Thank you for your feedback!

**Comment by patrick-rodgers** [comment] 2019-11-20 18:53
Can you share a repo we can clone or a clearer code sample of what you are trying to do? It feels like the issue is with the context. You can also debug and see if the context is pointing to the site you think it is.

**Comment by luisnjuarez** [comment] 2019-11-20 22:15
Hi Patrick,
I found the solution in this issue, greatly appreciated

https://github.com/pnp/pnpjs/issues/514

_

> Yes you are passing in the values from the context to your react component as a Property. That's a good way to do it.
> Don't do that :)
> In the same WebPartName.ts as you just did the render() add a OnInit and do the setup there. Because if you think about it this is where you have the context available, because it's the web parts context, not React context.
> // https://pnp.github.io/pnpjs/documentation/getting-started/#using-pnpsp-setup
> public onInit(): Promise < void> {
>   return super.onInit().then(_ => {
>     sp.setup({
>       spfxContext: this.context
>     });
>   });
> }
> So then it would look like this in your WebPartName.ts:
> public onInit(): Promise < void> {
>   return super.onInit().then(_ => {
>     sp.setup({
>       spfxContext: this.context
>     });
>   });
> }
> public render(): void {
>   const element: React.ReactElement < IDropDownWebPartProps > = React.createElement(
>     DropDownWebPart,
>     {
>       siteUrl: this.context.pageContext.web.absoluteUrl,
>     }
> }

_

**Comment by patrick-rodgers** [comment] 2019-11-21 13:55
Awesome, thanks for letting me know. I will close this issue. If you have any further issues please let us know, thanks!

**Closed by patrick-rodgers** 2019-11-21 13:55 UTC
Labels: area: sample, status: details needed, type: question
