### ISSUE TITLE
ListAddResult with list name containing apostrophe

### ISSUE THREAD

**Issue by jpalo** [pnp/pnpjs#425] opened 2018-12-18 11:51 UTC
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.7.0]

Please specify what version(s) of SharePoint you are targeting: [ONLINE]

### Expected / Desired Behavior / Question
Using _ListAddResult_ after creating list where list name contains apostrophe would contain correctly encoded list name, so that following code would work.

### Observed Behavior
Currently the _url of ListAddResult contains single apostrophe causing highlighted `.expand...` code to fail.

![image](https://user-images.githubusercontent.com/6917905/50152159-94d34080-02cb-11e9-8ea1-9fb56ee38306.png)

### Steps to Reproduce

1. Create list where list name contains apostrophe using the following code where listName is e.g., "Test'4". 
2. Using ListAddResult of sp.web.lists.add contains _url where apostrophes are not correctly duplicated, making the `lar.list.expand `code to fail.

```
      sp.web.lists.add("Test'4", "", 100, false)
        .then((lar: ListAddResult) => {
          lar.list.expand("RootFolder").select("RootFolder/ServerRelativeUrl").get() // throws error
            .then((result) => {
              listUrl = result.RootFolder.ServerRelativeUrl;

```

**Comment by patrick-rodgers** [comment] 2018-12-18 16:18
Closing this as a duplicate of an open issue #313.

**Closed by patrick-rodgers** 2018-12-18 16:18 UTC
Labels: area: code, status: duplicate, type: enhancement
