### ISSUE TITLE
Cannot Select Specific Lookup Column Fields

### ISSUE THREAD

**Issue by Steven-Chorkawy** [pnp/pnpjs#1258] opened 2020-07-07 15:46 UTC
### Category
- [ ] Enhancement
- [x ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.6]

Please specify what version(s) of SharePoint you are targeting: [     Online    ]

### Expected / Desired Behavior / Question
Ability to include all fields from a lookup column. 

### Observed Behavior
I'm only able to include Currenty, and single line of text column types. Yes/No and Calculated column types cannot be included. 

### Steps to Reproduce
1. Have a list that uses a lookup column which has multiple field types.  Text, Currency, Yes/No, and calculated in the lookup column. 

1. Use `sp.web.lists.getByTitle('OGList').items.select('*, LookupColumn/TextFIeld, LookupColumn/CurrencyField, LookupColumn/YesNoField, LookupColumn/CalculatedField ').expand('LookupColumn').get().then();`

Here is my exact code: 
`let arInvoices = await sp.web.lists.getByTitle('Ar Invoices')
    .items
    .select(`*, FileRef,
    Customer/Title,
    AccountDetails/Account_x0020_Code,
    AccountDetails/Amount,
    AccountDetails/HST_x0020_Taxable,
    AccountDetails/HST,`)
    .expand('Customer, AccountDetails')
    .get();`

1. When I run the previous line I get the following error
![image](https://user-images.githubusercontent.com/65408672/86806687-183bba80-c047-11ea-9720-18676de73af4.png)

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in seperate issues so we can track resolution.

Thank you for your feedback!

**Comment by koltyakov** [comment] 2020-07-07 15:53
That's not a bug, but REST API doesn't provide capability expanding field values for all data types.

**Comment by Steven-Chorkawy** [comment] 2020-07-07 15:55
Thank you for getting back to me. 

Do you know where I can find documentation on which data types are available?

**Comment by koltyakov** [comment] 2020-07-07 16:03
Can't find a specific reference with a list of data types at the moment. Generally, it's the same data types that are allowed in Dependent Lookups.

**Comment by patrick-rodgers** [comment] 2020-07-14 20:32
Going to close this as answered. Thanks!

**Closed by patrick-rodgers** 2020-07-14 20:32 UTC
Labels: status: not a bug, type: question
