### ISSUE TITLE
Saving metadata via code in PnPJs doesn't work when page is being edited

### ISSUE THREAD

**Issue by PieterVandendriessche** [pnp/pnpjs#3098] opened 2024-07-31 15:24 UTC
### Major Version

4.x

### Minor Version Number

4.3.0

### Target environment

SharePoint Framework

### Additional environment details

I am using SPFx and pnpJS to edit properties of a page, this in a pane. The page is in edit mode.

### Expected or Desired Behavior

Saving the page metadata should work as expected. This behaviour worked before, but doesn't work anymore.

### Observed Behavior

![image](https://github.com/user-attachments/assets/3cfbed05-3e18-40e3-9db7-28fa71468646)
Getting a message that the resource is locked and being edited by the user.
Tenant is in targeted release, co-authoring of SP pages might affect this

### Steps to Reproduce

`import { spfi } from "@pnp/sp";
import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";

const sp = spfi(...);

const list = sp.web.lists.getByTitle("MyList");

const i = await list.items.getById(1).update({
  Title: "My New Title",
  Description: "Here is a new description"
});

console.log(i);`

Run the code on the page while in edit mode. Assert you will get a 423 (locked)

**Comment by patrick-rodgers** [comment] 2024-07-31 20:00
This is likely not something we can control. That would be an error from the server. Will try and have a look at some point on what might be happening.

**Comment by bcameron1231** [comment] 2024-08-02 16:33
Hi. Yea this appears to be a change on the Microsoft side. I have tested on a tenant with standard release, and I don't get this error. It seems like maybe the new co-authoring experience is locking the Site Pages. 

I am going to close this for now as it appears unrelated to the library. I would check with Microsoft and see if this is intended behavior.

**Closed by bcameron1231** 2024-08-02 16:33 UTC
Labels: type: question, status: investigate
