### ISSUE TITLE
SPFX React WebPart - this.context.pageContext.web.absoluteUrl is Undefined in Render

### ISSUE THREAD

**Issue by philippe-entringer** [pnp/pnpjs#514] opened 2019-02-21 14:00 UTC
#### General Information
* [ ] Usage
* [x] Development
* [ ] Documentation
* [ ] Feature Request

#### What Version you are running?
* NodeJS: V8.15
* NPM: 6.8.0
* @pnp/spfx: V1.7.1

#### Problem Description
Create a HelloWorldWebPart with **React** Framework
On the **Render** Method try to retrieve the 
this.context.pageContext.web.absoluteUrl

```
  public render(): React.ReactElement<IHelloWorldProps> {
    return (
      <div className={ styles.helloWorld }>
        <div className={ styles.container }>
          <div className={ styles.row }>
            <div className={ styles.column }>
              <span className={ styles.title }>Welcome to {this.context.pageContext.web.absoluteUrl}</span>
              <p className={ styles.subTitle }>Customize SharePoint experiences using Web Parts.</p>
              <p className={ styles.description }>{escape(this.props.description)}</p>
              <a href="https://aka.ms/spfx" className={ styles.button }>
                <span className={ styles.label }>Learn more</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    );
  }
```

My goal is to query a SharePoint List using "@pnp/sp"
`import { sp } from "@pnp/sp";
...
 sp.setup({
        spfxContext: this.context
      });`

### More Information
the this.context.pageContext.web.absoluteUrl is well defined if I choose "**No Framework**" during the webpart generation wizard.

#### So my question is how do I initialize the SharePoint context before using @pnp/sp in React WebPart ?

Any help would be appreciated.

thanks

**Comment by patrick-rodgers** [comment] 2019-02-21 20:53
Hi @philippe-entringer  - @StfBauer wanted this transferred here. Can you share a link to a minimal reproduction repo? Thanks!

**Comment by simonagren** [comment] 2019-02-21 22:28
You could see here what I've done in an field customizer: [link](https://github.com/SharePoint/sp-dev-fx-extensions/blob/master/samples/react-field-user-permission/src/extensions/userPermission/UserPermissionFieldCustomizer.ts)

As you see I send in the properties from the Web part, where we have context available. Are you trying to get the absolute url from inside a react component?

**Comment by philippe-entringer** [comment] 2019-02-22 23:16
Thanks for the follow up, 
I finally found a way to intialize the current sharepoint context with my React Component.

Here are my conclusions regarding the use of pnp/js SharePoint 

### For React  Web part
1. Init the sharepoint current site url in the  Render method of the Webpart ( *.ts file)
'''
public render(): void {
    const element: React.ReactElement<IDropDownWebPartProps > = React.createElement(
      DropDownWebPart,
      {
siteUrl: this.context.pageContext.web.absoluteUrl,
}
'''

2.  Setup the sp context in the React WebPart code (*.tsx) 
'''
import { sp } from "@pnp/sp";

constructor(props: IDropDownWebPartProps) {
    super(props);
     //https://pnp.github.io/pnpjs/documentation/getting-started/
    sp.setup({
      sp: {
        baseUrl: this.props.siteUrl
      },
    });
  }

private _loadListItems(
{
// load your list items with the sp.setup context
sp.web.lists.getByTitle(thelistName).items
}
'''

reference
https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/connect-to-sharepoint-using-jsom.md

### For "No Framework" React  Web part
the sp.web.lists.getByTitle(thelistName).items works directly 
no initialization is needed.

**Comment by simonagren** [comment] 2019-02-23 07:27
@philippe-entringer I see what you did, but I wouldnt suggest that.
That baseurl is mostly for usage outside of SharePoint FrameWork.

1. Yes you are passing in the values from the context to your react component as a Property. That's a good way to do it.

2. Don't do that :)
In the same `WebPartName.ts` as you just did the render() add a OnInit and do the setup there. Because if you think about it this is where you have the context available, because it's the web parts context, not React context.
```TypeScript
public onInit(): Promise<void> {
    return super.onInit().then(_ => {
      sp.setup({
    spfxContext: this.context
    });
    });
  }
```

**Comment by philippe-entringer** [comment] 2019-03-02 01:35
All is cristal clear now.
Thanks Simon !

**Comment by patrick-rodgers** [comment] 2019-03-04 14:14
Thanks, going to close this as answered.

**Closed by patrick-rodgers** 2019-03-04 14:14 UTC
Labels: area: non-library, status: details needed, type: question
