### ISSUE TITLE
ITermInfo::childrenCount is not filled by getting terms

### ISSUE THREAD

**Issue by yarick123** [pnp/pnpjs#1378] opened 2020-09-14 09:21 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 2.0.9, 2.0.10 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint online ]

### Expected / Desired Behavior / Question
ITermInfo::childrenCount expected to be filled with the correct number of the children especially if the field 'childrenCount' is selected by the select(...) method.

### Observed Behavior
```ts
import { ITermInfo, ITermSet, SPBatch, sp } from '@pnp/sp-commonjs';
// ...
	const termset: ITermSet = sp.termStore.sets.getById(termsetId);
	const terms: ITermInfo[] = await termset.children.select('childrenCount')();

	console.log('Raw terms:', terms)
```
all the returned terms do not contain childrenCount field at all. Some terms definitive have children.

### Steps to Reproduce
- execute the code above on a termset with terms, which contain children.

**Comment by juliemturner** [comment] 2020-09-21 12:44
After digging in a bit, it appears that in addition to the endpoints changing (as we noted in the change log for v2.0.9) the return payload has also changed and the IChildren definition needs to be updated.  The following are the only properties available:

- id
- labels
- createdDateTime
- lastModifiedDateTime
- descriptions
- properties

**Comment by juliemturner** [comment] 2020-09-21 19:43
Duplicate of #1359

**Comment by juliemturner** [comment] 2020-10-09 17:17
Docs updated to indicate beta endpoint changes.

**Closed by juliemturner** 2020-10-09 17:17 UTC
Labels: area: code, status: fixed, type: bug
