### ISSUE TITLE
Deleting sharepoint group using pnpjs removeByLoginName gives "Exception from HRESULT: 0x80131904"

### ISSUE THREAD

**Issue by Manjunatha123** [pnp/pnpjs#1980] opened 2021-12-17 06:12 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using:
Please find the versions
"@pnp/nodejs-commonjs": "^2.1.0",
"@pnp/pnpjs-commonjs": "^2.1.0", 
"@pnp/sp-commonjs": "^2.1.0"

Please specify what version(s) of SharePoint you are targeting: Sharepoint online

### Expected / Desired Behavior
Deleting an sharepoint group from sharepoint site using an isolated runtime should delete the site group successfully.

### Observed Behavior

We are creating a runtime (sp: SPRest) with username and password to read data (As seen by a visitor of the site with "Site Visitor Access") from the relevant lists from sharepoint online. After data is read we manipulate data and upload back to sharepoint site contents and delete some of the data from the list and a sharepoint group.
To upload data back to SPO we are creating a new Isolated runtime with client id and secret to the same site. Please find below the implementation.
```
import { bootstrap } from 'pnp-auth';
...
...
export class DataFromSP{
    constructor(siteUrl: string, username: string, password: string) {
        bootstrap(sp, { username, password }, siteUrl);
    }
    public datafetch(){
        return sp.web.lists.getByTitle('abc').select(select fields).get();
    }
}
...
// ISolated runtime example for delete data
...
export class DeleteDataFromSP{
   constructor(siteUrl: string, clientid: string, secret: string,logPath:string) {
        this.siteUrl = siteUrl, this.clientid = clientid, this.secret = secret; this.logPath=logPath;
    }
    public async createIsolatedroot() {
        this.isolatedSP = await sp.createIsolated();
        bootstrap(this.isolatedSP, { clientId: this.clientid, clientSecret: this.secret }, this.siteUrl);
    }
...
...
    public async deleteUserGroup(groupName) {
        try {
            const groupName = '_My_Custom_Group_Name';
            await this.isolatedSP.web.siteGroups.removeByLoginName(groupName);
        }
        catch (error) {
            logger.errorLogger.error(`error deleting user group: ${groupName}`, error);
        }
    }
}
```
When we are trying to delete the user group using `await this.isolatedSP.web.siteGroups.removeByLoginName(groupName)` we are getting "Exception from HRESULT: 0x80131904".
This issue is intermittent but is prominent when is run in the AzureDevOps Pipeline as a powershell command.
Please find the format of the command
```
tsc --pretty
node lib/index.js --command line parameters
```
### Steps to Reproduce
Running. the above command created issue for us. Even though it's intermittent only 2 out of 5 cases the command is succeeding where the user group is deleted in rest of the 3 cases user group is not deleted.

**Note**: When user group is directly deleted using SPO it was getting deleted without errors.

**Comment by koltyakov** [comment] 2021-12-17 07:48
Usually this error appears when there is little free disk space on SQL server. I don't believe such error could be caused by something wrong in the library.

Can you process the same operation manually on the farm without getting an error?

**Comment by Manjunatha123** [comment] 2021-12-17 10:16
@koltyakov Any suggestions from your side on measures (code wise) that can be taken to avoid the error ?

**Comment by koltyakov** [comment] 2021-12-17 10:18
Maybe a custom retry logic?

**Comment by Manjunatha123** [comment] 2021-12-17 11:04
Could you please give a small code demo on how we could tryout the custom retry logic

**Comment by koltyakov** [comment] 2021-12-17 11:13
IDK, something like this:

```typescript
const doWithRetries = async <T>(
  action: () => Promise<T>,
  checkException: (ex: unknown) => boolean = () => true,
  retries = 5
): Promise<T> => {
  try {
    return await action();
  } catch (ex) {
    const needRetry = checkException(ex);
    if (needRetry && retries > 0) {
      return doWithRetries(action, checkException, retries - 1);
    }
    throw Error(ex);
  }
};
```

this is completely agnostic to PnPjs, just a recursion with a exception check logic and tryouts.

**Comment by dvTB** [comment] 2021-12-30 16:39
Sadly the exception 0x80131904 comes from sharepoint directly and has nothing to do with the api. You quite often get this error when there is something with per item-level security in your site. From my experience with such problems (from onprem and online), don't force sharepoint to to permission-changes at the same time on the same item/folder/list/web. This will lead to "broken" items in the database (in onprem and sadly also online). E.g. if you remove a group, you also remove it from items the group has advanced access to.
One option you have is to retry the action a bit later. E.g. write a queue of actions you still have to do and get those actions done by a service which retries the actions from time to time.

The other thing you can try is, use the MS support. After all this is an error on SharePoints side, so they have to fix it, if they accept is as a bug.

**Comment by patrick-rodgers** [comment] 2022-01-03 19:43
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2022-01-03 19:43 UTC
Labels: type: question, status: answered, area: code
