### ISSUE TITLE
Remove requirement for Adal auth popup

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpjs#391] opened 2018-11-27 15:24 UTC
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.6]

Please specify what version(s) of SharePoint you are targeting: [SPFx 1.6 (Online)]

### Expected / Desired Behavior / Question
Making a request to Graph authenticates without requiring a popup, as described [here](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/33717253-remove-pop-up-requirement-for-graph-api-spfx-web-p).

### Observed Behaviour
The Adal client still creates a popup, which are blocked by default, and does not work when multiple users are signed in. The code can be seen [here](https://github.com/pnp/pnpjs/blob/dev/packages/common/src/adalclient.ts#L148).

### Steps to Reproduce
Make an initial request to Graph using the PnP graph library to trigger authentication.

**Comment by CPritch** [comment] 2018-11-27 16:12
Same here on this one, clearly the adal configs need to be updated in the common package.

**Comment by simonagren** [comment] 2018-11-27 16:49
@patrick-rodgers do you want to have a look? I have a few minutes tonight otherwise :)

**Comment by patrick-rodgers** [comment] 2018-11-27 17:01
IF you are operating inside SPFx >=1.6 and [provided us the context](https://pnp.github.io/pnpjs/documentation/getting-started/#establish-context) then you should not see a pop-up. This is however entirely governed by SPFx. [You can see the actual code that is running](https://github.com/pnp/pnpjs/blob/dev/packages/common/src/adalclient.ts#L208).

**Comment by patrick-rodgers** [comment] 2018-11-27 19:45
Can you share a minimal reproduction of what you are doing? Inside SPFx you shouldn't need to worry about creating any clients or anything, just provide the context as [shown in the docs](https://pnp.github.io/pnpjs/common/docs/adalclient/#calling-the-graph-api). The client should be auto created behind the scenes and you can just call the graph API.

**Comment by JakeStanger** [comment] 2018-11-27 20:07
```typescript
public onInit(): Promise<void> {
  return super.onInit().then(_ => {
    graph.setup({
      spfxContext: this.context
    });
    graph.users.get().then(console.log); // Or any other graph endpoint at all.
  });
}
```
On newly created apps using either the `@microsoft/sharepoint` or `@pnp/spfx` generators, either:
- Produces the popup
- Appears to make no attempt to authenticate and the request returns 403.

Generally I've found authentication to be more reliable on Firefox than Chrome.

**Comment by patrick-rodgers** [comment] 2018-11-28 00:20
Have you followed the steps in [this article](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#deploy-the-solution-and-grant-permissions) specifically those around visiting the new API management page? There was a limited number of older tenants that needed an admin to visit this page to reset the AAD plumbing used by SPFx. My tenant was affected and I needed to visit this page, wait about 10 minutes, and then everything "magically" started working again.

I can't reproduce this so its very hard to debug. The other issues is that if you are using all the versions of things you say (and I believe you) then we are using directly the SPFx AAD token provider to get the token, there isn't much we can do to fix anything there. Do you get the same permission errors if you use the native graph client in SPFx? That would help us narrow down whether it is permissions/setup of something with the library.

**Comment by JakeStanger** [comment] 2018-11-28 09:22
My previous statement that it appears to make no attempt to authenticate seems to be wrong. Checking session storage shows adal authentication keys for Graph do appear when the first request is made, however the request is still returning 403.

I know permissions have definitely been set in the new API management page on tennants before to get Graph working, which has previously failed to make everything magically work as often described. I will however try again with a fresh application and report back.

**Comment by JakeStanger** [comment] 2018-11-28 15:33
Revoking and re-granting the permission in SharePoint seems to have fixed it, cheers for your help.

**Comment by patrick-rodgers** [comment] 2018-11-28 15:37
Awesome, glad things are working! I'll close this then as resolved, please _reopen_ should you need to continue the conversation. Thanks!

**Closed by patrick-rodgers** 2018-11-28 15:37 UTC
Labels: area: code, status: details needed, type: question
