### ISSUE TITLE
Cannot read property 'sectionFactor' of undefined

### ISSUE THREAD

**Issue by dunlapm** [pnp/pnpjs#2026] opened 2022-01-29 00:36 UTC
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.11.0]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online]

### Expected / Desired Behavior / Question
I expect `sp.web.loadClientsidePage()` to properly load a Full Page App page.

### Observed Behavior
Attempting to use `sp.web.loadClientsidePage` on a Full Page App (created with `sp.web.addFullPageApp()`) will fail with the error "Cannot read property 'sectionFactor' of undefined" because the `onColumnChange` method of `ClientsideWebpart` does not check if `this.data.position` exists. It does for "normal" pages, but not for Full Page App pages.

   

### Steps to Reproduce
This can be easily reproduced if you have created a Full Page App page and use the PnPjs Console.

```
import { sp } from "@pnp/sp/presets/all";

(async () => {

  const page = await sp.web.loadClientsidePage("/teams/mysite/SitePages/MyFullPageApp.aspx");
  console.log("My page: ", page);

})().catch(console.log)
```

**Comment by patrick-rodgers** [comment] 2022-02-03 20:27
I am unable to reproduce this locally. My code is below and works without issue. Can you share a full repro so we can easily see the issue? Perhaps this was fixed by some other update and is no longer an issue.

```TS
try {

    const newPage = await sp.web.addFullPageApp("addFullPageApp2.aspx", "addFullPageApp", "guid");

    await newPage.save();

    const page = await sp.web.loadClientsidePage("/sites/dev/SitePages/addFullPageApp2.aspx");
    console.log("My page: ", page);

} catch (e) {

    console.error(e);
}
```

**Comment by dunlapm** [comment] 2022-02-03 20:55
After the page is created the page can be fetched immediately. Have you
tried loading it again in a new browser session after the page has been
created?

**Comment by dunlapm** [comment] 2022-02-03 21:09
I specifically said in my "Steps to Reproduce" that the Full Page App page was created outside of using the PnPJS console.

**Closed** 2022-03-09 14:00 UTC
Labels: status: details needed, area: code, type: someting isn't working
