### ISSUE TITLE
addChunked function fails with odata=nometadata

### ISSUE THREAD

**Issue by ahyland** [pnp/pnpjs#1616] opened 2021-03-02 11:55 UTC
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [     2.2.0    ]

Please specify what version(s) of SharePoint you are targeting: [     SPO    ]

### Expected / Desired Behavior / Question
Currently using PnP JS to build a custom SPFx web part that will allow users to upload files in to a document library and have them tagged appropriately. I am using the 'addChunked' function to upload a document in to a folder within a library. 

### Observed Behavior
When executing the function I get the following error:

Error: Error making HttpClient request in queryable [404] ::> 404 NOT FOUND

Using Chrome Dev Tools I can see that the HTTP Request the code is failing on is as follows:

> Request URL: https://tenant.sharepoint.com/sites/dev/startUpload(uploadId=guid'18f3350d-5876-4049-b63b-90eb564657d9')

When I look in the library where the file is being uploaded, the file itself has been created but it contains no content.

I am currently using pnp js version 2.2.0, however, I also had this problem with version 2.1.1 I only downgraded as I was able to get it working in the PnP JS Dev Tools which was using 2.1.1 so I thought I would downgrade to test but I still get the same issue.

### Steps to Reproduce
My original code was initial the context with the following headers:

```	private static _context: WebPartContext;
	
	public static initialise(context: WebPartContext) {
		this._context = context;

		sp.setup( {
			spfxContext: context,
			sp: { 
				headers: { 
					"Accept": "application/json;odata=nometadata"
				}
			}
		} );
	}
```

After changing my context to instead be 'minimalmetadata' I was able to get the function working successfully this is how I now initialise my context:

```
	private static _context: WebPartContext;
	
	public static initialise(context: WebPartContext) {
		this._context = context;

		sp.setup( {
			spfxContext: context,
			sp: { 
				headers: { 
					"Accept": "application/json;odata=minimalmetadata"
				}
			}
		} );
	}

```

The code I am executing when experiencing this issue is as follows:

```
export interface IDocumentItem {
    documentFilename: string;
    documentTitle: string;
    actionId: string;
    
    file: File;
}

export interface IAddDocumentResponse { 
	itemid: number;
	filename: string;
	folderserverrelativeurl: string;
	listserverrelativeurl: string;
	serverrelativeurl: string;
	serverredirectedembedurl: string;
    properties: IListItemFormUpdateValue[];
}

public static async uploadEvidence(folderUrl: string, document: IDocumentItem, progress: (data: IFileUploadProgressData, stage?: string) => void):Promise<IAddDocumentResponse> {
const targetActionFolderUrl = `${this._context.pageContext.site.serverRelativeUrl}/DocLib/${folderUrl}`;
const fileContent: Blob = document.file;
const targetFileName = `${document.documentFilename}`;
const addedFile = await sp.web.getFolderByServerRelativeUrl(targetActionFolderUrl).files.addChunked(targetFileName, fileContent, progress, true);

}
```
I call the 'uploadEvidence' function from a separate file combined with the [PnP File Picker control](https://pnp.github.io/sp-dev-fx-controls-react/controls/FilePicker/) upon a file being selected the function it then executed and any result captured.

Thanks to @phillipharding for helping with diagnosing this issue otherwise I would have been stuck forever. I hope this is enough information.

**Comment by patrick-rodgers** [comment] 2021-03-02 13:20
Sorry this caused you a problem but it is currently by design. We use the metadata to make the multiple requests work using calls to our `odataUrlFrom` internally. I understand the desire to use nometadata for smaller request sizes (good) but in this case we use the data internally to make the process work. I'd add that when uploading huge files in chunks there is no meaningful savings using nometadata.

One of our discussion points right now for v3 is improving support for nometadata and using minimalmetadata by default. We haven't up until now because some versions of on-premises only understand verbose.

Will leave this open and we can look at supporting nometadata mode for addChunked, but can't currently promise we will.

**Comment by ahyland** [comment] 2021-03-02 14:46
@patrick-rodgers thanks for the quick response it is much appreciated. Most of the files being uploaded as part of the web part I am developing will be relatively small in size so using minimalmetadata works fine and makes sense, hopefully this will be a useful reference for any other users who may experience this issue 👍

**Comment by koltyakov** [comment] 2021-03-02 14:57
As a workaround, while having `nometadata` globally, it's possible to `.configure()` a specific call with chunked upload with `minimalmetadata` headers.

However, I can't recommend `nometadata` in general. It saves really small amount of traffic while breaks many things. I know, it's a bad excuse and we should maybe think into a direction when those calls, which internally need at least `minimalmetadata`, automagically rewrite odata level.

**Comment by patrick-rodgers** [comment] 2021-08-03 16:38
Going to close this as there isn't a way to really support the functionality with no metadata.

**Closed by patrick-rodgers** 2021-08-03 16:38 UTC
Labels: area: code, status: investigate, type: enhancement
