### ISSUE TITLE
[Graph] Optional Batch Splitting Timeout

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpjs#1886] opened 2021-09-28 14:35 UTC
### Category
- [x] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.9.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question

Easy change to make so I'll happily submit a PR, but this seemed like a good one to run past you guys first in case you have any opinions on patterns or would rather avoid it.

There are some weird edge-cases with the Graph API where performing batch operations can cause concurrency errors. One I've run into is bulk-deleting individual events in a series. If you delete more than the batch's max requests (causing it to split), the second batch request will often fire too quickly, and subsequently fail.

This is quite poorly documented, but the supposed fix seems to be to just...wait. Apparently 100ms is fine:

```ts
while (requests.length > 0) { 
  // ...
  
  if(waitBetweenBatchRequests) {
    await new Promise(resolve => setTimeout(resolve, 100));
  }
}
```

Regarding controlling this behaviour:

- Should this be exposed to the user?
- Should it be controllable with a boolean, or direct control over the timeout (which defaults to 0)?
- If it's exposed to the user, regarding #1884, any preference on the public interface:

```ts
graph.createBatch(4, 100); // maxRequests, timeout
// or
graph.createBatch({maxRequests: 4, timeout: 100});

**Comment by juliemturner** [comment] 2021-09-28 15:03
While I think it's somewhat complicated (as you point out) to surface this in V2, the new timeline implementation of V3 is so well suited to deal with a scenario like this using what we're tentatively calling `Behaviors`.  @patrick-rodgers doesn't it seem like this would be very similar implementation to the Pessimistic Caching behavior https://github.com/pnp/pnpjs/blob/version-3/packages/queryable/behaviors/cachingPessimistic.ts

**Comment by JakeStanger** [comment] 2021-09-28 16:16
I'd argue it wouldn't be complicated to surface in V2 (see #1884), but the implementation would be somewhat unideal and it should definitely be revisited for V3. The problem is there's no workaround for this in V2 at the moment other than to avoid batching, or implement your own batching system.

In regards to V3 though, I do have a few other issues/areas of improvement for batching that I've been able to work around & I'd be happy to open a discussion and talk about the system as a whole (this issue included).

**Comment by juliemturner** [comment] 2021-09-28 16:27
By complicated I mean that you're introducing this option that would mostly be unused and thereby add complexity where 99.9% of the time it wouldn't be needed.  So probably just a poor choice of words.  Regardless, since we're on the cusp of an alpha release for V3 I would think that would be the better area to focus given my comment about mostly unused.  

Regarding batching yes, changes and updates needed to be made and @patrick-rodgers made some that I really love... maybe check out the new updated batching in V3 and see if that's any better and certainly if you have additional ideas, we'd love to hear them.

**Comment by patrick-rodgers** [comment] 2022-03-24 00:18
In v3 we now [support setting maxRequests](https://github.com/pnp/pnpjs/blob/version-3/packages/graph/batching.ts#L29) when the behavior is added. So that part is resolved.

Given we have a new design, does the need for a delay still exist in v3? I'd prefer not to inject artificial delays to cover edge cases if it can be avoided. Is there a consistent way to test that and see what the timing is?

**Comment by JakeStanger** [comment] 2022-03-26 17:49
I've changed job since I opened this (hence the recent radio silence), so unfortunately I don't have access to the scenario that this was necessary for. However, from what I can remember:

Being able to set `maxRequests` manually does not fully resolve this, as the API still has a hard-limit on the batch size, so the requests do still need to be split into multiple batches at some point. That means that a delay *will* still be required in these scenarios. 

As it is a very specific use-case (one that nobody else seems to have run into), and one that is at least possible to work around (albeit with another layer of batch management), I'll leave it up to you guys as to how necessary this is. Having a feature like this would add complexity for very small gains.

I've not had too much chance to play with it yet I'm afraid, but would the new pipeline system in V3 allow for adding this behavior yourself?

**Comment by patrick-rodgers** [comment] 2022-03-28 17:23
@JakeStanger - cool, since we've not seen any other reports on this behavior, I think we can close this issue for now. If you have time and can give us a way to quickly reproduce the issue that would be solved with a delay, we can have a look. Thanks!!

**Closed by patrick-rodgers** 2022-03-28 17:23 UTC
Labels: type: enhancement, status: details needed, area: code
