### ISSUE TITLE
A supported MIME type could not be found that matches the content type of the response

### ISSUE THREAD

**Issue by JarialAnkur** [pnp/pnpjs#2738] opened 2023-07-13 20:18 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

### Category

- [ ] Bug

Please specify what version of the library you are using: [     3.15.0    ]

Please specify what version(s) of SharePoint you are targeting: [    1.15.0     ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
After creating a new file using "A using path" API after creating the file, I am trying to move it using Batching but, I get an error. 
"A supported MIME type could not be found that matches the content type of the response".  After I reload the tab of the browser, it works fine and the file gets moved. I am trying to inject headers using inject headers in "spfi().using". But those are not reflected in the request. Instead, the file should get moved instantly. because I am even passing the headers, and I should see the batch request in the network call. Instead I see the move API call of sharepoint and it has an  error 400. 

### Observed Behavior
After creating a new file using "A using path" API after creating the file, I am trying to move it using Batching but, I get an error. 
"A supported MIME type could not be found that matches the content type of the response".  After I reload the tab of the browser, it works fine and the file gets moved. I am trying to inject headers using inject headers in "spfi().using". But those are not reflected in the request.

### Steps to Reproduce
`const sp = spfi().using(
    SPBrowser({
        baseUrl: Constants.siteUrl + Constants.relativeSiteUrl,
    }),
    InjectHeaders({
        "Content-Type" : "application/json;odata=minimalmetadata",
        "Testing":"Ankur",
        "Cache-Control": "no-cache",
    }));`
`const [batchedWeb, execute] = sp.web.batched();`

`batchedWeb.getFileByServerRelativePath(`!@p1::${FileOrFolder.ServerRelativeUrl}`).moveByPath(DestinationUrl, false, true).then((result)=>{
            console.log('This is result in move files =>',result)
            res.push(result)
        }).catch((error)=>{
            console.log('This is erropr in batchedWeb=>',error)
            return "error"
        })`
![Screenshot 2023-07-14 014747](https://github.com/pnp/pnpjs/assets/49793242/2193f6b6-1258-4348-9caf-969ac33aa1e8)

### Submission Guidelines
*Delete this section after reading*
* All suggestions, questions and issues are welcome, please let us know what's on your mind.
* Remember to include sufficient details and context.
* Please check back occasionally on your issue as we may have follow up questions.
* If you have multiple suggestions, questions, or bugs please submit them in separate issues so we can track resolution.

Thank you for your feedback!

**Comment by juliemturner** [comment] 2023-07-13 21:59
I'm confused about your environment.

>Please specify what version(s) of SharePoint you are targeting: [ 1.15.0 ]

Do you mean SPFx 1.15.0? If that's the case why are you using the SPBrowser? Why are you trying to inject those headers?

But regardless file handling isn't generally supported by batching. We've been trying to update the docs to tag them all that batching isn't supported. I'm not sure without testing if moveByPath is affected but I suspect it is. If you do those steps without batching do they work, if so then I suspect that's the problem. 

Regarding batching not using the headers that you defined in the original sp, I'd have to review that code, but could it be related [to the fix that's pending](https://github.com/pnp/pnpjs/pull/2718)?

**Comment by JarialAnkur** [comment] 2023-07-14 12:43
Yeah, the environment is SPFx 1.15.0. and I am trying to inject those headers because the says that there is no content-type: application/json header in the batch call which is true. 
Yes without batching it is not a problem. But the thing is once a new file is created, using the API and if I reload or refresh the browser tab then the batching works properly.

**Comment by juliemturner** [comment] 2023-07-14 12:53
So you create the file and then try to use batching to move it... that doesn't work, but if you create the file, refresh the browser, and then use batching to move it it does? 

Have you tried the v3nightly build going back to normal SPFx behavior without the header injection?

**Comment by bcameron1231** [comment] 2023-07-14 14:28
As @juliemturner mentioned, we *believe* this is fixed in that PR that she linked.

Basically any of the batching calls that have internal roundtrip calls can have these issues (like the one you're using (get file by path, and then move), because the multipart/mixed header isn't changing.

In the interim, I'd say try and test out that PR with your code and see if it works... or just wait until we deploy the fix in the next release.

**Comment by JarialAnkur** [comment] 2023-07-14 14:39
I can get that in the nightly build to test if it solves the problem right?
 Then I will add this to the solution once version 3.17 is released.

**Comment by bcameron1231** [comment] 2023-07-14 15:17
Yes.

**Comment by JarialAnkur** [comment] 2023-07-17 20:02
I went ahead and installed the nightly build, of the pnpjs (3.16.0-v3nightly.20230717). While this time something strange happened. 
Again I was creating a new file, and after that, I was moving it. But this time, sometimes I was seeing batch API calls in network calls and sometimes the direct ("SP.MoveCopyUtil.MoveFileByPath"). I did not understand why was this happening. I also removed the injected headers. 

2. In a few cases I got the following error 
Error: Could not properly parse responses to match requests in the batch. 
This was more frequent

**Comment by juliemturner** [comment] 2023-07-17 20:09
Can you please share your new code.... hard to help you without it.

**Comment by JarialAnkur** [comment] 2023-07-17 20:09
batchedWeb.getFileByServerRelativePath(!@p1::${FileOrFolder.ServerRelativeUrl}).moveByPath(DestinationUrl, false, true).then((result)=>{ console.log('This is result in move files =>',result) res.push(result) })


Basically, the above code is getting executed, instead, it should only execute once I hit execute function for that batch.

**Comment by JarialAnkur** [comment] 2023-07-17 20:10
`const [batchedWeb, execute] = sp.web.batched();`

`FileOrFolderArr.map(async (FileOrFolder)=>{
        console.log('This is FileORFolder archive =>', FileOrFolder)
        const DestinationUrl = replacewithArchiveLibrary(FileOrFolder.ServerRelativeUrl)
        console.log("This is destination url = >", DestinationUrl)
       batchedWeb.getFileByServerRelativePath(`!@p1::${FileOrFolder.ServerRelativeUrl}`).moveByPath(DestinationUrl, false, true).then((result)=>{
            console.log('This is result in move files =>',result)
            res.push(result)
        }).catch((error)=>{
            console.log('This is error in batchedWeb=>',error)
            return "error"
        })
    })`

**Comment by juliemturner** [comment] 2023-07-17 20:10
I would say you have something wired up incorrectly. Without a full reproduction of what you're doing it's very hard to help you.

**Comment by JarialAnkur** [comment] 2023-07-17 20:13
```TypeScript
await execute().then(async (res)=>{
        console.log('TYhis is response in batch execiute=>',res)
}))
```

**Comment by juliemturner** [comment] 2023-07-17 20:27
I don't `think` this should be async

`FileOrFolderArr.map(async (FileOrFolder)=>{`

Hard to know without a full code implementation like I mentioned. And I know there have been issues using map/foreach type loops so you might try changing to a pure for(let i=0 type thing just to take that out of the equation.

**Comment by JarialAnkur** [comment] 2023-07-17 20:28
Sure will try that as well.

**Comment by bcameron1231** [comment] 2023-07-18 13:16
I've spent quite a bit of time trying to reproduce this, and I have not been able to. It works for me as expected

Here is my code (modeled after yours)
```
const [batchedWeb, execute] = this.sp.web.batched();
      const files = ["Document1.docx", "Document2.docx"];
      let i = 0;
      for(i=0; i < files.length; i++ ){   
        batchedWeb.getFileByServerRelativePath("/sites/contoso/Files/" + files[i]).moveByPath("/sites/contoso/Archive/Files/"+files[i], false, true).then((result:any)=>{
          console.log(result);
        }).catch((error:any)=>{
          console.log(error);
        });
      }
```

I've ran this multiple times and tried switching up different scenarios and makes the calls correctly (two calls to get file by path, and 1 batch)
![image](https://github.com/pnp/pnpjs/assets/7944457/6d8c3841-035a-4efa-98b9-2c3a7b230e9e)

At this point, because we can't reproduce, we ask that you go send us a repository with reproducible source code that we could try and run. Otherwise, it's going to be very difficult to try and diagnose, given we're only looking at a subset of the code, which appears to work for us.

**Comment by JarialAnkur** [comment] 2023-07-18 14:13
Hey Cameron, so if you are using a static file or a file that is already residing. It works for them perfectly. But, I am saying the key point here is "If we create a new file using the API `addusingPath` and just after the file gets created we try to move it using batch. 
Only in the above case, it fails. 

```Typescript
const file = await (await folderFromPath(sp.web,`!@p1::${relativeUrl}`)).files
        .addUsingPath(`!@p2::${relativeUrl+"/"+fileName}`,"");
   var item:any = await (await fileFromPath(sp.web,`!@p1::${file.data.ServerRelativeUrl}`)).listItemAllFields({
                headers:{
                  "Cache-Control": "no-cache"
              }
            })
```
Just after this code, we run the batch code, that you just mentioned in the above comment. 
I know this is a rare case.

**Comment by bcameron1231** [comment] 2023-07-18 15:41
I don't think this is a rare case, but it is difficult to diagnose when we don't have all the code.

As for the code, I still can't reproduce.

1. I'm adding two files,  then I am adding them to an array of files
2. I'm looping through each one for the batch
3. executing the batch
```
 var files:any = [];
var file = await(await folderFromPath(this.sp.web, "/sites/contoso/Files/Test")).files.addUsingPath(encodeURI("Document1.txt"),"Hello");            
files.push(file);

var file2 = await(await folderFromPath(this.sp.web, "/sites/contoso/Files/Test")).files.addUsingPath(encodeURI("Document2.txt"),"Hello");            
files.push(file2);

const [batchedWeb, execute] = this.sp.web.batched();
let i = 0;
for(i=0; i < files.length; i++ ){   
  batchedWeb.getFileByServerRelativePath(files[i].data.ServerRelativeUrl).moveByPath("/sites/contoso/Archive/Files/"+files[i].data.name, false, true).then((result:any)=>{
    console.log(result);
  }).catch((error:any)=>{
    console.log(error);
  });
}

await execute().then(async (res:any)=>{
  console.log('TYhis is response in batch execiute=>',res)
});
```

It uses the proper batch call.
![image](https://github.com/pnp/pnpjs/assets/7944457/15c44974-e9f0-4c54-ba78-1de9fdfa5eb2)

**Comment by JarialAnkur** [comment] 2023-07-19 12:56
Hey, Cameron thanks for the confirmation. I will try to diagnose it on my end now. If this code is working fine. I need to check other part of code.

**Comment by juliemturner** [comment] 2023-07-19 12:57
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Closed by juliemturner** 2023-07-19 12:57 UTC
Labels: type: question, status: answered, area: code
