### ISSUE TITLE
1.3.1-2 version get list item object for ClientSidePage

### ISSUE THREAD

**Issue by Sartor87** [pnp/pnpjs#569] opened 2019-03-20 15:31 UTC
### Category
- [ ] Enhancement
- [X] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.1-2]

Please specify what version(s) of SharePoint you are targeting: [Online]

### Expected / Desired Behavior / Question

Expecting to update list item settings for a created client side page.

    const item: Item = await page.get();

      const pageItem = await item.update({
        "ContentTypeId": contentTypeId,
        "PromotedState": 2,
        "BannerImageUrl": {
          "__metadata": { "type": "SP.FieldUrlValue" },
          "Description": "",
          "Url": ""
        }
      });

### Observed Behavior
Throws error that update is not a function.

### Steps to Reproduce
     const ct = await sp.web.contentTypes.getById("0x0101009D1CB255DA76424F860D91F20E6C4118").get();
      const contentTypeId = ct.Id.StringValue;

      const page = await sp.web.addClientSidePage("test565-1", "another title");

    const item: Item = await page.get();

      const pageItem = await item.update({
        "ContentTypeId": contentTypeId,
        "PromotedState": 2,
        "BannerImageUrl": {
          "__metadata": { "type": "SP.FieldUrlValue" },
          "Description": "",
          "Url": ""
        }
      });

**Comment by patrick-rodgers** [comment] 2019-03-20 17:10
This is by design, .get() does not return an item instance. The page object now includes property and methods to update all of the things in your code - suggest trying those to ensure they meet your needs.

**Comment by Sartor87** [comment] 2019-03-21 07:05
@patrick-rodgers methods and properties seems to work fine. However, I couldn't find anything related to content type - do you have any suggestions?

**Comment by patrick-rodgers** [comment] 2019-03-21 11:53
So you need to change the content type of the modern page? Can you describe that scenario or what you are trying to do?

**Comment by Sartor87** [comment] 2019-03-22 15:03
@patrick-rodgers I've checked with the team and it seems we no longer need to set Content Type. Thx!

**Comment by patrick-rodgers** [comment] 2019-03-22 23:55
Great, thanks for letting us know. Will close this issue. Cheers!

**Closed by patrick-rodgers** 2019-03-22 23:55 UTC
Labels: area: code, status: details needed, type: enhancement
