### ISSUE TITLE
[Syntax] Cannot build the application because of syntax errors

### ISSUE THREAD

**Issue by SkyleOri** [pnp/pnpjs#1047] opened 2020-02-03 05:00 UTC
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.0.2]

Please specify what version(s) of SharePoint you are targeting: [SharePoint 2013]

### Expected Behavior
No error when build the application

### Observed Behavior
3 errors as below in the build time:
**1. File: node_modules\@pnp\sp\clientside-pages\types.d.ts**
    set column(value: CanvasColumn **| null**);
--> I have to add **| null** to make it work.
**2. File: node_modules\@pnp\sp\fields\types.d.ts**
export interface IFieldCreationProperties extends ITypedHash<string | number | boolean **| undefined**>
--> I have to add **| undefined** to make it work.
**3. File: node_modules\@pnp\sp\search\suggest.d.ts**
export interface ISuggestQuery {
    [key: string]: string | number | boolean **| undefined**;
--> I have to add **| undefined** to make it work.

### Steps to Reproduce
Run: npm run build
I saw the issue 2 and 3 from the previous version (2.0.0), now I see issue 1 in this version. That is quite annoyed when I have to fix this issue after each update.

**Comment by patrick-rodgers** [comment] 2020-02-03 15:48
You're the first person to report this so its not something we have known about and ignored. Can you share your tsconfig.json? As is I can't reproduce this with the information you've shared - if you can help us understand why this is happening with detailed reproduction steps we can try and help. Thanks!

**Comment by SkyleOri** [comment] 2020-02-04 02:20
I apologize if what I mentioned or the way I described is not good. Below is my current tsconfig.json 's content. Please do let me know if you need need more information.
`{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
`

**Comment by patrick-rodgers** [comment] 2020-02-04 14:59
Can you try setting strictNullChecks to false OR set skipLibCheck to true? We don't build to support strictNullChecks currently and I think that is where the problem is.

**Comment by SkyleOri** [comment] 2020-02-05 08:30
I have problem with **setting strictNullChecks to false**, it throws some syntax errors from my own code. However, **setting skipLibCheck to true** helps to resolve the issue. Thank you.
I just wonder: If other users would like to use the library, do they still have to input that configuration when the project is initialized by themselves?

**Comment by patrick-rodgers** [comment] 2020-02-05 15:28
strictNullChecks is a severe check to enforce on libraries you import, skipLibCheck tells tsc to not check your imports from external libraries. Part of the issue with strictNullChecks is that you have to go through and add | null and | underfined, etc everywhere and then check those cases to pass. IF you want to use strictNullChecks with your code then it is usually a good idea to also set skipLibCheck.

**Comment by SkyleOri** [comment] 2020-02-06 01:39
OK! Thank you for your information.

**Comment by patrick-rodgers** [comment] 2020-02-06 13:48
Right on, will close this issue. Thanks!

**Closed by patrick-rodgers** 2020-02-06 13:48 UTC
Labels: area: code, status: details needed, type: someting isn't working
