### ISSUE TITLE
web.getUserById() does not return a promise

### ISSUE THREAD

**Issue by Yvand** [pnp/pnpjs#1854] opened 2021-08-18 15:28 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [2.8.0]

Please specify what version(s) of SharePoint you are targeting: [SPO]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
According to [the doc](https://pnp.github.io/pnpjs/sp/site-users/#get-user-by-id), `sp.web.getUserById(id)` should return a `Promise<ISiteUser>`.

### Observed Behavior
 `sp.web.getUserById(id)` returns a `ISiteUser` and it does not work.

### Steps to Reproduce
Try the sample in the documentation:
```javascript
user = await sp.web.getUserById(6);
```

**Comment by patrick-rodgers** [comment] 2021-08-18 16:45
This is by design, it allows you to select the properties you want from the user. That's an error in the docs, you would execute the request to get the user values:

```TypeScript
user = await sp.web.getUserById(6)();
```

**Comment by Yvand** [comment] 2021-08-19 07:29
Awesome, thank you for your very quick reply!

**Comment by patrick-rodgers** [comment] 2021-09-08 13:32
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2021-09-08 13:32 UTC
Labels: type: bug, area: documentation, status: investigate
