### ISSUE TITLE
Custom logger and sp.pnp requests

### ISSUE THREAD

**Issue by aslanovsergey** [pnp/pnpjs#188] opened 2018-08-01 13:34 UTC
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.1.2 ]

### Question
I wrote custom listener for Logger class from `"@pnp/logging"` and implement `log()` method where I save logs in SP List through `sp.web.lists.getByTitle("").items.add()` . It became cycle because apparently it uses logger inside and it turns out that it's my implementation of logger. Is there possible workarounds?

**Comment by patrick-rodgers** [comment] 2018-08-01 13:54
Hi @aslanovsergey - just so I make sure I understand the issue is your logger calls the pnp library, which then is calling your logger, which calls the pnp library, and creates a loop that keeps going?

That's an interesting problem, but I get what you mean. Will have to think about this a little. We could maybe introduce a way (not sure exactly how yet) to suspend logging for a single call. That would have to propagate through the entire request pipeline. Let us have a look and see what we can come up with.

**Comment by aslanovsergey** [comment] 2018-08-02 14:05
Hi Patrick, exactly

**Comment by patrick-rodgers** [comment] 2018-08-06 14:03
Hi @aslanovsergey: 

One suggestion after looking at this is to set the logging level to off in your log method, something like:

```TypeScript
const previous = Logger.activeLogLevel;
Logger.activeLogLevel = LogLevel.Off;

// your call to add the value to the list
await sp.web.get();

Logger.activeLogLevel = previous;
```
That should allow everything you want to get logged but not put the code into the loop you described. Let us know if that works for you. Thanks!

**Comment by patrick-rodgers** [comment] 2018-08-13 16:17
Hi @aslanovsergey - did the above suggestion work for you? If so we can close the issue, if not we will revisit. Thanks!

**Comment by aslanovsergey** [comment] 2018-08-13 19:48
Thanks Patrick, let’s close

**Comment by patrick-rodgers** [comment] 2018-08-13 20:40
Great, thanks!

**Closed by patrick-rodgers** 2018-08-13 20:40 UTC
Labels: area: code, status: answered, type: question
