### ISSUE TITLE
Timeline: Should it limit moments to those provided to constructor?

### ISSUE THREAD

**Issue by wmertens** [pnp/pnpjs#2206] opened 2022-04-07 11:33 UTC
Question regarding v3 Timelines:

I noticed that .on and .emit use Proxy to allow any moment to be provided.

Would it not be safer to initialize all moments at construction time and throw when trying to emit/subscribe an unknown moment?

Possibly with a helper that allows adding moments after construction?

That way, you can't mistype moments, and there's no need for the Proxy objects.

**Comment by patrick-rodgers** [comment] 2022-04-07 12:21
Nope, that is by design. You could certainly build your own Timeline that worked that way, but this is intentional. Type checking at build time should block typos, and if not they would appear pretty quickly with testing. Adding all that extra complexity and overhead doesn't add much value.

**Comment by juliemturner** [comment] 2022-04-10 15:19
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Closed by juliemturner** 2022-04-10 15:19 UTC
Labels: type: question, status: by design, area: code
