### ISSUE TITLE
Issue with searchWithCaching after upgrading to 2.3.0

### ISSUE THREAD

**Issue by chaitanya-SharePoint** [pnp/pnpjs#1678] opened 2021-04-05 18:20 UTC
### Category
- [ ] Bug

### Version

Please specify what version of the library you are using: [ 2.3.0 ]
![Screenshot_2](https://user-images.githubusercontent.com/28508253/113731477-d2d81680-96c6-11eb-9029-86600e3b1801.png)
After upgrade, Polyfill remained same
`"@pnp/polyfill-ie11": "^2.0.2" `
![image (3)](https://user-images.githubusercontent.com/28508253/113599267-5bde4780-960c-11eb-910a-c543e1454ad5.png)

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online ]

### Expected
The **searchWithCaching** to return the selected properties.
Highligted are the selected properties
![image (2)](https://user-images.githubusercontent.com/28508253/113598664-79f77800-960b-11eb-9a6f-e1f0a00cd5bc.png)

### Observed Behavior
**searchWithCaching** is trimming off many selected properties(mostly date related properties) while returning the results set.
Returned properties
![image (1)](https://user-images.githubusercontent.com/28508253/113598663-795ee180-960b-11eb-9d3c-48b5d88e02b1.png)

It was working before the upgrade.
The missing properties have values in them. If the values are null atleast it should return empty or undefined.

### Steps to Reproduce
```
sp.searchWithCaching(SearchQueryBuilder('test', query)).then(
                (searchResults: SearchResults) => {
   console.log(searchResults);
});
```

**Comment by juliemturner** [comment] 2021-04-05 21:56
Can we start by clarifying what platform you're working on... is this a nodejs project or a web project? Given that you've imported @pnp/nodejs-commonjs and @pnp/sp-commonjs I'm assuming nodejs but not sure because you've also referenced the polyfills and those are for browser projects.  Regardless, before you start anything you really need to get your packages all on the same version. To simplify things you might want to refer to the [getting started](https://pnp.github.io/pnpjs/getting-started/) to pare down your packages to those that you need for the type of project you're doing.

**Comment by chaitanya-SharePoint** [comment] 2021-04-05 23:44
Hello Julie,

Thanks for your email.
This is a SharePoint Online project and it was working before we upgraded
it from 2.0.3 to 2.3.0 and once after upgrading it all the packages are now
on v2.3.0.

Regards,
Chaitanya Krishna V.

**Comment by juliemturner** [comment] 2021-04-06 13:24
Sorry, that's not what your screen shot shows, so it wasn't clear.  

Operating under the assumption that you're working in a branch of your code for the update so that you can clean it up a bit... If that's the case then I would start by removing all the @pnp libraries except @pnp/sp and @pnp/graph (assuming your making calls to the graph) and @pnp/polyfills-ie11 (assuming you need to support older browsers like IE11) and making sure the version number for them is 2.3.0 and 2.0.2 for polyfills. Then delete your package-lock.json and the node_modules folder and reinstall using npm i.

**Comment by patrick-rodgers** [comment] 2021-04-06 14:19
Echoing what @juliemturner said, there have been no changes to the query builder so cleaning up the installed modules should resolve the issue.

**Comment by chaitanya-SharePoint** [comment] 2021-04-06 14:53
Hello Patrick/Julie,

*Update:*
My bad I've updated the ticket's body but not the subject.
So the issue is with *sp.**searchWithCaching *in 2.3.0. When I use
*sp.search* it is working in 2.3.0.
https://github.com/pnp/pnpjs/issues/1678

Regards,
Chaitanya Krishna V.

**Comment by patrick-rodgers** [comment] 2021-04-09 15:19
Hi @chaitanya-SharePoint - unable to reproduce this currently, and there were no code changes I can find within these code paths. Can you reconfirm you removed all pnp libraries from your project and re-installed just sp / graph packages?

**Comment by chaitanya-SharePoint** [comment] 2021-04-09 18:45
Hi @patrick-rodgers, 

Yes, I deleted and re-installed the PnP packages. Still the issue exists.

**Update:**
Please see my detailed response below. This is tested in Chrome SP Editor. No solution involved.

Just troubleshooted the issue in the PnPjs Consolev2.3.0 under Chrome SP Editor.

**sp.searchWithCaching** is storing the selectedProperties of the previously ran query.

Steps to reproduce using sp.searchWithCaching in PnPjs console:

**Create two different calls:**
1. Using sp.searchWithCaching with some SelectProperties.
2.  Add one more sp.searchWithCaching below the first with different search query with a new set of SelectProperties or don't even specify selected properties, specify an empty array.
3. Run it.

**Check the console:**
The selected properties of both results PrimarySearchResults are same. Even though the SelectProperties is an empty array.

**See screenshots below:**
![Screenshot_1](https://user-images.githubusercontent.com/28508253/114226544-ae3ba300-9941-11eb-952c-e46de22098ce.png)
![Screenshot_2](https://user-images.githubusercontent.com/28508253/114226547-ae3ba300-9941-11eb-88d6-1c364497e0e0.png)
![Screenshot_3](https://user-images.githubusercontent.com/28508253/114225316-2acd8200-9940-11eb-88d4-da091e070327.png)
**Console log of Call 1**
![Screenshot_4](https://user-images.githubusercontent.com/28508253/114225619-8ac42880-9940-11eb-8584-29b78ed0083f.png)
**Console log of Call 2**
![Screenshot_5](https://user-images.githubusercontent.com/28508253/114225315-2acd8200-9940-11eb-98e5-7e572b5809c5.png)

**Comment by chaitanya-SharePoint** [comment] 2021-04-15 15:33
Hello @patrick-rodgers / @juliemturner

Just checking, did you get a chance to look into this issue. Were you able to reproduce the same?
Let me know if there's something that I can provide with.
Thank You!! :)

**Comment by patrick-rodgers** [comment] 2021-04-28 12:45
This was a bug that was introduced when we did the work adding the isolated runtime support. The issue isn't exactly what you describe, each cached search request was being cached using the same key. So all the properties, not just SelectProperties would be identical. This will be fixed in the next release.

Ahead of that if you specify a key using the optional caching options parameter things should be back to working for you.

Thanks for reporting the issue so we could get it fixed!

**Closed** 2021-05-14 15:42 UTC
Labels: area: code, status: fixed, type: bug
