### ISSUE TITLE
SPFX : some calls to pnpjs never return an answer ( success or fail ), probably because no http call is made anyway

### ISSUE THREAD

**Issue by JMTeamway** [pnp/pnpjs#1277] opened 2020-07-16 10:40 UTC
### Category
- [x] Question

### Version
Please specify what version of the library you are using: [    latest     ]
Please specify what version(s) of SharePoint you are targeting: [   Online      ]

### Expected / Desired Behavior / Question
I use pnpjs inside an SPF webpart to make call to graph API.
I expect to have an answer to each call I make.

### Observed Behavior
Sometimes ( spent hours and still not able to systematically reproduce nor to find anything more specific than that ), my calls to thenable pnpjs interface just never give me a response :  no then(), no reject()

### Steps to Reproduce
I can't systematically reproduce the behavior.

### Detailed explanations
My webpart perfectly works most of the time, so I imagine the code is OK.
The causes I see for such a behavior could be :
- an issue in the affectation of the webpart context / pnpj initialisation

```
return super.onInit().then(_ => {
  graph.setup({
    spfxContext: this.context
  });

  // The first calls to pnpjs are made in the dataProvider constructor 

  this._dataProvider = new SharepointDataProvider([...]);
});
```
- an issue onb the way I declare the graph object in my Dataprovider :

```
import { graph } from "@pnp/graph";
```

- an issue on the way I call pnpjs :
I created a method to reject the call after a timeout to deal myself with the lack of answer. 
Any comment on this welcome ! ;-) 

```
this.callAsyncWithTimeout( 
  graph.groups.getById(this._groupId).members.select("id", "displayName", "mail"), 
  'members.select',
  4000 
)
.then(result => {})
.catch(error => {});

```
```
private callAsyncWithTimeout = (callBack, callbackName, timeout) => new Promise((resolve, reject) => {
  let resultReturned = false;

  callBack()
    .then(result => {
        resultReturned = true;
        resolve(result);
    })
    .catch((error) => {
      reject(error);
    });

  setTimeout(() => {
    if(!resultReturned){
      reject('TIMEOUT');
    }
  }, timeout);

})
```

Having a look at Chrome Console, I see nothing different between the working and the failing scenarios.

Having a look at Chrome Network tool, when the component fails, I see no call to graph api going out.
This should indicate that something went wrong inside pnpjs, and that the call to graph api was just not made.

I post this as a question and not a bug.
Do you have any idea, tips, suggestion on why I would sometime never get an answer from such a call ?
Do you have any idea on how I could use pnpjs differently to give me more feedback on what is happening ?
Do you have any idea on how I could debug such a scenario ?

Thanks a lot for your help !

**Comment by patrick-rodgers** [comment] 2020-07-31 20:01
The library can either error or execute a request (which might be successful or error). If no request is sent and no error is thrown it sounds like the request was never invoked. You can review the [docs on logging](https://pnp.github.io/pnpjs/logging/) which can give you detailed info about what is happening. Debugging your application is a larger topic than we can support through the issues list.

**Comment by JMTeamway** [comment] 2020-08-04 16:40
Hi @patrick-rodgers , thanks for the answer.

I installed the logger and gave a try by adding custom logs just before my call to pnpjs ( the 'callBack()' line) , and just after I get its answer. 
I can clearly see both of my logs, but nothing between : it seems I do not display logs that pnpjs may provide.

Here is my updated code :
```
// subscribe a listener
Logger.subscribe(new ConsoleListener());
// set the active log level
Logger.activeLogLevel = LogLevel.Verbose;
// test log
Logger.write("Testing logger subscrption ...", LogLevel.Warning);

  callBack()
    .then(result => {
      Logger.write("Unsuscribing logs ...", LogLevel.Warning);
        Logger.clearSubscribers();
        console.log('    => call' + retriesLeft + ' returned a result !!!');
        resultReturned = true;
        resolve(result);
    })
    .catch((error) => {
      Logger.clearSubscribers();
      console.log('    => call' + retriesLeft + ' did not succeed :' );
      reject('Call' + retriesLeft + ' : ' + error);
    });

  console.log('    => set timeout'+retriesLeft+' to ' + timeout +'ms');
```
Here is the output of a debug session :
```
    => Call4 graph.groups.group.members.select(id, displayname, mail)()
Message: Testing logger subscrption ...
    => set timeout4 to 4000ms
[...]
Message: Unsuscribing logs ...
    => call4 returned a result !!!
```

Anything I did wrong ?
I understood this method would display verbose log from pnpjs inside code, is that right ?
Do I have anything to do with pnpjs to set it outputting verbose logs ?

I would like to be clear, I am pretty confident with my code and I have everything I need to debug it.
I am sure I call pnpjs correctly, and that 'sometimes' it does not answer.
So it is pnpjs graph I would like to debug ...

**Comment by JMTeamway** [comment] 2020-08-31 07:45
Hi @patrick-rodgers , excuse me if I insist to much, but I don't think this ticket should be marked as "Answered"  considering my last answer.

Could I please have an answer, I'm confident I can contribute to the quality of PnPjs if I were able to debug and maybe fix that behavior ...

**Comment by juliemturner** [comment] 2020-08-31 14:43
@JMTeamway -- I might suggest that instead of trying to put logging in the code you instead focus on writing a simple test solution that demonstrates the bug. Then, watch the network calls in your browsers debug window to make sure the calls are being made and not answered. Once you have the calls isolated and can provide that code sample to us with a reproducible issue, we'd then be able to review and provide you more assistance.  

At this point although I know you believe you have found a bug the code and description you have provided is overly complicated and does not give us enough to go on to assist you since we cannot reproduce this issue.

**Comment by JMTeamway** [comment] 2020-08-31 14:56
@juliemturner  thanks for the reply, that's fair, I'll try to setup such a solution.

**Comment by patrick-rodgers** [comment] 2020-09-10 18:28
Closing this issue - if you can create a way for us to reliably reproduce the issue please open a new issue and ref this one including all the new details you can.

**Closed by patrick-rodgers** 2020-09-10 18:28 UTC
Labels: area: non-library, status: answered, type: someting isn't working
