### ISSUE TITLE
Updating TermStore throws 403 - "OAuth only flow is enabled and the call has not been issued from an app"

### ISSUE THREAD

**Issue by wizneeraj** [pnp/pnpjs#2606] opened 2023-03-22 12:17 UTC
### Category
- [ ] Enhancement
- [X] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 3.13 ]

Please specify what version(s) of SharePoint you are targeting: [SharePoint Online ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
SPFx Application customizer should be able to make CRUD operations in the Term Store

### Observed Behavior
We are trying to update Term set with custom property in our SPFx Application customizer and while doing so we are receiving a 403 error - "OAuth only flow is enabled and the call has not been issued from an app"

I noticed there was an issue already raised #2552 and it should be fixed in the latest version, but we are still experiencing the issue. If we are creating the sp context as below

`import { SPFxToken, SPFx } from "@pnp/sp";

sp = spfi().using(SPFx(context), SPFxToken(context));`

then all API calls are failing. Based on #2570 comment - [https://github.com/pnp/pnpjs/issues/2570#issuecomment-1429869152](url) what should be the webApiPermissionRequests that should be added in the package-solution.json file for List & TermStore operations?

**Comment by juliemturner** [comment] 2023-03-22 13:17
Duplicate of #2552

**Comment by juliemturner** [comment] 2023-03-22 13:39
Sorry, I saw the title and the beginning and just marked it duplicate... probably would be useful to give a title that indicates your real question in the future.

Anyway, I honestly don't know the answer to that without going to see what the options are in the App Registration in AAD, guessing (maybe TermStore.ReadWrite.All), and trial and error or maybe some googling... although I don't hold out much hope that there's an answer already published because, we're using non-documented APIs to give the sp package access to Taxonomy services meant for the Graph. So, that said you might be better off by simply switching to the graph to do this although you'd have to use `graphPost` syntax as we haven't formally implemented them in the graph package. 

Here's an example ([graph docs](https://learn.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-1.0&tabs=http))
```
const graph = graphfi()...
await graphPost(GraphQueryable(graph.sites.getById({site-id}).toUrl(), `//termStore/sets/{set-id}/children`),
                {
                    body: JSON.stringify(
                        {new term}
                    )
                });
```
If you decide to go the sp route, be aware you only need the token for adding the term all the other apis use cooking auth and thereby fail when you add a token.

**Comment by wizneeraj** [comment] 2023-03-23 12:55
@juliemturner - Thanks for the update. I had to add the TermStore.ReadWrite.All permission in the webApiPermissionRequests and also use the `spfi().using(SPFx(this.context), SPFxToken(this.context));` context for the update to work. Please update the documentation as it will help others making Create, Update & Delete operations with Taxonomy term store.

**Comment by patrick-rodgers** [comment] 2023-03-27 14:30
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2023-03-27 14:30 UTC
Labels: type: question, status: answered, area: code
