### ISSUE TITLE
Batch processing on SharePoint 2013: Cannot read property 'createBatch' of undefined

### ISSUE THREAD

**Issue by unnieayilliath** [pnp/pnpjs#332] opened 2018-11-01 13:40 UTC
### Category
- [ ] Bug
- [ ] Question

### Version
@pnp/pnpjs@1.2.3

Please specify what version(s) of SharePoint you are targeting: [      On-Prem 2013   ]

### Expected / Desired Behavior / Question
I am trying to see if I can use PnP batch processing in my SP 2013 site. I am adding 25 items into a SharePoint list using bacth execute method.
```
`function BatchTest(){

var batch = new pnp.sp.createBatch();
var promises = [];

for (var i = 0, len = 25; i < len; i += 1) {
   promises.push(pnp.sp.web.lists.getByTitle('Forecasts').items.inBatch(batch).add({ "Title": "Title " + i }));
}

Promise.all(promises).then(function() {
    console.log("Batch items creation is completed");
});

batch.execute();
}`
```
### Observed Behavior
The execution fails as below:

pnp.js:18 Uncaught TypeError: Cannot read property 'createBatch' of undefined
    at new e.createBatch (pnp.js:18)
![image](https://user-images.githubusercontent.com/9658606/47855158-0fabcf00-dde4-11e8-835b-7242d567685d.png)

### Steps to Reproduce

```
function BatchTest(){

var batch = new pnp.sp.createBatch();
var promises = [];

for (var i = 0, len = 25; i < len; i += 1) {
   promises.push(pnp.sp.web.lists.getByTitle('Forecasts').items.inBatch(batch).add({ "Title": "Title " + i }));
}

Promise.all(promises).then(function() {
    console.log("Batch items creation is completed");
});

batch.execute();
}
```

Does the batch processing work against SP 2013 ?
Thank you for your feedback!

**Comment by koltyakov** [comment] 2018-11-01 14:22
Hi @unnieayilliath, 

SP 2013 doesn't support batch API. No luck, there is no such a feature at the backend.
For SP 2013, requests can be batched only logically with (Promise.all). Of course, it's separate physical calls, but no other options in OOTB.

**Comment by patrick-rodgers** [comment] 2018-11-01 15:33
Going to close this as answered.

@unnieayilliath - this does appear to possibly be a duplicate of the question from stack exchange which you also asked on twitter. Understand you're in need of an answer but please use one channel for asking. We get a lot of questions so want to ensure we can respond to folks and not miss anything. For questions specific to this library this issues list is the best place and we'll answer as fast as we can. Thanks!

**Closed by patrick-rodgers** 2018-11-01 15:33 UTC
Labels: status: answered, type: question
