### ISSUE TITLE
Workflow-related REST endpoints

### ISSUE THREAD

**Issue by pedro-pedrosa** [pnp/pnpjs#285] opened 2018-10-15 10:01 UTC
### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.2.3]

Please specify what version(s) of SharePoint you are targeting: [SPO]

### Expected / Desired Behavior / Question
Need to implement the workflow endpoints available in the REST API.

I couldn't find any official documentation on the REST support for workflows but, from blogs available online, the following methods are known to exist:

`/_api/SP.WorkflowServices.WorkflowSubscriptionService.Current/EnumerateSubscriptionsByList`
`/_api/SP.WorkflowServices.WorkflowInstanceService.Current/StartWorkflowOnListItemBySubscriptionId`

These can be used to start workflows manually.

I found SharePoint/PnP-JS-Core#610 but it looks like it never got implemented. I can look into implementing this.

**Comment by koltyakov** [comment] 2018-10-15 11:15
Hi @pedro-pedrosa, would be great if you can jump in with implementation for these methods. Thanks!

**Comment by pedro-pedrosa** [comment] 2018-10-15 21:09
I was trying to work on this but now I'm confused... the `/_api/SP.WorkflowServices.WorkflowSubscriptionService.Current/EnumerateSubscriptionsByList` resource (or even `/_api/SP.WorkflowServices.WorkflowSubscriptionService.Current/EnumerateSubscriptions`) is accessible by POST, which suggests I should just execute `postCore()` when the `enumerateSubscriptions` property is accessed. 

However, since the resource returns a collection, it should also be filterable, selectable, etc. I tried using a select on this resource and the select worked, so it should be supported by returning a `SharePointQueryableCollection` instead of executing the request right away.

My question is, how exactly am I supposed to return a `SharePointQueryableCollection` instance if this is supposed to be called with `postCore()`, which is protected? Am I supposed to override `get()` to call `postCore()` instead of `getCore()`?

**Comment by patrick-rodgers** [comment] 2018-10-16 15:11
You could implement a method, say "getEnumerateSubscriptionsByList" within which you could call postCore. [Here is one example](https://github.com/pnp/pnpjs/blob/ca52ed44fc6f5d2d19907a6601d7275c2b1a0464/packages/sp/src/comments.ts#L82).

You can see here where we are p[assing in the expands](https://github.com/pnp/pnpjs/blob/8562be50d8f177ccf7347f292c53ec4be49fba9b/packages/sp/src/lists.ts#L325) because we have to call post for this method. The issue is the library wasn't written with the idea that a POST would operate like a get, even though there are a few cases where this is true - it breaks the model in a way.

You could override get(), though I don't love that approach since it hides what is happening. I am open to other ideas you might have on approaches.

**Comment by pedro-pedrosa** [comment] 2018-10-16 15:46
Theoretically, we are using an abstraction over an API, not the API itself. There are places in this library that methods on resources are actually compositions of multiple REST calls, not just one.

So in a way while I do agree that overriding `get()` to perform a POST request is a little bit :confused: from a developer's point of view, a user using the library probably wouldn't notice he's doing a POST instead of a GET and he probably wouldn't care anyway since it's an abstraction. Maybe if the method was called `execute()` instead of `get()` which would call `getCore` or `postCore` depending on the resource then it wouldn't be so confusing.

That said, I'm fine with the idea of creating a method that takes the selects and expands, but this will hide other options like order by, top, skip, filter...

Let me know how to proceed.

**Comment by patrick-rodgers** [comment] 2018-10-16 16:19
Agree that isn't ideal to hide the other operations. Let me think about it a bit.

**Comment by dannyfoncke** [comment] 2019-02-05 15:19
Is there any news this ?
Can workflows be started using pnp ?

Thanks

**Comment by patrick-rodgers** [comment] 2019-02-13 00:23
@dannyfoncke - no updates at this point. I think some of the work needed to implement this will be incorporated into the 2.0 release later this year.

**Comment by patrick-rodgers** [comment] 2019-11-05 20:32
For folks who may still be interested in this topic the work in v2 and [invokable](https://github.com/pnp/pnpjs/blob/dev-v2/docs/concepts/invokable.md) [default actions](https://github.com/pnp/pnpjs/blob/dev-v2/packages/sp/sharepointqueryable.ts#L156) should enable the needed functionality as discussed in this thread. Check it out and feel free to ask any questions, thanks!

**Closed** 2019-12-30 20:40 UTC
Labels: area: code, status: help wanted, type: enhancement
