### ISSUE TITLE
Graph.me.getMemberGroups() is not a function

### ISSUE THREAD

**Issue by JMTeamway** [pnp/pnpjs#1076] opened 2020-02-25 16:16 UTC
### Category
- [ ] Bug
- [x] Question

### Version
Please specify what version of the library you are using: [   2.0.3     ]
Please specify what version(s) of SharePoint you are targeting: [   SPO      ]

### Expected 
The result of a graph.me() call gives me an object on which I can call the getMemberGroups() function.

### Observed Behavior
I catch an exception :
```
me.getMemberGroups is not a function
```

Here is the content of the me object I get :
```JSON
mobilePhone:null
officeLocation:"TEAMWAY"
preferredLanguage:"fr-FR"
surname:"MAGNE"
userPrincipalName:"julien.magne@teamway.fr"
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}
__defineGetter__:function __defineGetter__() { … }
__defineSetter__:function __defineSetter__() { … }
__lookupGetter__:function __lookupGetter__() { … }
__lookupSetter__:function __lookupSetter__() { … }
constructor:function Object() { … }
hasOwnProperty:function hasOwnProperty() { … }
isPrototypeOf:function isPrototypeOf() { … }
propertyIsEnumerable:function propertyIsEnumerable() { … }
toLocaleString:function toLocaleString() { … }
toString:function toString() { … }
valueOf:function valueOf() { … }
__proto__:null
```

### Steps to Reproduce

I'm developping an SPFX webpart, so this code is REACT Typescript :
`graph.me().then((me:IUser) => {
   me.getMemberGroups();
}).catch( [...] );`

### Detailled information
I tried to have a look at PnP code without finding the cause.

graph/users/types.ts : https://github.com/pnp/pnpjs/blob/7dd9064005eb37a53eaf6614709b4ceb885bb906/packages/graph/users/types.ts
`export class _User extends _DirectoryObject<IUserType> {`

graph/directory-objects/types.ts :
https://github.com/pnp/pnpjs/blob/7dd9064005eb37a53eaf6614709b4ceb885bb906/packages/graph/directory-objects/types.ts
```
export class _DirectoryObject<GetType = IDirectoryObjectType> extends _GraphQueryableInstance<GetType> {
[...]
public getMemberGroups(securityEnabledOnly = false): Promise<{ value: string[] }> {
[...]
}
```

At that point I can't tell if there is a real bug or if I somehow miss use the api.

**Comment by koltyakov** [comment] 2020-02-27 12:05
I'm wondering how your imports look like? Did you try [@pnp/graph/presets/all](https://pnp.github.io/pnpjs/getting-started/#using-pnpgraph-setup) or make sure that all partial imports ([see more](https://pnp.github.io/pnpjs/graph/contacts/#get-all-of-the-contacts)) are required for API entities are imported as well?

**Comment by JMTeamway** [comment] 2020-02-28 15:30
Hi koltyakov, thanks for your answer.

Here is the code of my import in SPFX :

"dependencies": {
    [...]
    "@pnp/graph": "^2.0.3",
    [...]
}

`import { graph } from "@pnp/graph/presets/all";`

I saw you stated this is not a bug, so you do you confirm that graph.me.getMemberGroups() works well on your side and that the problem is on mine ?

**Comment by patrick-rodgers** [comment] 2020-04-01 11:57
I am not able to reproduce this issue, the following works for me without issue:

```TypeScript
import { graph } from "@pnp/graph/presets/all";

const g = await graph.users.getById("1e7f876a-49c2-4b05-84a4-cb819ae840c4").getMemberGroups();

const g2 = await graph.me.getMemberGroups();
```

Can you provide a repo we can clone to see the issue?

**Comment by patrick-rodgers** [comment] 2020-04-08 12:48
Going to close this as not reproduceable. If you are still having this issue please open a new issue and ref this one with additional details to help us get you going. Thanks!

**Closed by patrick-rodgers** 2020-04-08 12:48 UTC
Labels: area: code, status: details needed, type: question
