### ISSUE TITLE
Gulp Bundle shows many warnings

### ISSUE THREAD

**Issue by PavelBrokhman** [pnp/pnpjs#1530] opened 2021-01-13 20:34 UTC
For more than 2 years we have used package which includes several web parts in it. 
We have decided to update one of the web part and use @pnp/sp module. When we used gulp bundle we got a lot warnings similar to below one. Code itself is working and we are getting proper results. Should we ignore those warnings?

```
[33m./node_modules/@pnp/sp/items/index.js[39m
[33mModule Warning (from ./node_modules/source-map-loader/index.js):[39m
[33m(Emitted value instead of an instance of Error) Cannot find source file '../../../../../packages/sp/items/index.ts': Error: Can't resolve '../../../../../packages/sp/items/index.ts' in 'C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\@pnp\sp\items'[39m
[33mNonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../../../../../packages/sp/items/index.ts': Error: Can't resolve '../../../../../packages/sp/items/index.ts' in 'C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\@pnp\sp\items'[39m
[33m    at emitWarning (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\lib\NormalModule.js:154:16)[39m
[33m    at C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\source-map-loader\index.js:80:7[39m
[33m    at doResolve (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:184:12)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn0 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)[39m
[33m    at resolver.doResolve (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn0 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn0 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)[39m
[33m    at resolver.doResolve (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn42 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m    at _fn1 (eval at create (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)[39m
[33m    at hook.callAsync (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:238:5)[39m
[33m @ ./lib/webparts/webPartContentEditor/components/ScriptEditor.js 58:0-23[39m
[33m @ ./lib/webparts/webPartContentEditor/WebPartContentEditorWebPart.js[39m
[33m./node_modules/@pnp/sp/items/list.js[39m
[33mModule Warning (from ./node_modules/source-map-loader/index.js):[39m
[33m(Emitted value instead of an instance of Error) Cannot find source file '../../../../../packages/sp/items/list.ts': Error: Can't resolve '../../../../../packages/sp/items/list.ts' in 'C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\@pnp\sp\items'[39m
[33mNonErrorEmittedError: (Emitted value instead of an instance of Error) Cannot find source file '../../../../../packages/sp/items/list.ts': Error: Can't resolve '../../../../../packages/sp/items/list.ts' in 'C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\@pnp\sp\items'[39m
[33m    at emitWarning (C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\webpack\lib\NormalModule.js:154:16)[39m
[33m    at C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\source-map-loader\index.js:80:7[39m
```

#### Category
[ ] Enhancement

[X] Bug

[nodX] Question

#### Version
v10.22.0
PS C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise> npm -- version

{ 'sp-enterprise': '0.0.1',
  npm: '6.14.6',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.9.3',
  icu: '64.2',
  modules: '64',
  napi: '6',
  nghttp2: '1.41.0',
  node: '10.22.0',
  openssl: '1.1.1g',
  tz: '2019c',
  unicode: '12.1',
  uv: '1.34.2',
  v8: '6.8.275.32-node.58',
  zlib: '1.2.11' }
PS C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise> npm ls -g --depth=0 @microsoft/generator-sharepoint

C:\Users\pbrokhman\AppData\Roaming\npm
`-- @microsoft/generator-sharepoint@1.11.0 

#### Observed Behavior
When I have created new web part and used @pnp/sp logic with similar functionality as the updated web part, there was no such warnings. 

#### Steps to Reproduce
No idea.

**Comment by patrick-rodgers** [comment] 2021-01-14 13:17
Hi @PavelBrokhman - can you have a look at [this article in the docs](https://pnp.github.io/pnpjs/SPFx-on-premises/) and let us know if it helps you? You can also see additional details in the [transition guide](https://pnp.github.io/pnpjs/transition-guide/). If those aren't helpful can you please give us a bit more context on what's happening? From what you've provided it isn't immediately clear what's wrong.

**Comment by PavelBrokhman** [comment] 2021-01-14 14:46
Are you sure I have to try the steps from SPFx On-Premises? I am working with online SharePoint. Second transition one, I don't think it is related to my case. It is the first time when @pnp/sp has been used in this project.

It is the issue I am not sure what might the problem is. Below I have added package list. While I don't have @pnp/sp I do not see those warnings. Once I install it they are appears. So, I am not sure whether I should worry about those warnings. It doesn't affect the code or at least I don't see that there is affect. But still there are many warnings similar to the one I showed before and all of those related to @pnp/sp, such as items, lists, site-groups and others. All of those warnings are related to operations I have used in the new code, like items, lists and site-users.
`{
  "name": "sp-enterprise",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@babel/highlight": "^7.10.4",
    "@microsoft/decorators": "1.9.1",
    "@microsoft/rush-stack-compiler-3.2": "^0.3.30",
    "@microsoft/sp-application-base": "1.9.1",
    "@microsoft/sp-build-web": "1.9.1",
    "@microsoft/sp-core-library": "1.9.1",
    "@microsoft/sp-dialog": "1.9.1",
    "@microsoft/sp-lodash-subset": "1.9.1",
    "@microsoft/sp-module-interfaces": "1.9.1",
    "@microsoft/sp-module-loader": "^0.5.1",
    "@microsoft/sp-office-ui-fabric-core": "1.9.1",
    "@microsoft/sp-webpart-base": "1.9.1",
    "@pnp/sp": "^2.0.13",
    "@pnp/spfx-controls-react": "^1.14.0",
    "@pnp/spfx-property-controls": "^1.16.0",
    "@readable/closest": "0.0.2",
    "@types/es6-collections": "https://registry.npmjs.org/@types/es6-collections/-/es6-collections-0.5.29.tgz",
    "@types/es6-promise": "0.0.33",
    "@types/microsoft-ajax": "0.0.33",
    "@types/react": "16.4.2",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "16.0.5",
    "@types/sharepoint": "^2016.1.3",
    "@types/webpack-env": "1.13.1",
    "chart.js": "^2.8.0",
    "classnames": "^2.2.6",
    "font-awesome": "^4.7.0",
    "ics": "^2.16.1",
    "justgage": "^1.3.1",
    "mdn-polyfills": "^5.18.0",
    "natives": "^1.1.6",
    "npm": "^6.11.2",
    "object-fit": "^0.4.3",
    "omers.modernshared": "file:../Omers.ModernShared",
    "react": "16.3.2",
    "react-canvas-gauges": "^1.2.1",
    "react-classset": "0.0.2",
    "react-dom": "16.3.2",
    "react-dropzone": "^10.1.10",
    "react-raphael": "^0.9.0",
    "react-resize-detector": "^2.3.0",
    "react-syntax-highlighter": "^8.1.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.9.1",
    "@microsoft/sp-module-interfaces": "1.9.1",
    "@microsoft/sp-webpart-workbench": "1.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "@microsoft/sp-tslint-rules": "1.9.1"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  }
}
`

**Comment by patrick-rodgers** [comment] 2021-01-14 19:20
I am just guessing as you really haven't shared a lot of information other than dumping tons of package names and versions. Can you share the solution so we can have a look? You state that the issue is only when upgrading the existing project and now new - so very hard to investigate an issue local to your machine/project.

**Comment by PavelBrokhman** [comment] 2021-01-15 03:13
I am not sure what you mean by "upgrading the existing project and now new" sentence. If summarize both posts, I said the next -> "I have upgraded existing project by adding new module @pnp/sp". So, there is no contradiction in it. 

I am not sure how I can add this project here. This project includes 10 different spfx web parts, thousands line of code. How exactly would you like me to add this project here? Also, this project has copyright. I cannot just give you it. Is there anything else I can give you? Maybe to add some code in my project and log information. So, you could figure out what can be done to avoid those messages. 

For instance, I can add here some the main update I have done in the code where I have used @pnp/sp. After adding this code those warnings have been received. 

`  private async _isLoggedUserAdmin(): Promise<boolean> {
    try {
        const result = await sp.web.currentUser.get();
        var userEmail = result.Email.toLowerCase();
        
        var currentUrl = new URL(window.location.href);
        let web = Web(currentUrl.origin + "/sites/SomeSite");
        const items = await web.lists.getByTitle("SomeLibrary").items();
        return items.some(item => (item["Title"] as string).toLowerCase() == userEmail);
    } catch (error) {
        return false;
    }
  }
`

**Comment by juliemturner** [comment] 2021-01-15 20:53
So, if I'm following you, this is an SPFx solution... and there are 10 web parts in it... 

And so I'm assuming you've added an init function and you're doing the imports... to mirror what Patrick said you're not really providing us enough information to help you, but the short answer is no it's not ok that you're getting those warnings.

Given the obvious complexity of your project, it would probably help if you created a new project as a sample SPFx web part, adding @pnp/sp and then doing a base implementation... when you've worked out everything there it may help you understand what's wrong with the larger project.... Unfortunately, there is no way we can just look at this list of dependencies and a small snippet of code and understand why you have a problem. By doing so you would also then have a project you could share with us if you still can't get it working.

**Comment by PavelBrokhman** [comment] 2021-01-15 21:18
First post has this section. 
--------------------------------
Observed Behavior
When I have created new web part and used @pnp/sp logic with similar functionality as the updated web part, there was no such warnings.
-------------------------------

What it means I have done such testing. I have created separated web part which was created from the scratch similar to the one from the original project. It was working. So, it means there is something in the old project which conflicts with @pnp/sp. I have tried to resolve it by myself, but I don't understand why @pnp/sp complains. I am not familiar with Source Code of the @pnp/sp to figure it out.

So, if you need additional information let me know what exactly you need: Logs, piece of code, settings, web part configuration.... I will provide it.

**Comment by PavelBrokhman** [comment] 2021-01-15 21:35
Following image is from the separated web part I have created.
![image](https://user-images.githubusercontent.com/5633942/104780823-63016200-574f-11eb-9591-56cd470407e5.png)

This image is from the project
![image](https://user-images.githubusercontent.com/5633942/104780780-4f55fb80-574f-11eb-90f1-d6fd50ac657f.png)


As you see both are the same. 

In error "Error: Can't resolve '../../../../../packages/sp/lists/web.ts' in 'C:\Projects\OmersDev\SP%20OMERS\WebParts\SPEnterprise\node_modules\@pnp\sp\lists'"  gulp bundle is looking for web.ts, items.ts, types.ts and other which is not in the folder for both projects. So, why does it work for one and is not for another?

![image](https://user-images.githubusercontent.com/5633942/104780930-90e6a680-574f-11eb-8ab2-01bc3a07c5a4.png)

![image](https://user-images.githubusercontent.com/5633942/104780957-9e9c2c00-574f-11eb-9966-02f2b9e8bab8.png)

**Comment by koltyakov** [comment] 2021-01-15 21:46
I guess for an old source-map-loader you have to disable trying processing node_modules folder to work with some TypeScript libraries.

```json
"module": {
    "rules": [
      {
        "enforce": "pre",
        "test": /\.js$/,
        "loader": "source-map-loader",
        "exclude": [
          path.join(process.cwd(), 'node_modules')
        ]
      },
```

As an option, upgrading to the latest SPFx, yours is 2 versions behind.

Many similar errors reference can be found around, all related to the loader, e.g. https://github.com/telerik/kendo-react/issues/126

**Comment by PavelBrokhman** [comment] 2021-01-20 15:02
> I guess for an old source-map-loader you have to disable trying processing node_modules folder to work with some TypeScript libraries.
> 
> ```js
> "module": {
>     "rules": [
>       {
>         "enforce": "pre",
>         "test": /\.js$/,
>         "loader": "source-map-loader",
>         "exclude": [
>           path.join(process.cwd(), 'node_modules')
>         ]
>       },
> ```
Where should it be added?

**Comment by koltyakov** [comment] 2021-01-20 15:40
Loaders are the part of Webpack plumbing, so webpack config json. https://github.com/SharePoint/sp-dev-docs/wiki/Extending-Webpack

**Comment by patrick-rodgers** [comment] 2021-02-12 15:04
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2021-02-12 15:04 UTC
Labels: area: code, status: details needed, type: someting isn't working
