### ISSUE TITLE
Sending Anchor tags in Body of Email is not getting rendered as a link in outlook.

### ISSUE THREAD

**Issue by JarialAnkur** [pnp/pnpjs#2633] opened 2023-04-05 19:55 UTC
### Category

- [x] Question

### Version 

Please specify what version of the library you are using: [    3.12.1     ]

Please specify what version(s) of SharePoint you are targeting: [   1.15.0      ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.*

### Expected / Desired Behavior / Question
I am using sp.utility.sendEmail to send the email, and in the Boy of the email I am adding an anchor tag (<a></a>) as the body is written in HTML . Link in this HTML tag is: 
ms-word:ofe|u|https://dev.sharepoint.com/sites/Dev/Files/Sample/Demo Folder1/hello.docx

But this anchor tag should come as a link in the email, instead of coming as plain text.

### Observed Behavior
I am using sp.utility.sendEmail to send the email, and in the Boy of the email I am adding an anchor tag (<a></a>) as the body is written in HTML . Link in this HTML tag is: 
ms-word:ofe|u|https://dev.sharepoint.com/sites/Dev/Files/Sample/Demo Folder1/hello.docx

But this anchor tag is not coming as a link in the email, instead it is coming as plain text.

But when I use a link like following: 
https://dev.sharepoint.com/sites/Dev/_layouts/15/Doc.aspx?sourcedoc={7fce3b96-55f4-497f-8707-e6e54bad197c}&action=View

It works perfectly fine. Is there any way to encode the HTML to show the link as clickable in Outlook. 

After some more Research I can see that in the network call, Sharepoint API is indeed having this link embedded in the body of Email,  but for somehow. It is not rendering in the outlook.

Thank you for your feedback!

**Comment by juliemturner** [comment] 2023-04-05 20:42
>After some more Research I can see that in the network call, Sharepoint API is indeed having this link embedded in the body of Email, but for somehow. It is not rendering in the outlook.

Based on this, it seems that the library is working as intended as so this is not a bug with the library but rather and issue with how the API works. I don't have any further information for you but maybe someone else in the community has had this experience and has more to offer.

**Comment by bcameron1231** [comment] 2023-04-05 22:39
I am making an assumption that you're testing this in Outlook Online. Outlook Online does not support ms-word schema links, and they will be stripped out... no matter how you encode them. 

This link is only supported in Outlook Desktop. 

As such, unfortunately there isn't much we can do to help you here.

**Comment by juliemturner** [comment] 2023-04-10 16:24
I'm going to close this issue as answered. If you have further issues, please feel free to create a new issue and reference this one.

**Closed by juliemturner** 2023-04-10 16:24 UTC
Labels: type: question, status: answered, area: non-library, area: coding request
