### ISSUE TITLE
DirectoryNotFoundException when adding files to folder

### ISSUE THREAD

**Issue by jpalo** [pnp/pnpjs#1013] opened 2020-01-16 13:17 UTC
### Category
- [ ] Enhancement
- [ ] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [1.3.8]

Please specify what version(s) of SharePoint you are targeting: [Online]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.* >> Cannot update ATM.

### Expected / Desired Behavior / Question
I'd like to upload file to a folder as documented by only defining file name in folder.files.add. I do this: `await sp.web.getFolderByServerRelativePath(targetFolderUrl).files.add(targetFileName, blob);`

targetFolderUrl is `/sites/projectfolders_test/slow21/01%20Handover%20documents/`
targetFileName is `Document.docx`

### Observed Behavior
There is error `System.IO.DirectoryNotFoundException`. 

HTTP POST is being made to URL `https://XYZ.sharepoint.com/sites/projectfolders_test/_api/web/getFolderByServerRelativePath(decodedUrl='/sites/projectfolders_test/slow20/01%20Handover%20documents/')/files/add(overwrite=true,url='Document.docx')`

However, if I do this: `await sp.web.getFolderByServerRelativePath(targetFolderUrl).files.add(targetFolderUrl + targetFileName, blob);`

it works, HTTP POST is being made to URL: `https://XYZ.sharepoint.com/sites/projectfolders_test/_api/web/getFolderByServerRelativePath(decodedUrl='/sites/projectfolders_test/slow30/01%20Handover%20documents/')/files/add(overwrite=true,url='/sites/projectfolders_test/slow30/01%20Handover%20documents/Document.docx')`

Question is, why does it require server relative URL as targetFileName parameter when all samples indicate file name is required?

Please note that the folder names must be able to support special characters, that's when e.g., getFolderByServerRelativeUrl starts to break.

![image](https://user-images.githubusercontent.com/6917905/72533307-a2b41600-387d-11ea-95e0-6fc912d932a2.png)

**Comment by koltyakov** [comment] 2020-01-16 14:33
My guess is that there is no folder with `targetFolderUrl` path and it should be created first when a document.

When using a path in add-filename property SharePoint also creates a folder as a side effect (not sure, got to check). Or maybe folder path require additional chars to be escaped.

**Comment by koltyakov** [comment] 2020-01-16 14:41
What's the exact folder path with special chars? I guess it's not `/sites/projectfolders_test/slow21/01%20Handover%20documents` but something else.

**Comment by jpalo** [comment] 2020-01-16 14:47
All testing and behavior I described was done using the  `/sites/projectfolders_test/slow21/01%20Handover%20documents` type of "simple" folder structure. 

That special character folder structure is just something I thought to mention as I've found some PnP functions appear to be constructing malformed REST queries in these scenarios.

**Comment by koltyakov** [comment] 2020-01-16 14:57
Not reproducible, really. On the same exact names but changed relative part to a test site. However, I'm testing with v2. But 1.3.* was in prod on similar tasks for a long time on numerous projects without such issues.

What about *Path methods (getFolderByServerRelativePath) do they behave the same for you? *Path methods treat more special characters which should not be usually used.

**Comment by tavikukko** [comment] 2020-01-16 15:29
possible related, SP Editor is using V2 tavikukko/Chrome-SP-Editor#62

**Comment by patrick-rodgers** [comment] 2020-01-16 19:25
For file names with special chars not all the methods work. There is for files and folders addUsingPath to support special chars. So there could be a couple things happening here and I can't quite tell from the thread which one(s) is happening:

- You need to use the proper special character methods. This is just a by-product of how SharePoint works
- We may be over-escaping some paths? Need examples
- We may be incorrectly escaping paths? Need examples

Help me understand a bit better and we'll see how we can help. I suspect this and #1014 are duplicates.

**Comment by patrick-rodgers** [comment] 2020-01-27 14:06
Did the *Path methods help with this issue? Can we close it or are there still open questions?

**Comment by jpalo** [comment] 2020-01-27 14:23
I am already using *Path methods as the *Url methods didn't really work with special characters in folder names.

**Comment by tavikukko** [comment] 2020-01-27 14:55
I got reported issue about similar case, and it was never resolved, until the folder/filename was renamed not to contain spaces. I was not able to reproduce it (SP2016). I was suspecting that a curtain CU could be the cause...but @jpalo was using OnLine, so not really sure about that either.

**Comment by patrick-rodgers** [comment] 2020-01-27 15:17
The Url methods aren't expected to work with special chars - just a characteristic of SharePoint.

If none of us can reproduce this I think for now will close. If we can find a case that repros consistently we can debug let's open a new issue and ref this one. Thanks!

**Closed by patrick-rodgers** 2020-01-27 15:17 UTC
Labels: area: code, status: details needed, type: someting isn't working

**Comment by jpalo** [comment] 2020-01-28 06:53
😥

**Comment by jpalo** [comment] 2020-01-28 08:36
This was due to having slash at the end of `targetFolderUrl`. Apparently although it fails the `getFolderByServerRelativePath` query, it succeeds the chained `.files.add` query IF you have server relative path to the file instead of just file name.
