### ISSUE TITLE
[2.0.0] sub module: SP-sputilities

### ISSUE THREAD

**Issue by PopWarner** [pnp/pnpjs#669] opened 2019-05-07 21:20 UTC
This issue tracks the review and preparation of a sub module for the 2.0.0 project. To finalize a sub-module the follow steps should be performed:

- [ ] Code review for TODO (do), commented out code (remove), ensure interfaces are prefixed with an "I", or not using await
- [ ] Ensure every property/method has at least one test
- [ ] Ensure all of the interface method/properties are commented
- [ ] Remove comments from class implementation files
- [ ] Ensure the docs page is updated to mention each method/property with at least a minimal example
- [ ] Search in closed issue by the label "area: sample" to see if any apply to the module you are review and add those as appropriate to the documentation
- [ ] Review/compare the code in the 1.x branch to ensure any fixes, updates, or changes are in 2.0

Once complete submit one PR per module for final review. Please make the title match the issue title and reference the issue in the body of the PR. It will then be reviewed so please check back for any feedback or questions.

**Comment by JonasBjerke89** [comment] 2019-06-18 12:38
I would like to grap this one. Please sign me up!

**Comment by PopWarner** [comment] 2019-06-18 12:42
Thank you @JonasBjerke89! You rock! Your all good to go here. Status changed from "help wanted" to "in progress". Thanks again! :)

**Comment by JonasBjerke89** [comment] 2019-06-18 12:52
Perfect!

Did you guys have a "getting started guidance" to ensure consistency?

**Comment by PopWarner** [comment] 2019-06-18 13:12
There is the dev-v2 readme, which can be found here: https://github.com/pnp/pnpjs/blob/dev-v2/README.md

There was also a contributor call last Friday, which was recorded and will be available soon. It highlights in detail additional guidance. I can send you the link when it’s uploaded. :)

**Comment by JonasBjerke89** [comment] 2019-06-18 13:23
I was on the call last Friday, but I find it quite confusing working with the tests implementation. 
Should it be located in "pnpjs/test/sp"-folder or "pnpjs/packages/sp/__tests"-folder?

At this point there are test implementation in both places. Patrick showed the regional settings example in the "pnpjs/test/sp"-folder (as far as I remember), but the latest PR on the views submodule has done work in the other location.

**Comment by JonasBjerke89** [comment] 2019-07-04 08:40
Hey @patrick-rodgers 

Can you sort this out for me? I would very much like to get going and contribute to this ;-)

**Comment by patrick-rodgers** [comment] 2019-07-08 16:09
Sorry, just saw this. Tests should now be in the root test folder. The other folder is old and will be deleted, but we haven't yet so folks can grab the old code easily. The views work was in the wrong spot and was moved when it was merged. The coverage data should 100% be ignored for now or used as a guide as you are writing tests. I don't currently find it super accurate so we might remove it eventually.

**Comment by JonasBjerke89** [comment] 2019-07-09 06:04
Thanks @patrick-rodgers!

What about the TypeError when running "npm test" - is that to be ignored as well as the coverage?
The steps to reproduce:

- Fork
- Clone
- npm install -> npm test (without any modifications)

My experience is about 3 weeks old now, maybe I've got a faulty repo cloned at that time?

**Comment by patrick-rodgers** [comment] 2019-07-09 13:35
Yes, please do a pull to get the latest changes as I don't see that anymore. Plus a good amount of new stuff has been merged since so good idea to refresh before you start. Thanks!

**Comment by JonasBjerke89** [comment] 2019-07-11 12:25
Sure! Did a git pull upstream dev-v2 and can see a whole lot of changes! :-)

Unfurtunately, npm test still gives me an error - this time a different one:
![image](https://user-images.githubusercontent.com/21952399/61050487-62b03a00-a3e7-11e9-80f1-f1703e44534c.png)

'pnp-test-site' is empty. Do I need to specify a site url somewhere when running npm test?

**Comment by JonasBjerke89** [comment] 2019-07-11 12:44
Oh, I think I got it now (settings.example.js)

I will continue and get back to you, if I stumble onto more questions along the way :)

**Comment by patrick-rodgers** [comment] 2019-07-23 13:23
Yes you need to setup the settings file. We have [some docs on that here](https://pnp.github.io/pnpjs/documentation/debugging/#setup-settingsjs), but of course it could be better.

**Comment by JonasBjerke89** [comment] 2019-07-23 16:42
Yup, I think I got it 💪 PR is ready.

**Closed** 2019-11-01 13:47 UTC
Labels: [v2] Done
