### ISSUE TITLE
IList.breakRoleInheritance() not shows as missing design time but missing on runtime

### ISSUE THREAD

**Issue by waldekmastykarz** [pnp/pnpjs#1191] opened 2020-05-07 13:59 UTC
### Category
- [ ] Enhancement
- [ ] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: 2.0.4

Please specify what version(s) of SharePoint you are targeting: SPO

### Expected / Desired Behavior / Question

With the following preset:

```ts
import { SPRest } from "@pnp/sp";

import "@pnp/sp/webs";
import "@pnp/sp/lists";
import "@pnp/sp/items";
import "@pnp/sp/fields";
import "@pnp/sp/site-groups/web";

export const sp = new SPRest();
```

Calling:

```ts
sp.web
  .lists.getByTitle(listTitle)
  .breakRoleInheritance(true);
```

seems just fine design-time but on runtime fails with error that breakRoleInheritance is missing. Adding `import "@pnp/sp/security/list";` fixes the issues. Not sure if this behavior is by design due to some limitations. Docs do mention that the security import should be included but it could be easily missed if TypeScript doesn't mention that something's wrong.

Not sure if you were already aware of it and if it's something you could look into but I thought I'd let you know.

Hope it helps.

**Comment by patrick-rodgers** [comment] 2020-05-08 15:10
This is by design as you need to selective include the security methods. Sometimes the IDE seems to pick up methods even if they aren't directly included. I don't see this often and usually it goes away if you rebuild or close/open the IDE. This isn't ideal - but I am not sure of a way to fix it from within the library.

I did double check and we aren't adding that to the interface outside of the security sub-module so I think everything is working as expected on side.

Going to close this but if you can find a pattern or see where we are wrong please do let us know.

**Closed by patrick-rodgers** 2020-05-08 15:10 UTC

**Comment by waldekmastykarz** [comment] 2020-05-08 20:32
Will do! Thank you for the additional explanation! 👍
