### ISSUE TITLE
Unable to appear People web part with descriptive layout

### ISSUE THREAD

**Issue by umaknow-annie** [pnp/pnpjs#517] opened 2019-02-25 18:32 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [ 1.2.8 ]

Please specify what version(s) of SharePoint you are targeting: [ SharePoint Online]

### Expected / Desired Behavior / Question

I am trying to copy the properties of people webpart inside a ClientSideWebpart. Here is the result of the getProperties  :

![image](https://user-images.githubusercontent.com/39703457/53358952-aa826900-38ff-11e9-8ae6-faddc4ca4795.png)

When I use setProperties, I have the same properties :

![image](https://user-images.githubusercontent.com/39703457/53359330-9f7c0880-3900-11e9-9360-e94f01dd7577.png)

But when I open the page in sharepoint, the webpart appear with the compact layout. Here is the code I use :

```
const webPartCopy = ClientSideWebpart.fromComponentDef(partDef);
const properties = webPart.propertieJson;
webPartCopy.setProperties(getProperties(properties));
```

Thank you for your feedback!

**Comment by patrick-rodgers** [comment] 2019-02-26 00:51
Can you share your full code? Including where you load and save the page? Want to ensure we can duplicate your code and find the issue. Thanks!

**Comment by umaknow-annie** [comment] 2019-02-26 14:59
This is how i get the page 
```
const pageFile = (await this.getListByUrl("SitePages", web)).items.getById(id).file;
return ClientSidePage.fromFile(pageFile);
```
Here is the set properties code
```
const properties = {
     layout: 2,
     persons: [
          {
               department: "",
               id: "test@example.com,
               linkName: "Facebook",
               phone: "",
               role: "test@example.com,
               sip: "",
               upn: ""
         },
          {
               department: "",
               id: "test2@example.com,
               phone: "",
               role: "test2@example.com,
               sip: "",
               upn: ""
         },
     ]
}

webPart.setProperties(properties);
```

And this is how i save the page
```
targetPage.addSection().addControl(webpart);
targetPage.save()
```

**Comment by koltyakov** [comment] 2019-02-26 15:38
I guess this one also is connected to the general issue with client-side pages webparts provisioning https://github.com/pnp/pnpjs/issues/504

**Comment by patrick-rodgers** [comment] 2019-02-26 16:35
@koltyakov - maybe, I haven't had a chance to really dig into it yet.

**Comment by umaknow-annie** [comment] 2019-02-27 14:57
I have a similar problem with the image web part. When I crop an image the properties are set in the web part. The caption text appear but the image doesn't appear. Here is the json properties of my client side web part.
![image](https://user-images.githubusercontent.com/39703457/53499104-b3954680-3a75-11e9-8d9b-9d1a2bebe85a.png)

**Comment by patrick-rodgers** [comment] 2019-03-07 00:48
Closing this as a duplicate of #504  - please retest and open a new issue after the next release this Friday March 8 2019. You can see more details in the issue thread on exactly what happened. Thanks!

**Closed by patrick-rodgers** 2019-03-07 00:48 UTC
Labels: area: code, status: details needed, type: question
