### ISSUE TITLE
Like/Unlike SharePoint ListItem raises "No observers registered for this request"

### ISSUE THREAD

**Issue by DennisKuhn** [pnp/pnpjs#2283] opened 2022-05-27 22:40 UTC
Thanks a lot for creating and upgrading this amazing library. I am facing an issue with PNP v3 Like/Unlike on SharePoint List Items.

### Category
- [ ] Enhancement
- [x] Bug
- [X] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: `3.3.2`

Please specify what version(s) of SharePoint you are targeting: `Online`

### Expected / Desired Behavior / Question
Execute `Like` or `Unlike` on a `ListItem` without error as when using PNP v2.

### Observed Behavior
I was able to migrate all but this to PNP v3. I can load list items, their comments and can comment.

When I execute (`ListItem.ts:105`):

```typescript
    await this.pnpItem.like();
```

I get the exception:

```shell
Uncaught (in promise) Error: No observers registered for this request. (https://pnp.github.io/pnpjs/queryable/queryable#No-observers-registered-for-this-request)
    at Proxy.execute (queryable.js:78:1)
    at Proxy.start (timeline.js:138:1)
    at Proxy.post (operations.js:8:1)
    at op (operations.js:20:1)
    at spPost (operations.js:5:38)
    at 91VZ._items_types_js__WEBPACK_IMPORTED_MODULE_1__._Item.like (item.js:17:18)
    at async ListItem.toggleLike (ListItem.ts:105:13)
```

### Steps to Reproduce
My code to load the `ListItem` through my `SharePointList` controller:

SharePointList.ts
```typescript
    import "@pnp/sp/webs";
    import "@pnp/sp/lists";
    import "@pnp/sp/lists/web";
    import "@pnp/sp/fields";
    import "@pnp/sp/folders/list";
    import "@pnp/sp/items";
    import { IList, IListInfo } from "@pnp/sp/lists";
    import { IFieldInfo, FieldTypes } from "@pnp/sp/fields/types";

    public loadAllRecords = async (filter: string): Promise<void> => {
        const plainItems = await this.list.items
            .filter(filter)
            .select(...this.selectFields)
            .expand(...this.expandFields)
            ();

            for (const plain of plainItems) {
                const instance = await this.getObject(plain);
                this.addToRecords(instance);
            }
    }

    private getObject = async (plain?: Record<string, unknown>): Promise<DataType> => {
        const instance = instance = plainToClass(this.baseModel.jsFactoryFactory(), plain, transformOptions);

        if (instance.id && !instance.pnpItem) {
            instance.pnpItem = this.list.items.getById(instance.id);
        }
        return instance;
    }
```

ListItem.ts:
```typescript
    import "@pnp/sp/comments/item";

    export class ListItem extends ListItemBase {
        // this.likeBy is filled when transforming plainToClass
        public isLikedByMe = (): boolean => this.likedBy.some(
            prospect => this.controller.site.currentUser.Id === prospect.id
        );

        public toggleLike = async (): Promise<void> => {
            const mySiteUser = this.controller.site.currentUser;

            if (this.isLikedByMe()) {
                await this.pnpItem.unlike();
                this.likedBy.splice(
                    this.likedBy.findIndex(
                        prospect => mySiteUser.Id === prospect.id
                    ),
                    1
                );
                this.likesCount -= 1;
            } else {
                await this.pnpItem.like();
                const me = getUserLookupSync(
                    mySiteUser.Id,
                    this.controller.selectedFields.get('LikedBy')
                );

                this.likedBy.push( me );
                this.likesCount = (this.likesCount ?? 0) + 1;
        }
    }
```
 
Any help is greatly appreciated :-)

**Comment by juliemturner** [comment] 2022-05-30 13:32
Thanks for all the details we'll look into this and see if we can see what the issue is.

**Comment by juliemturner** [comment] 2022-05-31 21:35
@DennisKuhn - [6/1 nightly build](https://www.npmjs.com/package/@pnp/sp) will have what we believe is the fix for this issue. If you want to test that out and make sure it's solved for you as well that would be great.

**Closed by juliemturner** 2022-05-31 21:35 UTC
Labels: type: bug, status: fixed, area: code

**Comment by DennisKuhn** [comment] 2022-05-31 22:30
Awesomest, thank you :-) I will test as soon it's on NPM :-)
