### ISSUE TITLE
406 Invalid Accept Header getAll SharePoint 2013 on-prem

### ISSUE THREAD

**Issue by c-eiser13** [pnp/pnpjs#209] opened 2018-08-23 14:29 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [Docs](https://pnp.github.io/pnpjs/) to see if your question is already addressed there. This will help us ensure our documentation covers the most frequent questions.**

### Category
- [ ] Enhancement
- [x] Bug
- [x] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of the library you are using: [  1.1.3-1 ]

*If you are not using the latest release, please update and see if the issue is resolved before submitting an issue.* *** --> Tried 1.1.4 with same issue

### Expected / Desired Behavior / Question
I am trying to use the getAll() function in an Angular 6 app for a SharePoint 2013 on-prem environment. I have tested against my 365 environment and it works properly, but not in 2013.

### Observed Behavior
In a SharePoint 2013 on-prem environment, I am getting a 406 error, "The HTTP header ACCEPT is missing or its value is invalid." Looking at the source code, I see the use of ;odata=nometadata and I am wondering if this is somehow causing the issue with 2013? I looked through some of the issues on this site to make sure this is supported in 2013, but did not find any info stating it is not. Below is the error in the console:
![capture](https://user-images.githubusercontent.com/42096464/44531311-19170d80-a6b6-11e8-9e07-05ec71ccef20.PNG)

I am currently working around this by using the code from the getAll function in conjunction with a getPaged() call, and this works properly in 2013, also pointing to the header as being the issue.
![paged](https://user-images.githubusercontent.com/42096464/44531430-62fff380-a6b6-11e8-8dcd-eb48e4b0f196.PNG)

I can continue this way, but just wanted to point this out in case it is in fact an issue. Thanks!

### Steps to Reproduce
Create a minimal Angular 6 app and use the getAll() method against a list in a 2013, on-prem environment.

**Comment by patrick-rodgers** [comment] 2018-08-23 16:38
This is indeed caused by the header in 2013. We'll have to make that an optional parameter on the method so you can override the default behavior.

**Comment by patrick-rodgers** [comment] 2018-08-23 16:45
Did this in #207 (which is a big PR with a lot of changes for the upcoming release). Will be merged and a beta released likely Friday or Monday. Thanks for reporting the issue!

**Comment by c-eiser13** [comment] 2018-08-23 17:01
Thanks for the quick response @patrick-rodgers !

**Comment by patrick-rodgers** [comment] 2018-08-24 15:54
Going to close this as it is addressed in the latest beta, 1.1.5-3, released today. Please give that a try and _reopen_ if this continues to be an issue. Thanks!

**Closed by patrick-rodgers** 2018-08-24 15:54 UTC
Labels: area: code, status: complete, type: enhancement

**Comment by c-eiser13** [comment] 2018-08-27 17:06
@patrick-rodgers thanks for the update. Installed the latest beta this morning and when I call getAll() in 2013 on-prem, I get the following 400:

![1](https://user-images.githubusercontent.com/42096464/44673397-015ec280-a9f1-11e8-844c-ed4a6fdf7ddb.PNG)

Looks like it is adding a ? at the end of the URL. I f I remove this ? in the browser, I can see XML results.

![2](https://user-images.githubusercontent.com/42096464/44673420-13406580-a9f1-11e8-90b8-ee69a8f7d634.PNG)

I took a look at the source, but could not figure out where the ? is coming from.

**Comment by patrick-rodgers** [comment] 2018-08-28 14:06
Can you please open an issue for this? Thanks!
