### ISSUE TITLE
Creating A Document Set with PNP JS

### ISSUE THREAD

**Issue by mrpullen** [pnp/pnpjs#1451] opened 2020-11-19 21:45 UTC
Is there an issue with creating a document set using PNP JS using the following code? 

I found multiple posts from the previous sp-pnp-js repository saying that it wasn't something that was supported in PNP JS due to REST API - but this solution seem to work pretty consistently - at least on my tenant.

I took code from the following link and just supplied the ContentTypeId of a Document Set. 

[https://blog.jussipalo.com/2019/12/spfx-changing-folder-content-type.html](https://blog.jussipalo.com/2019/12/spfx-changing-folder-content-type.html)

 ```
    let etfn = await this.web.lists.getByTitle("Documents").getListItemEntityTypeFullName();
    let listUrl = await this.web.lists.getByTitle("Documents").rootFolder.serverRelativeUrl.get();
    
     // first create folder
    let far: any = await this.web.folders.add(listUrl + '/' +  data.Title);

    // then get list item ID of the folder
    let fData: any = await this.web.getFolderById(far.data.UniqueId).select('ID').listItemAllFields.get();

    // then get folder as list item
    let item: any = await this.web.lists.getByTitle("Documents").items.getById(fData['ID']);

    await item.update({
        ContentTypeId: '**0x0120D52000213C8E8999D60849B819FB3B9863C0DE002D72C1716ACCA5478D8224732B12606A**'
    }, '*', etfn);
```

**Comment by patrick-rodgers** [comment] 2020-11-23 18:12
Ok - in the past we were not able to find a way to consistently make this work. If things have changed such that your approach works, that's great. Document sets are just folders, but the issue we had was they also have a special mime type associated that we were unable to set so they didn't work perfectly across all the apps etc. IF that is no longer true, awesome but we haven't looked at it in some time.

**Comment by patrick-rodgers** [comment] 2020-12-04 14:11
Closing this issue as answered. If you have additional questions or we did not answer your question, please open a new issue, ref this issue, and provide any additional details available. Thank you!

**Closed by patrick-rodgers** 2020-12-04 14:11 UTC
Labels: area: code, status: answered, type: question

**Comment by sankarkumar23** [comment] 2021-03-15 05:35
I've used the above approach and created a document set.. but the problem is.. it is unable to capture the Version History (Manually by clicking on ECB menu). When I go back to classic mode these document sets are still appearing as folders. If I create a Document Set directly from UI in classic mode.. I am able to capture version history in both classic and modern UI. Something is missing when we create a folder and change the content type to document set. Is there a way to capture the document set version in this scenario?
